### ISSUE TITLE
Release Notes Project Acoustics version 1.1

### ISSUE THREAD

**Issue by hakonstrande** [microsoft/ProjectAcoustics#1]
The Microsoft Project Acoustics team is excited to share a new update with you.

We’d like to announce Project Acoustics version v1.1 with plugin support for Unity and Unreal+Wwise. This update incorporates some of the great user feedback we’ve received since GDC 2019 and enables some exciting new features.  

What’s new in Project Acoustics version 1.1:

•	Unity MacOS support – design and deliver great acoustics on Mac.
•	Unity performance improvements – faster bake preparation on Unity. 
•	Runtime DSP performance improvements - high quality HRTF rendering at a lower CPU cost.
•	Azure Batch VM compute pool utilization improvements – faster acoustics bakes.
•	Support for streaming simulation results from disk in Unity – lower runtime memory cost.
•	Unreal Engine 4.22 support
•	Wwise 2019 support
•	Wwise UWP support

Project Acoustics uses physics at design-time to simulate sound wave propagation in your virtual world. This provides fast, low CPU, low RAM, hyper precise rendering of salient acoustics features such as occlusion, obstruction, portalling and reverberation at runtime. This means no more tedious reverb zones markup during level design or computationally expensive ray casting at runtime. Project Acoustics also provides per sound source design controls of the acoustics, bending physics to your will.

Project Acoustics version 1.1 is now available to download for both Unity and Unreal+Wwise. In those download packages we also included pre-baked sample scenes for both Unity and Unreal+Wwise that you can use for critical listening of wave propagation based acoustics.

Unity: https://www.microsoft.com/en-us/download/details.aspx?id=57346

Unreal+Wwise: https://www.microsoft.com/en-us/download/details.aspx?id=58090 

Project Acoustics documentation is there to guide you through installation and integration with both Unity and Unreal+Wwise: https://aka.ms/acoustics

The GDC 2019 Session: https://www.youtube.com/watch?v=uY4G-GUAQIE&feature=youtu.be&list=PLRs2lXTYCDQ3q9WF-4aO2SgCCCL6rSmA6 

If you’re curious about the research and theory behind Project Acoustics you can find it here: https://aka.ms/triton

**Comment by MikeChemi** [comment]
Version 2.0 is now available. #55
