### ISSUE TITLE
Changelog for UE recent update?

### ISSUE THREAD

**Issue by hectorC** [microsoft/ProjectAcoustics#100]
Hello,

I just noticed an update to the Project Acoustics plugin for Unreal Engine. It seems it was posted yesterday. Is there a changelog for that somewhere? Thanks!

**Comment by KyleStorck** [comment]
We did recently push out a patch release. We don't currently have a place where we publish release notes publicly. We need to figure that out. I'll post our internal release notes here for now.

```
## 3.0 Patch - June 2022
* Few critical bug fixes for the 3.0 release
* UNREAL
    * Added clamp to prevent reverb from clipping in Marketplace plugin
    * Changed pre-bake default save directory to be in the Project/Plugins directory 
    * Fix for ACE file drag and drop
    * Fix for AcousticsSpace transforms
* TRITON
    * Temporary fix for Android crash in Triton runtime
```


 Were you referring to the Unreal/Wwise plugin, or the Unreal Audio marketplace plugin?
