### ISSUE TITLE
Can't local build anymore with v3 & Unity

### ISSUE THREAD

**Issue by laurelhach** [microsoft/ProjectAcoustics#101]
I just installed the latest version (v3) and when I run the *.bat file I get this error :
Just before, I was with the previous version and I was running fine, but I saw the new version and cancel the generation.
I installed the new version and now I get this:

- Unity 2021.3.6f1 
- Win11 64bits.

d:\MicrosoftAcoustic>docker run --rm -w /acoustics/ -v "d:\MicrosoftAcoustic":/acoustics/working/ mcr.Microsoft.com/acoustics/baketools:2.0.143_Linux ./tools/Triton.LocalProcessor --configfile Acoustics_PrisonCells_config.xml --workingdir working

ERROR: Failed to deserialize config file: Acoustics_PrisonCells_config.xml
ERROR: Exception: XML Parsing failed - provided NVP (ProbeInfo) not found

PS: The problem is that the baketools is now using 3.0.Linux instead of the 2.0.143. 
I had to manually change the value to make it work. But I am not sure why it doesn't update correctly when I export the local bake data.

PS: I had to clear the toolset version in Unity (delete the info), then the info repopulated itself with the correct version.
Maybe this is something that could be updated automatically to avoid these kind of issues :)

**Comment by laurelhach** [comment]
@NoelCross, thanks for the explanation. But I'm fine moving to the v3. Actually it builds much faster than before (well .. I've also upgraded my computer ... so ... ) I was just wondering why it was not working with the new version :)

All is well ;)

**Comment by MikeChemi** [comment]
Glad you got this sorted out. I'll go ahead and close this issue. We will improve the upgrade path for our next release so you won't need to manually reset the tools string.
