### ISSUE TITLE
Wwise PluginNotFound

### ISSUE THREAD

**Issue by tamuranetsu** [microsoft/ProjectAcoustics#104]
MicrosoftProjectAcoustics.plugins.Unreal\Wwise\2021.1\ProjectAcoustics\Authoring.zip\Authoring\x64\Release\bin\plugins\ProjectAcousticsWwiseAuthoring.xml

```
<!--// Temporarily disable UI for spatial reverb.
<EffectPlugin Name="Project Acoustics Spatial Reverb" CompanyID="275" PluginID="5" EngineDllName="ProjectAcousticsWwise">
```

Is comment out as intended?

**Comment by MikeChemi** [comment]
Yes, this is intended. We are experimenting with new reverberation algorithms, but don't have anything ready to release yet. This is a placeholder leftover from our investigations.

**Comment by tamuranetsu** [comment]
Thank you very much. solved.

Used by PA_SpatialReverb in AcousticsGame.wproj, but didn't notice it was disabled on volume -96
