### ISSUE TITLE
Errors with Unreal Engine 5.0.3 and Wwise 2021.1.8.7831.2284

### ISSUE THREAD

**Issue by NathanCleary123** [microsoft/ProjectAcoustics#105]
Hi, 

I had Unreal Engine and Project Acoustics running fine on my local machine for the past month or so with Unreal Engine 5.0.1 but recently tried to bring on an Art Team who were all hit with errors possibly from the fact they could only download Unreal Engine 5.0.3 from the Epic Games Launcher and it may have conflicted? Here's the Errors they had -> 
![ArtTeamErrors](https://user-images.githubusercontent.com/63648420/179996652-1edc8c94-df17-4457-adf2-cfeef25ab527.png)

So I decided to start from scratch, in terms of integration of PA and Wwise, and installed Unreal Engine 5.0.3 and proceeded to install everything fresh and just set everything up again. I went through all the steps as usual but this time have been hit with some new errors on my local machine which weren't there before so would like to know where to go from here as it seems code related to identifiers and stuff not being initialized etc -> 
![Capture](https://user-images.githubusercontent.com/63648420/179997040-d54e454d-177b-462d-9963-f0bc09547d28.PNG)

Thanks in advance, 
Nathan

**Comment by NathanCleary123** [comment]
Hey,

So, inevitably, there's errors on the end of the Art Team trying to compile the project and it all seems to be Project Acoustics. :(

I'll post the error log down below but they deleted the Project's GitHub Repo from their local machine and then did a clean clone and pull from my locally working /compiling version but are hit with similar errors to which I had before. I said they should run the PatchWwise.bat just in case but it doesn't seem to have worked.

Any advice without making them have to download Wwise etc would be greatly appreciated in getting the project to compile! (Without removing PA completely!)

![CleanCollaboratorRepoPull_PAErrors](https://user-images.githubusercontent.com/63648420/180595671-5105cd7f-c86f-495f-b4c1-b65f0bd8cabc.PNG)

Thanks,
Nathan

**Comment by MikeChemi** [comment]
This is mostly because they ran PatchWwise.bat multiple times. You can only run it once. If you go to the end of AkAudioDevice.h/.cpp, remove all the duplicate entries that the multiple patches created and try again.

There's also an error about unable to link against Triton.Runtime.lib and Triton.Preprocessor.lib. Ensure that you committed all of the Project Acoustics plugin to the git repo, including the libraries in the ThirdParty folder.

**Comment by NathanCleary123** [comment]
Ok, so I included the whole Plugins folder including Binaries etc and we're still getting the same error about Occlusion when the Art Team tries to compile the project. We tried seemingly everything today including doing fresh pulls from the repo with everything deleted from their system and also going through and deleting any duplicates in the .cpp and .h files.

![Capture](https://user-images.githubusercontent.com/63648420/180630532-eb65a468-4133-4266-882a-060d08d121e2.PNG)

I've also tried gradually including more and more files and folders but the builds still don't work. I'll include the most recent version of my .gitignore file to see if maybe I'm missing something? It seems that the online repo and my local, working, machine are pretty similar now though. We also tried deleting the .vs, binaries, deriveddatacache and saved folders then recompiling with no avail.

CURRENT .GITIGNORE
# Visual Studio 2015 user specific files
.vs/

# Compiled Object files
*.slo
*.lo
*.o
*.obj

# Precompiled Headers
*.gch
*.pch

# Compiled Dynamic libraries
*.so
# *.dylib
# *.dll

# Fortran module files
*.mod

# Compiled Static libraries
*.lai
*.la
*.a
# *.lib

# Executables
*.exe
*.out
*.app
*.ipa

# These project files can be generated by the engine
*.xcodeproj
*.xcworkspace
*.sln
*.suo
*.opensdf
*.sdf
*.VC.db
*.VC.opendb

# Precompiled Assets
SourceArt/**/*.png
SourceArt/**/*.tga

# Binary Files
# Binaries/*
# Plugins/*/Binaries/*

# Builds
Build/*

# Whitelist PakBlacklist-<BuildConfiguration>.txt files
!Build/*/
Build/*/**
!Build/*/PakBlacklist*.txt

# Don't ignore icon files in Build
!Build/**/*.ico

# Built data for maps
*_BuiltData.uasset

# Configuration files generated by the Editor
Saved/*

# Compiled source files for the engine to use
Intermediate/*
Plugins/*/Intermediate/*

# Cache files for the editor to use
DerivedDataCache/*
/Test Builds/Windows
/Test Builds

airue

Any help would be great appreciated as it's only PA that seems to be causing the errors! :(

**Comment by NathanCleary123** [comment]
Hey, so strangely one of the other members did a clean pull of the repo and made sure to delete any duplicate code in the AkAudioDevice.cpp and .h files, which are strangely not in my local version, and then we got the game to build! BUT we have a few new errors which I'm a little worried about.

We made sure to only delete the duplicated code and made sure it was the same as my local error free code but we have been getting this:
![Capture](https://user-images.githubusercontent.com/63648420/180673666-2b257cd7-2f3c-4828-ba2f-cfaa49468be8.PNG)

If you could shed some light on whether we should be worried/what we should do, it'd be massively appreciated!

**Comment by MikeChemi** [comment]
Sounds like your remaining issues are with git configuration and warnings from AudioKinetic. This is not the correct forum for either of those issues.

**Comment by NathanCleary123** [comment]
Ok Mike, looks like it's all working for now (Aside from these small warnings) so thanks for the help! 

I've made sure to note everything/all the steps down and what to include in Git, it seems it was the Plugins Binaries Folder which was the main issue I believe.
