### ISSUE TITLE
Acoustics differences adding or removing objects

### ISSUE THREAD

**Issue by cdor8** [microsoft/ProjectAcoustics#106]
Hi,
I'm using the Unity package. I have a simple room (rectangle, 4 walls) that it's empty in one scene and then I have a second scene with the same room where I added some objects with different types of materials (sofas, table, cabinet). I would like to test whether the acoustics change or not. I bake the acoustics for each scene and at the moment I don't hear any difference. I'm swapping the scenes by pressing a key and I have one acoustic manager per scene with its corresponding ace file. 
I would expect to hear differences in the acoustics if the room is empty compared to when its full of objects, but I don't hear any difference. The same applies when I have two scenes with the same empty room but bake it with different materials for the walls (one using plaster and the second one using snow fresh). Even if I build the two scenes separately and play the builds one after the other. 
I can't hear any differences. 
What could be going wrong?
Thank you.

**Comment by MikeChemi** [comment]
Let's start by looking at what the acoustic bakes are doing. If you enable gizmos for the acoustics manager, you should see overlays on the scene with some acoustic properties displayed for the sound source. Are any of the values different between the two scenes?

**Comment by cdor8** [comment]
Hi, 
Thanks for the answer. I don't see differences in the acoustics properties except for the listener outdoorness which in both of the empty scenes is 0 and in the scene with the furniture is 0.9. Everything else is 0 in all scenes (empty plaster wallls, empty snow fresh walls and furniture with plaster walls). 
This is how it looks:
![image](https://user-images.githubusercontent.com/55885187/180497166-c0281155-a824-43ff-9d09-bf333a240cc2.png)

**Comment by MikeChemi** [comment]
Aha! Your acoustic queries are failing. That -3.402823E+38 value is our failure code. This usually happens if your sound source or listener is inside of the voxels. If you turn on the voxels gizmo, can you tell if the sound source is stuck inside the voxels? If so, try nudging it outside.

If that's not it, we'll need to think of other reasons why the query might be failing.

**Comment by cdor8** [comment]
Thank you. I moved the sound source and now it works.
