### ISSUE TITLE
Error: Failed to open ACE file for reading

### ISSUE THREAD

**Issue by ZedFear** [microsoft/ProjectAcoustics#107]
I'm getting this error when trying to use my baked data file:

LogAcousticsRuntime: Error: Failed to open ACE file for reading: [Z:/Darkion 5.0/Content/Acoustics/LVL_TestCombat_AcousticsData.ace]
LogAcousticsRuntime: Error: Failed to load ACE file [Content/Acoustics/LVL_TestCombat_AcousticsData.ace]

(if it matters i baked locally and imported manually)

**Comment by KyleStorck** [comment]
Hi @ZedFear. First think to check is that your ACE is physically located inside the Content/Acoustics folder. For instance, Content/Acoustics should look like this in File Explorer 
![image](https://user-images.githubusercontent.com/1233941/181261704-b83382c9-25b0-40b2-b920-ddbc66b01754.png)

**Comment by ZedFear** [comment]
Thanks! that did the trick :)
