### ISSUE TITLE
Output log error in Unreal 5

### ISSUE THREAD

**Issue by agobbett** [microsoft/ProjectAcoustics#108]
Hi, I am receiving a lot of these errors in my output log when using Project Acoustics:

LogAcousticsRuntime: Error: No key found in the acoustic query map for source:8. This most likely means this source did not register first (RegisterSourceObject) before updating.

I have attached an image of what I'm seeing on my map when using Debug controls. It's not happening with all sounds but seems like it happens intermittently. Any idea what the issue is?

![Screenshot 2022-07-30 095534](https://user-images.githubusercontent.com/63791978/181903166-a43484b1-115f-4a7d-87c0-a44c597cc57a.png)

Thanks
Alex

**Comment by KyleStorck** [comment]
I can take a closer look on Monday, but some preliminary questions for you:

1. Are you running multiple clients in a single editor by any chance?
2. Could you post all the errors you're seeing in the output log
3. Tell me more about the sound sources in the scene. How are you spawning the sound sources, how many are there, do you still get the error with just a few sound sources.

**Comment by agobbett** [comment]
Hi Kyle, Just had a look into this further.

1. I am running multiple clients in the editor. I just checked playing with 1 client and I don't seem to have these errors.
2. I also get this error multiple times when I start with 2 clients, I dont get it when i start with 1 client:

LogAcousticsRuntime: Error: No key found in the acoustic query map for source:4. This most likely means this source did not register first (RegisterSourceObject) before updating.

3. I am spawning sounds from anim notify blueprints and actor component blueprints, attached to the pawns in the scene. I am not spawning that many at a time, maybe a handful. I don't get the error on every spawned sound, just some. For example 1 gunshot will not have the error, but the next gunshot (same source) will.

Hope that helps?

**Comment by KyleStorck** [comment]
It does help, thanks. Running with multiple clients in a single editor is not a scenario that this plugin supports yet. When you run multiple clients in one editor, it creates multiple audio listeners, which both use the same sourceIDs, and they stomp all over each other in our source caches. We want to support this scenario, but it's not on our immediate roadmap.

**Comment by agobbett** [comment]
I see, makes sense. Thanks for your help.
