### ISSUE TITLE
Is the Unreal + Wwise feature-set available on the latest Project Acoustics Plug-in release för unreal 5?

### ISSUE THREAD

**Issue by nehlmark** [microsoft/ProjectAcoustics#109]
So I've been checking out Project acoustics lately as I found out that it can be used on Playstation 5, which mkes it a viable option for the game studio I'm working at.

And recently I saw that there's tools such as dynamic objects support which is crucial for me and my team. But I'm confused if that feature is only available if one use Wwise and not only Unreal? I cant find a Dynamic object component in Unreal but in Source Data Override Settings it has a toggle for Dynamic Openings.

Thanks for the help!

**Comment by KyleStorck** [comment]
Dynamic openings should still work for the Project Acoustics Unreal Audio plugin. Do you not see it listed as an addable component? 
<img width="535" alt="image" src="https://user-images.githubusercontent.com/1233941/181996779-5166193a-a64b-4320-8057-a5e3e0717f56.png">

**Comment by nehlmark** [comment]
> Dynamic openings should still work for the Project Acoustics Unreal Audio plugin. Do you not see it listed as an addable component?
> <img alt="image" width="535" src="https://user-images.githubusercontent.com/1233941/181996779-5166193a-a64b-4320-8057-a5e3e0717f56.png">

Hi! Yes I found it! Awesome! As I understood it from the documentation you can sort do you own things in code/blueprints with dynamic openings. Say you want it to function for a destructible wall say? And thanks for your answer Kyle!

**Comment by KyleStorck** [comment]
Correct. You need to notify the acoustics system the state of the doors through blueprints, which allows the acoustic parameters that are returned to be accurate as to whether that dynamic opening should sound open/closed.
