### ISSUE TITLE
Sound fades in and out with tiny motions (Wwise vs PA in separate maps?)

### ISSUE THREAD

**Issue by borogove** [microsoft/ProjectAcoustics#11]
PA 1.1, UE 4.23 (custom), VS2019, Wwise 2019.1.5.

I'm up and running in a coarse-bake acoustics environment, player running around a big area which includes a few subrooms. The effect of the environment on sounds seems glitchy in some cases. 

Most noticeable: I have a room with highly absorptive (grass, 0.7) walls/floors/ceiling, open to a much bigger area with harder surfaces. Inside the "grass room" is an object emitting a kick-drum thump once per second. Standing next to it it sounds correctly dry. As player moves outside the room into the big hard space it gets reverby. Moving away from the door, it goes to silence when the player stops moving, but any extremely small movement of the camera (= listener) causes the sound to come back up in volume for a moment and then back down to silence. It sounds like it might be restarting a blend from a previous probe point every time I move, no matter how small the move. 

I can provide video of this occurring if that's helpful.

**Comment by borogove** [comment]
The cause seems to be changes I made in order to let maps without acoustic data use wwise spatialization while those with acoustic data use PA. This is pretty important for us in the near term while we're evaluating whether or not we want to commit to using PA. 

In the UAcousticsAudioComponent constructor, if I leave the stanza `bUseSpatialAudio = false` stanza in place, then our non-acoustics maps don't work correctly. I tried moving that block into TickComponent and doing it once conditionally based on whether or not an .ACE was successfully loaded for the level, but in that case I got the reported fade-in-and-out, I guess because Wwise occlusion was conflicting with PA. 

I tried another approach, turning bUseSpatialAudio off in the constructor and conditionally turning it back on in the tick, and Wwise spatialization seems to generally work in non-acoustics maps in that case, but I'm getting many `AK::SpatialAudio::SetEmitterObstructionAndOcclusion: game object (ID:...) is not registered as a spatial audio emitter` errors to the log. 

Before I dig deeper into the Wwise occlusion/obstruction logic, do you have any suggestions for addressing this? I don't want to use separate sound components for Wwise-mode and PA-mode, because we want to re-use blueprints across our test maps.

**Comment by NoelCross** [comment]
I'm pretty sure that what you are trying to do is unsupported, but there might be a way to pull off what you desire.  I'm going to ping our contacts at AudioKinetic to see if they can chime in.

**Comment by nikunjragh** [comment]
A related question: in the non-PA maps, do you intend to use the acoustics features of the Wwise Spatial Audio Engine - like Wwise Reflect, rooms/portals etc.? Or do you mainly want a decent fallback option with spatialization + manual reverb in cases where you can't use PA?

**Comment by borogove** [comment]
@NoelCross I think I got the solution I needed -- I check for an AcousticsSpace actor in the level at BeginPlay and turn off the Wwise spatialization then instead of in the constructor. Seems to work okay.

@nikunjragh This is purely a short term thing while we're evaluating PA for a new project. I don't need all the features of Wwise, just need it not to sound like I've broken everything in non-PA maps.

**Comment by MikeChemi** [comment]
@borogove , I'm going to close this issue since you have a solution. Feel free to reopen if you find that your solution no longer works for what you need.

**Comment by borogove** [comment]
@MikeChemi This still doesn't quite work. If I turn off Wwise spatialization in `UAcousticsAudioComponent::BeginPlay` instead of the constructor, then Acoustics dry-path spatialization doesn't seem to work -- it looks like the listener position maybe doesn't update, as the dry path works near the player start but nowhere else. I suppose the solution is to just add an Acoustics Space to all our test levels, and disable via IAcoustics::SetEnabled if there's no baked data available. (The default behavior with no bake is too "boomy".)

**Comment by MikeChemi** [comment]
@borogove yeah, that should work. Thanks for the feedback on the default no-bake sound. This could be adjusted via design parameters, but then you'd have to undo those parameters when re-enabling the bake. If using SetEnabled is working for you, I'd stick with that.

**Comment by borogove** [comment]
Hmm, no, disabling acoustics leaves me with no spatialization again, it appears.

**Comment by borogove** [comment]
I was never able to get a code solution that spatialized correctly for both Acoustics-ready and non maps. We went ahead and baked acoustics data for all our maps and switched over wholesale.

I do think being able to selectively enable acoustics would be a good feature for teams in the process of evaluating PA, but this is not currently a blocking issue for me.
