### ISSUE TITLE
Unity-Azure batch service requirements

### ISSUE THREAD

**Issue by arazrm** [microsoft/ProjectAcoustics#110]
Hi.
I was trying to bake my scene using azure but after Job getting created I couldn't see any usage in the Batch Service overview tab.
I checked the Job itself and there was "Core Quota" error if I remember it correctly?
so the question I wanted to ask: is there anything specific I should do while creating Batch service?
I haven't used Azure before so I might be wrong while creating the service.
Thank u for the feedback!

**Comment by MikeChemi** [comment]
Hello! Sounds like you need to request a quota increase. Refer to the Batch documentation on how to do this:
https://docs.microsoft.com/en-us/azure/batch/batch-quota-limit

We recommend using the F8s v2 node size to get started.

**Comment by arazrm** [comment]
Thank you for the response MikeChemi!
I actually don't setup the pool myself (because I know almost nothing about Azure service :D)
I just give the unity plugin names and keys it needs and it creates the pool itself and I get the "The specified account has reached core quota" error.
this is the pool the plugin itself has created:
![Screenshot 2022-08-04 201520](https://user-images.githubusercontent.com/110555906/182889952-ebad23fc-d200-48a8-86aa-4a8952d6688d.png)

it is also a F8s v2 node size

thank you again for further guides!

**Comment by MikeChemi** [comment]
While the Unity plugin will take care of creating the pool itself, you need to do the quota request yourself. If your account has not been granted any F8s v2 quota (which by default, it hasn't), the Unity plugin will be unable to create a pool as you've seen. Please follow the documentation instructions on requesting a quota increase, specifically this section https://docs.microsoft.com/en-us/azure/batch/batch-quota-limit#request-in-azure-portal

**Comment by arazrm** [comment]
thank you MikeChemi!
