### ISSUE TITLE
How can I reduce the data size of ACE?

### ISSUE THREAD

**Issue by pmtmp123456** [microsoft/ProjectAcoustics#112]
Hello.

Acoustics is a great solution！
But the problem for me is that the data size of ACE is very large.

I want to use only Obstruction/Occlusion/Portaling of Acoustics.
So I will not use the functions related to Reverb.

Is there any way to avoid including Reverb-related information in ACE when baking?

I would like to know how to reduce the data size other than changing the values of Max Frequency / Max Horizontal Probe Spacing / Simulation Region.

Translated with www.DeepL.com/Translator (free version)

**Comment by MikeChemi** [comment]
We are working on a way to remove unwanted parameters from the ACE file. We don't have anything ready to share yet, though.

In the current version, the way to reduce the file size are the parameters you mentioned, as well as increasing receiver spacing and voxel map resolution.

**Comment by pmtmp123456** [comment]
Thanks for getting back to me.
My team considers data size important.
I look forward to more options for data to be included in ACE!

**Comment by pmtmp123456** [comment]
I have one more related question.

If I disclose the source code, can I customize it to exclude unnecessary data when creating an ACE?

By source code disclosure, I mean this.  

https://docs.microsoft.com/ja-jp/gaming/acoustics/what-is-acoustics#%E3%82%BD%E3%83%BC%E3%82%B9-%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9

**Comment by NoelCross** [comment]
@pmtmp123456 if you "license" the source code from Microsoft, you can make modifications to the source code to fit the needs of your title.  We don't allow for "disclosure" of source code to non-licensees.

**Comment by pmtmp123456** [comment]
thanks for the answer. 
I will try the method you told me.
