### ISSUE TITLE
UE5 Acoustics not working

### ISSUE THREAD

**Issue by DanteThaDevil** [microsoft/ProjectAcoustics#113]
I dont really know what i am doing wrong but after setting up my scene with acoustics and baking it then loading in and following the steps it still does not work. in-game preview it says "Acoustics Status" Not loaded, i dont understand and appreciate every help i can get. am i missing something ? Also i cant load up the Acoustics demoleve it just says "AcousticsGameUE5 could not be compiled. Try rebuilding from Source manually" So i have no way to check if im missing something in that leve
![acoustics issue](https://user-images.githubusercontent.com/55096870/186666418-19614e73-633c-44bb-a862-c0f2e48a8c8b.png)
l

**Comment by KyleStorck** [comment]
Looks like your ACE file hasn't loaded correctly. Just a few things to check

- You have an AcousticsSpace actor added to the scene, and you added your ACE file to the AcousticsData property?
- Are there any error messages in the Output Log?
- Check that your ACE file is physically located inside the Content/Acoustics folder. For instance, Content/Acoustics should look like this 
![image](https://user-images.githubusercontent.com/1233941/186685378-f4a68a03-f76b-4acb-9d51-aee60ee70512.png)


Then for the sample scene, yes you may need to rebuild from source manually, by generating a Visual Studio solution file and compiling from there.

**Comment by DanteThaDevil** [comment]
The picture did the trick, i manually put the .ace file in the folder and now it works. my question here would be do i have to do that everytime or is there a way to do it automatically ? I bake everything local. Thank you so much!

**Comment by KyleStorck** [comment]
Ya, there's a few ways to import the ACE file and we try to make as many of them work as possible.

- If you copy the ACE file to the Content/Acoustics folder first and import into UE from there, that should work
- If you drag and drop the ACE file from its original directory to the UE Content Browser, that should work (this was enabled in our most recent patch)
- If you import directly from its original directory into UE, that still does not work
