### ISSUE TITLE
High correlation of reverb tail using Unity

### ISSUE THREAD

**Issue by constantinpopp** [microsoft/ProjectAcoustics#114]
Hello,
I am currently experimenting with Microsoft Project Acoustics using the 3.0 version running in Unity directly and local bake using Docker with this image: mcr.microsoft.com/acoustics/baketools | 3.0.Linux.

When I bake the reverb for a basic shoebox room using the local bake option the reverb tails are highly correlated and appear virtually in mono, as visible in the attached video. 

Is this mono-sounding reverb tail the intended output of Project Acoustics? Or does local baking create only mono-like reverb tails and I would have to upgrade to the cloud-based baking to generate reverb tails with less correlation? Or did I miss a checkbox somewhere?

Many thanks for your help.

Best wishes,
Constantin

https://user-images.githubusercontent.com/2156449/188625117-67bf6322-41d5-4c2a-b090-07b9a01ae112.mp4

**Comment by NoelCross** [comment]
@constantinpopp , for the PA3.0 release and prior releases, the reverb tail is rendered monoaurally and duplicated in both the left and right channels.    We are hard at work on the next release which will provide a more spatially accurate reverberation rendering.

Also, the simulation results for a local bake versus baking in the cloud are identical so you shouldn't be worried about missing features with executing local bakes.

**Comment by constantinpopp** [comment]
Hi Noel, many thanks for your kind explanations and quick response.

**Comment by MikeChemi** [comment]
One note I'll add -- the reverb is decorrelated, but does not rotate at all. The left and right channels will have similar power, but different content. I don't know how that RME plugin works, but if I had to guess it is only looking at the overall power in each channel?

**Comment by constantinpopp** [comment]
Hi Mike

Many thanks for your answer. The RME plugin ("[Digicheck](https://www.rme-audio.de/digicheck.html)") shows the correlation between left and right channel in a Goniometer (vector scope), visible on the right of the screencast. It can be used to display the phase of a stereo signal. The following description is taken of their user's manual:
- 0° / mono: shows vertical line.
- Left only: shows line from the upper left to the lower right.
- Right only: shows line from the upper right to the lower left.
- 180° / out of phase: shows horizontal line.

Apologies for just putting the plugin in there without explaining why I put it there. 

Here is another video where the direct signal is occluded so that I can hear mostly only the reverberated signal, showing a rather small apparent source width of the reverberated signal:

https://user-images.githubusercontent.com/2156449/188925895-269a64a9-6d1b-428f-a759-b55afbd0c472.mp4

I think the issue maybe more related to user expectation rather than being a question about if I have used the spatializer wrongly. In music production, reverberation plugins generate "stylized" rooms, which may not exist in real life, and create usually a very wide apparent source width. This effect tends to be associated to high user envelopment and maybe an expectation associated to presentation of spaces via a recording/playback medium (loudspeakers/headphones). Here is an example of the same voice sample reverberated using Valhalla Room and converted into binaural audio:

https://user-images.githubusercontent.com/2156449/188926716-d54d60ab-849e-4bf3-a99f-50eabf7d6805.mp4

One can hear that the image is very wide (maybe too wide?).  

I understand that I am comparing apples with oranges - as the purpose of these tools is entirely different. But I wonder if it would be a nice feature if the reverberated signal would appear wider than it is now, for it not to appear as a separate, distant source. The problem of a narrow apparent source width of the reverb appears when the direct sound is coming from one side of the user with the reverb appearing in the centre. For me this effect impairs the fusion between the direct sound and the room's response, as seen in this video:
 
https://user-images.githubusercontent.com/2156449/188931366-58517cad-ae2c-441d-ba6d-fe18bbbf6cd1.mp4

I know that this example is an extreme case. Usually a player would more likely focuses on the location of sound sources rather than if the reverb of a space is nicely wide. 

I hope this explanation illustrates a bit the background on where my question is coming from. 😄 

Anyhow, many thanks for making this awesome spatializer. 😄 Having such realistic sounding occlusion and diffraction at one's finger tips without having to code anything is just awesome. 👍 

Best wishes,
Constantin

**Comment by MikeChemi** [comment]
Thanks for the detailed response! I do love the Valhalla reverb :)

I suspect you will really enjoy what we have planned for next release. Our new reverberator aims to do proper steering and should vastly improve the scenario from the last video you've posted.

For an idea of what's coming you can check out this video, specifically the parts pertaining to reflections. This video does not demonstrate our new reverb algorithm (it is four years old, after all) but does give a good sense of some of the effects we're working on, namely the anisotropic reverb. https://www.youtube.com/watch?v=6f8kOI3iD8E

**Comment by nikunjragh** [comment]
Hi @constantinpopp - I'll add that the new reverb should also improve the width in the middle of a room to be closer to isotropic like you see with Valhalla. I am quite surprised our old reverb above came out as so narrow; we did the due diligence to decorrelate the two ear signals. Anyhow, the new algorithm is much more carefully designed so it should fix, like Mike said.

**Comment by constantinpopp** [comment]
Many thanks @nikunjragh and @MikeChemi for your kind responses and the video suggestion. The video sounds very cool. I am already very excited for the new algorithm. :)
