### ISSUE TITLE
UE5 Cook to Oculus Quest 2 - Module Not Available on the Platform

### ISSUE THREAD

**Issue by jblanchardFLAD** [microsoft/ProjectAcoustics#115]
Hello, I'm looking to package my Unreal Engine 5 game over to my Oculus Quest 2 and am receiving the following error and several subsequent errors noting similar issues:

UATHelper: Cooking (Android (ASTC)): LogInit: Display: LogCook: Error: Failed to cook /Game/Audio/NewAcousticsSourceDataOverrideSourceSettings for platform Android_ASTC. It imports class /Script/ProjectAcousticsNative.AcousticsSourceDataOverrideSourceSettings, which is in a module that is not available on the platform.

Is Project Acoustics an available plugin for the Quest 2? Are there other VR headsets that are better suited for the plugin?

**Comment by KyleStorck** [comment]
Project Acoustics for Unreal Audio currently only supports Windows. This is both a limitation of Project Acoustics and the Unreal Engine. SourceDataOverride plugins only work on Windows in UE 5.0. A change is coming in 5.1 that will allow SourceDataOverride plugins to run on other platforms. So when UE 5.1 comes out, we can release a version of PA that works on Android. We're hoping sometime this fall.

**Comment by jblanchardFLAD** [comment]
Understood! Thank you for your quick response to my issue. I'll keep an eye out for 5.1, then!
