### ISSUE TITLE
Local bake (Unreal integration): When changing the speed of sound in the .xml file from 330 to 410 and running a local bake, the voxel map gets offset (potentially scaled) from the world geometry.

### ISSUE THREAD

**Issue by GuidedElf123** [microsoft/ProjectAcoustics#118]
I am working on a collaborative project, which attempts to model the acoustic environment of the planet Venus. The speed of sound on the surface of Venus is approximately 410 metres per second. My approach to factor this in is to the game world using Project Acoustics is: Tag geometry and make sure all materials absorption coefficients are correct > Tag the RecastNavMesh as the acoustics navigation > run the probe generator (have tried both fine and coarse) > Prepare local bake > open the .xml file that is generated and change the speed of sound from 330 to 410 > do the bake (RunLocalBake.bat) > import .ACE file into Unreal:

This approach works fine when I don't change the speed of sound, but if I do - see second image:
330:

![330](https://user-images.githubusercontent.com/112936607/191938231-94a3888b-2dc8-419f-b9a0-4abf90b7d1b0.png)

410:

![410](https://user-images.githubusercontent.com/112936607/191938256-0e08e4a7-56c7-419a-821d-98883cc2fa93.png)

 
Are there any other variables I haven't changed that need to be changed when adapting the speed of sound?

Kind Regards

Sam

**Comment by KyleStorck** [comment]
Neat idea! 

I think the speed of sound should be changed before you do the probe layout, not after. But, speed of  sound is not one of the parameters that we allow you to change. And I think there were reasons. I'm sure @nikunjragh would love to explain this :-D
![image](https://user-images.githubusercontent.com/1233941/191969764-65b23dc1-89c3-4f0f-b00c-790daf3d79db.png)

**Comment by nikunjragh** [comment]
+1 on what Kyle said. Speed of sound and max frequency of simulation will together determine the grid cell size for simulation, so that should be changed at the very start of the pipeline.

**Comment by GuidedElf123** [comment]
Thanks Kyle and Nikunj for the info! As speed of sound is not exposed as a simulation parameter and it is a value that needs to be set prior to running the probe layout calculation, is there a way of setting it in the Engine > Plugins > Marketplace > ProjectAcousticsNative > source files? If so, how complex would this procedure be? 

Thanks again for the help guys.

**Comment by KyleStorck** [comment]
If you're up for changing the source files, it should be pretty easy (you'll need to convert the marketplace plugin to a Project/Engine plugin so that you can recompile it). The place where we hardcode it is in AcousticsSharedState.cpp, inside GetTritonSimulationParameters(). You can set it to what you want there.
![image](https://user-images.githubusercontent.com/1233941/192332539-959e62e8-adeb-4602-b24f-1ff871ccf521.png)

**Comment by GuidedElf123** [comment]
Thanks Kyle! I tested this solution and it worked - looking forward to implementing and hearing the results in the Venus project.
