### ISSUE TITLE
UE5 Intergration Dynamic Openings Not Working

### ISSUE THREAD

**Issue by TommyAllen123** [microsoft/ProjectAcoustics#126]
UE5 5.03
Project Acoustics 3.0

Ive created a BP with an automated sliding door to test Dynamic Openings
The sliding door is automated with Sinewave, where the values are then driven to alter the Gain values between -40dB and 0 dB for the wet and dry attenuation settings using the Acoustic Dynamic Opening Node.

The Acoustic Dynamic Opening is set to Static - That covers the entire Doorway of the Geometry of the baked file
This then has a child which is the physical moving door which has its mobility set to moveable

In the Debug my sound sources appear as [no dynamic opening]

I can't seem to find any documentation or how to implment this properly for just UE5 intergation.
Is this possible?

Everything Else works perfectly so far (Custom Submixes, Closest Distances and Forced Tile Loading)
Not sure what I am doing wrong

Any help if greatly appreicated.  Thanks

I have attatched Files of my work flow Below

Thanks
Tommy

![PA_Dynamic_Opening_Problem_Sliding_Door_Mechanic](https://user-images.githubusercontent.com/117173827/201354501-5e76b674-f3cb-4690-a94d-2a58d0a2d3f3.png)
![PA_Dynamic_Opening_Problem_Acoustic_Opening_Veiwport](https://user-images.githubusercontent.com/117173827/201354509-56c5eada-a58a-47fa-a4b9-e14381597807.png)
![PA_Dynamic_Opening_Problem_Attenuation_Setting_Automation](https://user-images.githubusercontent.com/117173827/201354511-c5710634-4080-400a-836f-8b07195aca8f.png)
![PA_Dynamic_Opening_Problem_Debug_In_Play](https://user-images.githubusercontent.com/117173827/201354515-fc058f35-4e19-4848-9835-a89a8ff6bb82.png)
![PA_Dynamic_Opening_Problem_Map_Placement](https://user-images.githubusercontent.com/117173827/201354521-79e7e987-2ac1-4823-809a-18f99ebaf1e1.png)
![PA_Dynamic_Opening_Problem_Physical_Door_Viewport](https://user-images.githubusercontent.com/117173827/201354528-cf5cde8b-9f9f-4cbf-8410-769d2cf9176e.png)

![PA_Dynamic_Opening_Problem_Source_Ride_Settings](https://user-images.githubusercontent.com/117173827/201355772-4775340e-3e5f-43f1-9ab6-aeb3614ae764.png)

**Comment by KyleStorck** [comment]
Thanks for the report. Everything you did looks fine to me. I'll look into it.

**Comment by TommyAllen123** [comment]
Awesome thank you kyle

The only error I could be doing is that I made a seperate BP to put in the Acoustics Space Node

As this is always saved in the marketplace folder in the native UE5 installation program files
And isnt suitable for working with source control (Perforce) but i got everything else to work

But thanks for looking into it :) 
Tommy

**Comment by TommyAllen123** [comment]
I think it was a referencing problem do the referencing the BP

This work around worked by adding a Add Dynamic opening node

Thanks :)

![image](https://user-images.githubusercontent.com/117173827/201387438-1900ae1a-8b36-43d3-9dbd-c72b73d800e6.png)

**Comment by KyleStorck** [comment]
Ok, glad you got it to work
