### ISSUE TITLE
Unreal won't recognize .ACE bake

### ISSUE THREAD

**Issue by dr0p1n** [microsoft/ProjectAcoustics#129]
Opening a new issue, as the ticket I commented was closed, so not sure if you get updates!

So the problem with my local bake is that after drag and drop to the created Acoustics folder, the .ACE does neither get recognized by the drop down menu, nor the content browser. I used the Windows Explorer, not the Content Browser for import.

![image](https://user-images.githubusercontent.com/44287611/202570977-3a8f04b3-fbbc-4ae9-acb6-7e5d2610b74b.png)

**Comment by dr0p1n** [comment]
I dropped all the files from the folder there in the hope to get any response from the content browser (:

**Comment by KyleStorck** [comment]
Is it working for you now?

**Comment by dr0p1n** [comment]
It does, dragging into content browser is the way.

**Comment by mkmarchan** [comment]
Wanted to add some extra detail if someone hits this in the future. There are two steps needed to get this working:
1. Make sure the .ace file is in Content>Acoustics
2. Drag and drop the .ace file into the content browser in UE

Some of this info is detailed here: https://learn.microsoft.com/en-us/gaming/acoustics/unreal-baking-bake#Data-Files
