### ISSUE TITLE
Increase max range

### ISSUE THREAD

**Issue by CaptainCheerios** [microsoft/ProjectAcoustics#131]
I was noticing that there is a hard cut at 50M, 50000 unreal units for Acoustics.  Is there a way to adjust this? I am working with some bends around a corner and it just ends up being 52m away.  I can always adjust things in the level to make everything work, but if there's a way to adjust this to a max/min distance I would be interested in finding out where it is.

Working in UE 5.0.   Looking to test in 5.1 when the new marketplace plugin releases.

**Comment by KyleStorck** [comment]
In the Probes tab, under Advanced Parameters, you can adjust the Simulation Region to achieve this. You will need to redo the Probes calculation and bake after you change this.
![image](https://user-images.githubusercontent.com/1233941/203445170-3dc562e8-028b-4589-91f9-a05588d6c151.png)

**Comment by CaptainCheerios** [comment]
I have tried this but it does not increase the distance to which the sound emitter stops working with acoustics.  After the 5000 unit mark it defaults back to normal Attenuation.
![image](https://user-images.githubusercontent.com/11049683/203459497-09f6e002-1e9c-49a7-829e-abd2c0bcf920.png)
![image](https://user-images.githubusercontent.com/11049683/203459509-22eecd4e-4a31-481a-b72c-901d10dbde42.png)

I've tried dramatically increasing the simulation region to 4x the default amount, but it still stops at 5000 units
![image](https://user-images.githubusercontent.com/11049683/203459724-c0ff0cba-f950-4efc-92b9-a81c414ad79c.png)

I have baked it again after recalculating.

**Comment by CaptainCheerios** [comment]
Update.  I didn't know there was a limit on the debug draw line.  After 5,000 units it stops drawing and its in the plugin source.  

The distance is going further with this change.

**Comment by KyleStorck** [comment]
Ok. Is it working for you now?

**Comment by CaptainCheerios** [comment]
Yes it is!  I can't wait for Epic to get the update approved and test this out and see if it works on the quest.
