### ISSUE TITLE
Support for multi-agent baking

### ISSUE THREAD

**Issue by OzymandiasLlewellyn** [microsoft/ProjectAcoustics#133]
The bake times on larger scenes leaves something to be desired when it comes to iteration.
With the local bake option and docker container setup, I was hoping there would be support for multi-agent baking through the docker services, but it seems that there is no support I can find. 

I was going to try to jerry-rig multi-agent baking using the "Resume" parameter but it didn't seem to change anything when attempting to add "--resume true" parameter, even if the bake was already complete it started from task zero again.

Any suggestions?

**Comment by NoelCross** [comment]
@OzymandiasLlewellyn thanks for your feedback for supporting multi-agent local baking.  Currently, our only solution is to use Azure for multi-agent baking.  With some work, it would be possible to grab the tools in the Docker image for Linux and distribute across multiple Linux machines.  Each probe produces an .enc file via the RunTritonTask command which is then merged during a CollateTritonData task to produce an ACE file with all of the .enc files as input.  It's probably not the answer you were looking for, but technically it is possible to put something together using the tools that we currently ship.

**Comment by OzymandiasLlewellyn** [comment]
Thanks Noel, tehcnically possible is fine with me. If I can iterate the triton tasks and run CollectTritonData manually I'll make something work.
