### ISSUE TITLE
C++ SDK

### ISSUE THREAD

**Issue by PlasmaDev5** [microsoft/ProjectAcoustics#136]
Is there plans for an engine independent SDK that can be used for integration into games not using Unreal or Unity? Iv not been able to find anything about this

**Comment by NoelCross** [comment]
@PlasmaDev5 Currently, we don't have plans to release a game engine independent SDK, although the source code for the Unreal Engine plugin is available for downloading from Microsoft's Download Center and provides most of the details you would need in order to integrate into a bespoke solution.
