### ISSUE TITLE
Questions about occlusion value calculation

### ISSUE THREAD

**Issue by pmtmp123456** [microsoft/ProjectAcoustics#137]
hello
The occlusion value calculated by Acoustics doesn't seem to take into account mesh thickness, physical material, sound transmission, etc. Are these specs correct?
Please correct me if my understanding is wrong.

For example, imagine a square room with a doorway big enough for a person to enter.
In this environment, let's say you are hearing sounds outside the room that are being pronounced inside the room.

If you change the mesh thickness of the room wall between 1mm and 1000mm and change the physical material to steel or cloth, the occlusion values should be about the same.

In this case, meshes with attributes that have a low shielding rate in the real world, such as thin cloth, have a high shielding rate, and the problem is that even very thin meshes have a high shielding rate.

It's a pity that I can't upload the capture data of the development screen due to circumstances

**Comment by NoelCross** [comment]
@pmtmp123456 You are correct in identifying that transmission is currently not supported in Project Acoustics.  It's definitely something that we've received feedback on so hopefully we can come up with a good solution in the future.

**Comment by nikunjragh** [comment]
To add - Part of the difficulty is that mesh thickness is non-trivial to derive for general scenes, given how game geometries are made of triangle meshes with no water-tightness guarantees. So, deriving a good _input_ to the simulation, no matter how accurate the latter is, is by itself a major problem. I know that doesn't help what you're trying to do, but hopefully sheds some light.

**Comment by pmtmp123456** [comment]
Thank you both for your answers.
Acoustic is a great piece of technology and I look forward to future updates.
