### ISSUE TITLE
Local Bake Task Encoding takes for ever after [x] tasks

### ISSUE THREAD

**Issue by laurelhach** [microsoft/ProjectAcoustics#138]
Hi Guys,

I was wondering if you were aware of an issue I have with the local bake speed.
I am encoding the data locally (using the latest version 2022 ) and honestly I didn't pay attention before, but when I reach a certain amount of files encoded, then suddenly the tasks take forever to be completed. For example after reaching 250+ *.enc files on 450, each new *.enc file take about +5mn each (actually it looks like it increasing the time for each new task). 

I am not sure if this is a local problem, or a leak in the way it is calculated. I can't really cancel it (no resume option). 

PS: Actually it was between 270 and 283 (it took 1h to do only these files)

Thanks for your work and support :) 

PS: Using win11, 64 gig ram, i5 12th Gen

**Comment by MikeChemi** [comment]
Each probe takes a different amount of time depending on the geometry being simulated for that probe. For example, if some probes are fully indoors, they will finish baking faster than probes that are fully outdoors.

Doesn't sound like anything is amiss here.
