### ISSUE TITLE
Question about -> Load multiple ACE files simultaneously at runtime

### ISSUE THREAD

**Issue by laurelhach** [microsoft/ProjectAcoustics#139]
Hi :)

Is there any documentation on how to use that new feature?
Is the multi load automatic when you stream sub levels?

I'm using Unity 2021.3.15 with your latest version (November - 2022)

thanks in advance :)

**Comment by MikeChemi** [comment]
Hello! This is currently only available at the SDK level. We have not yet hooked up the functionality to any of the plugins.
