### ISSUE TITLE
Log File -> The referenced script (*) on this Behaviour is missing!

### ISSUE THREAD

**Issue by laurelhach** [microsoft/ProjectAcoustics#140]
Hello :)

So I have this message spamming the unity log file when I run the game (Unity 2021.3.15)
The referenced script (Microsoft.Acoustics.AcousticsGeometry) on this Behaviour is missing!

I understand the message as probably the script you add to bake the scene is not there anymore. So I was wondering how this is happening. I don't remove the script manually, but I know that I have prefabs or mesh items that are not exported in the final game (debug info, visual reference, etc.) I've added a custom script on these assets, so your generation ignore all the static meshes (and don't add your script to them). But I am not sure why this is still happening (lost reference, etc.).

Can you give me some hints and / or ideas on how I can track that issue and fix it ?
The build is in debug mode.

Thanks again!

**Comment by MikeChemi** [comment]
This should be fixed in our latest version.

You can try adding the following to the AcousticsGeometry.cs script

        [PostProcessScene]
        public static void DestroyOnBuild()
        {
            if (BuildPipeline.isBuildingPlayer)
            {
                foreach (var geo in FindObjectsOfType<AcousticsGeometry>())
                {
                    DestroyImmediate(geo);
                }
            }
        }

**Comment by laurelhach** [comment]
Yes it is already there in the latest version. Thanks!
