### ISSUE TITLE
Unable to load example project for UE5.1

### ISSUE THREAD

**Issue by pietjaakko** [microsoft/ProjectAcoustics#141]
When I try to run the Project Acoustics Example Project for Unreal Engine 5.1 (v2022.1 11/30/2022) I receive the following error message: 

"Missing AcousticsGameUE51 Moules
The following modules are missing or built wit a different engine version:
AcousticsGameUE51

Would you like to build them now"

Perhaps needless to say but rebuilding the modules won't work.

**Comment by NoelCross** [comment]
@pietjaakko I just checked on my PC and noticed that same thing.  It appears that I had an outdated .NET runtime installed on my machine so I grabbed a 6.0 version from https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.404-windows-x64-installer and now the project is loading again.  I still needed to rebuild components when launching the project and once that was done, I was able to use the sample project.

```
You must install or update .NET to run this application.

App: C:\Program Files\Epic Games\UE_5.1\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: C:\Program Files\dotnet\

The following frameworks were found:
  3.1.32 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  5.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by pietjaakko** [comment]
@NoelCross Thank you very much for your quick solution. 

I installed the .NET runtime from the link but still receive the same error messages. ("AcousticsGameUE51 could not be compiled. Try rebuilding from source manually.")

You are referring to this "Rebuilding from source manually" with you having to rebuild components?

I apologize for these perhaps elementary level questions, but all of this is way above my skill level.

**Comment by NoelCross** [comment]
@pietjaakko in order to better understand what is going on, please send a copy of the latest log file in the Saved\Logs folder of your project.  This should give us more information about what is going wrong during the compilation process.  Thanks!

**Comment by pietjaakko** [comment]
@NoelCross Sure, here you are. Thank you!

> Log file open, 12/28/22 16:13:43
LogConfig: Display: Loading VulkanPC ini files took 0.02 seconds
LogConfig: Display: Loading IOS ini files took 0.02 seconds
LogConfig: Display: Loading HoloLens ini files took 0.02 seconds
LogConfig: Display: Loading Mac ini files took 0.02 seconds
LogConfig: Display: Loading Android ini files took 0.03 seconds
LogConfig: Display: Loading Windows ini files took 0.03 seconds
LogConfig: Display: Loading Unix ini files took 0.03 seconds
LogConfig: Display: Loading TVOS ini files took 0.03 seconds
LogConfig: Display: Loading LinuxArm64 ini files took 0.03 seconds
LogConfig: Display: Loading Linux ini files took 0.03 seconds
LogPluginManager: Mounting Engine plugin Bridge
LogPluginManager: Mounting Engine plugin FastBuildController
LogPluginManager: Mounting Engine plugin EnhancedInput
LogPluginManager: Mounting Engine plugin MeshPainting
LogPluginManager: Mounting Engine plugin XGEController
LogPluginManager: Mounting Engine plugin TraceUtilities
LogPluginManager: Mounting Engine plugin Paper2D
LogPluginManager: Mounting Engine plugin ChaosNiagara
LogPluginManager: Mounting Engine plugin ChaosEditor
LogPluginManager: Mounting Engine plugin AutomationUtils
LogPluginManager: Mounting Engine plugin ChaosCaching
LogPluginManager: Mounting Engine plugin ChaosCloth
LogPluginManager: Mounting Engine plugin BackChannel
LogPluginManager: Mounting Engine plugin ChaosClothEditor
LogPluginManager: Mounting Engine plugin CharacterAI
LogPluginManager: Mounting Engine plugin ChaosSolverPlugin
LogPluginManager: Mounting Engine plugin Dataflow
LogPluginManager: Mounting Engine plugin GeometryFlow
LogPluginManager: Mounting Engine plugin MeshModelingToolsetExp
LogPluginManager: Mounting Engine plugin Iris
LogPluginManager: Mounting Engine plugin FullBodyIK
LogPluginManager: Mounting Engine plugin GeometryCollectionPlugin
LogPluginManager: Mounting Engine plugin PlanarCut
LogPluginManager: Mounting Engine plugin MeshLODToolset
LogPluginManager: Mounting Engine plugin ChaosUserDataPT
LogPluginManager: Mounting Engine plugin PlatformCrypto
LogPluginManager: Mounting Engine plugin PythonScriptPlugin
LogPluginManager: Mounting Engine plugin OpenImageDenoise
LogPluginManager: Mounting Engine plugin UVEditor
LogPluginManager: Mounting Engine plugin ProxyLODPlugin
LogPluginManager: Mounting Engine plugin EnvironmentQueryEditor
LogPluginManager: Mounting Engine plugin AISupport
LogPluginManager: Mounting Engine plugin SkeletalReduction
LogPluginManager: Mounting Engine plugin AnimationModifierLibrary
LogPluginManager: Mounting Engine plugin BlendSpaceMotionAnalysis
LogPluginManager: Mounting Engine plugin AndroidMedia
LogPluginManager: Mounting Engine plugin ControlRigSpline
LogPluginManager: Mounting Engine plugin IKRig
LogPluginManager: Mounting Engine plugin ImgMedia
LogPluginManager: Mounting Engine plugin MediaPlate
LogPluginManager: Mounting Engine plugin AvfMedia
LogPluginManager: Mounting Engine plugin WmfMedia
LogPluginManager: Mounting Engine plugin ControlRig
LogPluginManager: Mounting Engine plugin Niagara
LogPluginManager: Mounting Engine plugin Interchange
LogPluginManager: Found config from plugin[Interchange] Game
LogPluginManager: Mounting Engine plugin MediaCompositing
LogPluginManager: Mounting Engine plugin AndroidFileServer
LogPluginManager: Mounting Engine plugin InterchangeEditor
LogPluginManager: Mounting Engine plugin ActorLayerUtilities
LogPluginManager: Mounting Engine plugin MediaPlayerEditor
LogPluginManager: Mounting Engine plugin Takes
LogPluginManager: Mounting Engine plugin AppleMoviePlayer
LogPluginManager: Mounting Engine plugin AssetTags
LogPluginManager: Mounting Engine plugin AndroidDeviceProfileSelector
LogPluginManager: Mounting Engine plugin AudioCapture
LogPluginManager: Mounting Engine plugin AndroidPermission
LogPluginManager: Mounting Engine plugin WebMMedia
LogPluginManager: Mounting Engine plugin AppleImageUtils
LogPluginManager: Mounting Engine plugin CustomMeshComponent
LogPluginManager: Mounting Engine plugin ArchVisCharacter
LogPluginManager: Mounting Engine plugin AndroidMoviePlayer
LogPluginManager: Mounting Engine plugin ChunkDownloader
LogPluginManager: Mounting Engine plugin AudioWidgets
LogPluginManager: Mounting Engine plugin ExampleDeviceProfileSelector
LogPluginManager: Mounting Engine plugin GeometryProcessing
LogPluginManager: Mounting Engine plugin LinuxDeviceProfileSelector
LogPluginManager: Mounting Engine plugin IOSDeviceProfileSelector
LogPluginManager: Mounting Engine plugin InputDebugging
LogPluginManager: Mounting Engine plugin GooglePAD
LogPluginManager: Mounting Engine plugin LocationServicesBPLibrary
LogPluginManager: Mounting Engine plugin GoogleCloudMessaging
LogPluginManager: Mounting Engine plugin MeshModelingToolset
LogPluginManager: Mounting Engine plugin Metasound
LogPluginManager: Mounting Engine plugin CableComponent
LogPluginManager: Mounting Engine plugin HoudiniEngine
LogPluginManager: Mounting Engine plugin GeometryCache
LogPluginManager: Mounting Engine plugin MobilePatchingUtils
LogPluginManager: Mounting Engine plugin AudioSynesthesia
LogPluginManager: Mounting Engine plugin Synthesis
LogPluginManager: Mounting Engine plugin WindowsDeviceProfileSelector
LogPluginManager: Mounting Engine plugin WebMMoviePlayer
LogPluginManager: Mounting Engine plugin ProceduralMeshComponent
LogPluginManager: Mounting Engine plugin PropertyAccessEditor
LogPluginManager: Mounting Engine plugin WaveTable
LogPluginManager: Mounting Engine plugin SignificanceManager
LogPluginManager: Mounting Engine plugin SoundFields
LogPluginManager: Mounting Engine plugin WindowsMoviePlayer
LogPluginManager: Mounting Engine plugin CameraShakePreviewer
LogPluginManager: Mounting Engine plugin BlueprintHeaderView
LogPluginManager: Mounting Engine plugin CryptoKeys
LogPluginManager: Mounting Engine plugin CurveEditorTools
LogPluginManager: Mounting Engine plugin FacialAnimation
LogPluginManager: Mounting Engine plugin GLTFImporter
LogPluginManager: Mounting Engine plugin GeometryMode
LogPluginManager: Mounting Engine plugin EditorDebugTools
LogPluginManager: Mounting Engine plugin EditorScriptingUtilities
LogPluginManager: Mounting Engine plugin DataValidation
LogPluginManager: Mounting Engine plugin ProjectAcoustics
LogPluginManager: Mounting Engine plugin GameplayCameras
LogPluginManager: Mounting Engine plugin ModelingToolsEditorMode
LogPluginManager: Mounting Engine plugin AssetManagerEditor
LogPluginManager: Mounting Engine plugin MaterialAnalyzer
LogPluginManager: Mounting Engine plugin UdpMessaging
LogPluginManager: Mounting Engine plugin SequencerAnimTools
LogPluginManager: Mounting Engine plugin MacGraphicsSwitching
LogPluginManager: Mounting Engine plugin MobileLauncherProfileWizard
LogPluginManager: Mounting Engine plugin WorldPartitionHLODUtilities
LogPluginManager: Mounting Engine plugin GameplayTagsEditor
LogPluginManager: Mounting Engine plugin SpeedTreeImporter
LogPluginManager: Mounting Engine plugin PluginBrowser
LogPluginManager: Mounting Engine plugin StylusInput
LogPluginManager: Mounting Engine plugin OnlineServices
LogPluginManager: Mounting Engine plugin OnlineBase
LogPluginManager: Mounting Engine plugin TcpMessaging
LogPluginManager: Mounting Engine plugin LauncherChunkInstaller
LogPluginManager: Mounting Engine plugin OnlineSubsystem
LogPluginManager: Mounting Engine plugin AlembicImporter
LogPluginManager: Mounting Engine plugin OodleNetwork
LogPluginManager: Mounting Engine plugin OnlineSubsystemUtils
LogPluginManager: Mounting Engine plugin GLTFExporter
LogPluginManager: Mounting Engine plugin VariantManager
LogPluginManager: Mounting Engine plugin DatasmithContent
LogPluginManager: Mounting Engine plugin OnlineSubsystemNull
LogPluginManager: Mounting Engine plugin KDevelopSourceCodeAccess
LogPluginManager: Mounting Engine plugin CLionSourceCodeAccess
LogPluginManager: Mounting Engine plugin CodeLiteSourceCodeAccess
LogPluginManager: Mounting Engine plugin PixWinPlugin
LogPluginManager: Mounting Engine plugin PlasticSourceControl
LogPluginManager: Mounting Engine plugin NullSourceCodeAccess
LogPluginManager: Mounting Engine plugin GitSourceControl
LogPluginManager: Mounting Engine plugin TraceDataFilters
LogPluginManager: Mounting Engine plugin DumpGPUServices
LogPluginManager: Mounting Engine plugin RiderSourceCodeAccess
LogPluginManager: Mounting Engine plugin PropertyAccessNode
LogPluginManager: Mounting Engine plugin TextureFormatOodle
LogPluginManager: Mounting Engine plugin VisualStudioSourceCodeAccess
LogPluginManager: Mounting Engine plugin PerforceSourceControl
LogPluginManager: Mounting Engine plugin UObjectPlugin
LogPluginManager: Mounting Engine plugin VariantManagerContent
LogPluginManager: Mounting Engine plugin SubversionSourceControl
LogPluginManager: Mounting Engine plugin PluginUtils
LogPluginManager: Mounting Engine plugin VisualStudioCodeSourceCodeAccess
LogPluginManager: Mounting Engine plugin AnimationSharing
LogPluginManager: Mounting Engine plugin XCodeSourceCodeAccess
LogPluginManager: Mounting Engine plugin InterchangeTests
LogPluginManager: Mounting Engine plugin ActorSequence
LogPluginManager: Mounting Engine plugin LevelSequenceEditor
LogPluginManager: Mounting Engine plugin TemplateSequence
LogPluginManager: Mounting Engine plugin SequencerScripting
LogPluginManager: Mounting Engine plugin OnlineSubsystemGooglePlay
LogPluginManager: Mounting Engine plugin LightMixer
LogPluginManager: Mounting Engine plugin ContentBrowserClassDataSource
LogPluginManager: Mounting Engine plugin ObjectMixer
LogPluginManager: Mounting Engine plugin ContentBrowserAssetDataSource
LogPluginManager: Mounting Engine plugin ContentBrowserFileDataSource
LogPluginManager: Mounting Engine plugin OnlineSubsystemIOS
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Bridge/Content/' mounted to '/Bridge/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/2D/Paper2D/Content/' mounted to '/Paper2D/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/ChaosNiagara/Content/' mounted to '/ChaosNiagara/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/ChaosCaching/Content/' mounted to '/ChaosCaching/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/ChaosClothEditor/Content/' mounted to '/ChaosClothEditor/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/ChaosSolverPlugin/Content/' mounted to '/ChaosSolverPlugin/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/Dataflow/Content/' mounted to '/Dataflow/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/GeometryFlow/Content/' mounted to '/GeometryFlow/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/MeshModelingToolsetExp/Content/' mounted to '/MeshModelingToolsetExp/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/FullBodyIK/Content/' mounted to '/FullBodyIK/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/GeometryCollectionPlugin/Content/' mounted to '/GeometryCollectionPlugin/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/MeshLODToolset/Content/' mounted to '/MeshLODToolset/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/PythonScriptPlugin/Content/' mounted to '/PythonScriptPlugin/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/UVEditor/Content/' mounted to '/UVEditor/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Animation/ControlRigSpline/Content/' mounted to '/ControlRigSpline/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Animation/IKRig/Content/' mounted to '/IKRig/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Media/MediaPlate/Content/' mounted to '/MediaPlate/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Animation/ControlRig/Content/' mounted to '/ControlRig/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/FX/Niagara/Content/' mounted to '/Niagara/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Interchange/Runtime/Content/' mounted to '/Interchange/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Media/MediaCompositing/Content/' mounted to '/MediaCompositing/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/VirtualProduction/Takes/Content/' mounted to '/Takes/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Runtime/AudioWidgets/Content/' mounted to '/AudioWidgets/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Runtime/GeometryProcessing/Content/' mounted to '/GeometryProcessing/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Runtime/MeshModelingToolset/Content/' mounted to '/MeshModelingToolset/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Runtime/Metasound/Content/' mounted to '/Metasound/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Runtime/HoudiniEngine/Content/' mounted to '/HoudiniEngine/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Runtime/AudioSynesthesia/Content/' mounted to '/AudioSynesthesia/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Runtime/Synthesis/Content/' mounted to '/Synthesis/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Runtime/WaveTable/Content/' mounted to '/WaveTable/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Editor/BlueprintHeaderView/Content/' mounted to '/BlueprintHeaderView/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Editor/GLTFImporter/Content/' mounted to '/GLTFImporter/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Editor/GeometryMode/Content/' mounted to '/GeometryMode/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Marketplace/ProjectAcousticsNative/Content/' mounted to '/ProjectAcoustics/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Editor/ModelingToolsEditorMode/Content/' mounted to '/ModelingToolsEditorMode/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Editor/SpeedTreeImporter/Content/' mounted to '/SpeedTreeImporter/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Enterprise/GLTFExporter/Content/' mounted to '/GLTFExporter/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Enterprise/DatasmithContent/Content/' mounted to '/DatasmithContent/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Developer/AnimationSharing/Content/' mounted to '/AnimationSharing/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/MovieScene/SequencerScripting/Content/' mounted to '/SequencerScripting/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Editor/ObjectMixer/LightMixer/Content/' mounted to '/LightMixer/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Editor/ObjectMixer/ObjectMixer/Content/' mounted to '/ObjectMixer/'
SourceControl: Source control is disabled
SourceControl: Source control is disabled
LogInit: Warning: Incompatible or missing module: AcousticsGameUE51
Running C:/Program Files/Epic Games/UE_5.1/Engine/Build/BatchFiles/Build.bat Development Win64 -Project="C:/Users/jaakk/Desktop/AcousticsGameUE51/AcousticsGameUE51.uproject" -TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE
Running UnrealBuildTool: dotnet "..\..\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" Development Win64 -Project="C:/Users/jaakk/Desktop/AcousticsGameUE51/AcousticsGameUE51.uproject" -TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE
Log file: C:\Users\jaakk\AppData\Local\UnrealBuildTool\Log.txt
Error while enumerating Visual Studio toolchains
LogInit: Warning: Still incompatible or missing module: AcousticsGameUE51
LogCore: Engine exit requested (reason: EngineExit() was called)
LogExit: Preparing to exit.
LogVirtualization: UE::Virtualization was shutdown
LogModuleManager: Shutting down and abandoning module DesktopPlatform (58)
LogModuleManager: Shutting down and abandoning module PerforceSourceControl (56)
LogModuleManager: Shutting down and abandoning module SourceControl (55)
LogModuleManager: Shutting down and abandoning module PythonScriptPluginPreload (52)
LogModuleManager: Shutting down and abandoning module PlatformCryptoOpenSSL (50)
LogModuleManager: Shutting down and abandoning module PlatformCryptoTypes (48)
LogModuleManager: Shutting down and abandoning module PlatformCrypto (46)
LogModuleManager: Shutting down and abandoning module XGEController (44)
LogXGEController: Cannot use XGE Controller as Incredibuild is not installed on this machine.
LogXGEController: Cleaning working directory: C:/Users/jaakk/AppData/Local/Temp/UnrealXGEWorkingDir/
LogModuleManager: Shutting down and abandoning module FastBuildController (42)
LogModuleManager: Shutting down and abandoning module AnimationModifiers (40)
LogModuleManager: Shutting down and abandoning module AudioEditor (38)
LogModuleManager: Shutting down and abandoning module PropertyEditor (37)
LogModuleManager: Shutting down and abandoning module Virtualization (34)
LogModuleManager: Shutting down and abandoning module MessageLog (33)
LogModuleManager: Shutting down and abandoning module TextureCompressor (30)
LogModuleManager: Shutting down and abandoning module RenderCore (28)
LogModuleManager: Shutting down and abandoning module Landscape (26)
LogModuleManager: Shutting down and abandoning module SlateRHIRenderer (24)
LogModuleManager: Shutting down and abandoning module AnimGraphRuntime (22)
LogModuleManager: Shutting down and abandoning module Renderer (20)
LogModuleManager: Shutting down and abandoning module Engine (18)
LogModuleManager: Shutting down and abandoning module CoreUObject (16)
LogModuleManager: Shutting down and abandoning module SandboxFile (14)
LogModuleManager: Shutting down and abandoning module PakFile (12)
LogModuleManager: Shutting down and abandoning module RSA (11)
LogModuleManager: Shutting down and abandoning module NetworkFile (8)
LogModuleManager: Shutting down and abandoning module StreamingFile (6)
LogModuleManager: Shutting down and abandoning module CookOnTheFly (4)
LogModuleManager: Shutting down and abandoning module StorageServerClient (2)
LogExit: Exiting.
Log file closed, 12/28/22 16:14:37

**Comment by NoelCross** [comment]
@pietjaakko it appears that Unreal Engine is not able to find a valid version of Visual Studio installed on your machine.  You'll need to have at least VS2019 or preferably VS2022 installed in order to build the project.

```
Running C:/Program Files/Epic Games/UE_5.1/Engine/Build/BatchFiles/Build.bat Development Win64 -Project="C:/Users/jaakk/Desktop/AcousticsGameUE51/AcousticsGameUE51.uproject" -TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE
Running UnrealBuildTool: dotnet "....\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" Development Win64 -Project="C:/Users/jaakk/Desktop/AcousticsGameUE51/AcousticsGameUE51.uproject" -TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE
Log file: C:\Users\jaakk\AppData\Local\UnrealBuildTool\Log.txt
Error while enumerating Visual Studio toolchains
LogInit: Warning: Still incompatible or missing module: AcousticsGameUE51
LogCore: Engine exit requested (reason: EngineExit() was called)
LogExit: Preparing to exit.
```


I'm not sure if you shared text from C:\Users\jaakk\AppData\Local\UnrealBuildTool\Log.txt, but this file also may contain clues about what's blocking the project from building.

**Comment by pietjaakko** [comment]
@NoelCross I updated Visual Studio to VS2022 (with the Workloads selected according to the UE5.1 Documentation). Now I can see that the log file does not state the Error regarding VS toolchains, yet wile still not opening. 

I included below the following logs: 
- **Project saved/logs/AcousticsGameUE51.log**
- **C:\Users\jaakk\AppData\Local\UnrealBuildTool\Log.txt**

[AcousticsGameUE51.log](https://github.com/microsoft/ProjectAcoustics/files/10324751/AcousticsGameUE51.log)
[Log.txt](https://github.com/microsoft/ProjectAcoustics/files/10324750/Log.txt)

**Comment by NoelCross** [comment]
@pietjaakko Now it appears that you are having a problem with building the HoudiniEngine plugin.  Perhaps you need to disable this plugin or upgrade to a new version of the plugin in the Epic Games Launcher to get past this problem.

```
Enabling plugin 'HoudiniEngine' (referenced via default plugins)
Expecting to find a type to be declared in a module rules named 'HoudiniEngine' in UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.
BuildException: Expecting to find a type to be declared in a module rules named 'HoudiniEngine' in UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in C:\Program Files\Epic Games\UE_5.1\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 462
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in C:\Program Files\Epic Games\UE_5.1\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 394
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in C:\Program Files\Epic Games\UE_5.1\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 394
   at UnrealBuildTool.RulesAssembly.CreateModuleRules(String ModuleName, ReadOnlyTargetRules Target, String ReferenceChain, ILogger Logger) in C:\Program Files\Epic Games\UE_5.1\Engine\Source\Programs\UnrealBuildTool\System\RulesAssembly.cs:line 394
   at UnrealBuildTool.UEBuildTarget.CreateModuleRulesAndSetDefaults(String ModuleName, String ReferenceChain, ILogger Logger) in C:\Program Files\Epic Games\UE_5.1\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 4333
   at UnrealBuildTool.UEBuildTarget.FindOrCreateModuleByName(String ModuleName, String ReferenceChain, ILogger Logger) in C:\Program Files\Epic Games\UE_5.1\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 4457
   at UnrealBuildTool.UEBuildTarget.FindOrCreateCppModuleByName(String ModuleName, String ReferenceChain, ILogger Logger) in C:\Program Files\Epic Games\UE_5.1\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 4580
   at UnrealBuildTool.UEBuildTarget.AddPlugin(PluginReferenceDescriptor Reference, String ReferenceChain, String[] ExcludeFolders, Dictionary`2 NameToInstance, Dictionary`2 NameToInfos, ILogger Logger) in C:\Program Files\Epic Games\UE_5.1\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3670
   at UnrealBuildTool.UEBuildTarget.SetupPlugins(ILogger Logger) in C:\Program Files\Epic Games\UE_5.1\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3490
   at UnrealBuildTool.UEBuildTarget.PreBuildSetup(ILogger Logger) in C:\Program Files\Epic Games\UE_5.1\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 2677
   at UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, Boolean bSkipRulesCompile, Boolean bForceRulesCompile, Boolean bUsePrecompiled, ILogger Logger) in C:\Program Files\Epic Games\UE_5.1\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 857
   at UnrealBuildTool.BuildMode.CreateMakefile(BuildConfiguration BuildConfiguration, TargetDescriptor TargetDescriptor, ISourceFileWorkingSet WorkingSet, ILogger Logger) in C:\Program Files\Epic Games\UE_5.1\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 741
   at UnrealBuildTool.BuildMode.Build(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in C:\Program Files\Epic Games\UE_5.1\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 275
   at UnrealBuildTool.BuildMode.Execute(CommandLineArguments Arguments, ILogger Logger) in C:\Program Files\Epic Games\UE_5.1\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 242
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in C:\Program Files\Epic Games\UE_5.1\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 648

```

**Comment by pietjaakko** [comment]
@NoelCross Thanks a lot for looking into this with such care! Updating to latest HoudiniEngine plugin didn't help but disabling it temporarily did the trick. After launching and saving it I was able to reactivate HoudiniEngine and even launch a HE session without issues.

**Comment by victo577** [comment]
I need help when i try to create a ue5 template using c++ I get this : An error occurred while trying to generate project files.

Running C:/Program Files/Epic Games/UE_5.1/Engine/Build/BatchFiles/Build.bat  -projectfiles -project="C:/Users/yee/Documents/Unreal Projects/MyProject2/MyProject2.uproject" -game -rocket -progress
Running UnrealBuildTool: dotnet "..\..\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" -projectfiles -project="C:/Users/yee/Documents/Unreal Projects/MyProject2/MyProject2.uproject" -game -rocket -progress
'dotnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by NoelCross** [comment]
@victo577 it appears that you are missing the dotnet runtime which is a requirement for building UE5 projects using C++.  Try installing the latest .NET runtime from https://dotnet.microsoft.com/en-us/download/dotnet and see if your able to get further.
