### ISSUE TITLE
Is PA only now available for 5.1 now. Or am I Missing Somthing? 

### ISSUE THREAD

**Issue by TommyAllen123** [microsoft/ProjectAcoustics#145]
So on my laptop everything works fine

I had fresh install of UE5.03 on to a new PC
Installed visual studio 2019 with everything needed, and got a fresh install of PA from the market place for UE5.03.

However for some reason the UE5 project with project acoustics it now doesnt work, saying the Ace file isnt loading.
![image](https://user-images.githubusercontent.com/117173827/211834196-f3a44f33-5e28-4463-8de6-db03a56b4c4d.png)

I have double checked and it works on my laptop fine. (installed and completed summer 2022)

the set up is also the same
<img width="606" alt="image" src="https://user-images.githubusercontent.com/117173827/211834823-2b16ef5a-55ce-4ec5-aaa4-407c717ec15b.png">

Again it works fine with Laptop,  On the PC i deleted and re-imported the ace file with a different name to stop any referencing issues, and still nothing loads.

Im was unable to find the 'project acoustics sample project' for 5.03, so i moved it over from my previous laptop, and I am having the same issue.

Is PA only now available for 5.1 now, and i need migrate everything? Or am I Missing Somthing? 

Thanks Tommy

**Comment by KyleStorck** [comment]
When you installed the latest version from the marketplace, you installed a new version of Project Acoustics (we call it 2022.1). This version of PA works with both UE 5.0 and UE 5.1, but will not work with older ACE files. I suspect you are trying to use an ACE file you generated with the previous version of PA, and that is not supported. Look in the Output Log to see if you see an error message about your ACE file. To fix this, you will need to regenerate your ACE files with the latest version of PA.

**Comment by TommyAllen123** [comment]
Thank you kyle for the quick reply, this makes total sense now thank you x
