### ISSUE TITLE
Problem with AAmbientSound virtual speakers when changing levels (UE5.1)

### ISSUE THREAD

**Issue by imgamesgustav** [microsoft/ProjectAcoustics#147]
We have a crash in FAcousticsAudioPluginListener::OnListenerUpdated when we change levels and all actors are destroyed, the plugin still runs this function making m_VirtualSpeakers crash as the AActors in there are destroyed.

We are using the "Server travel" (seamless travel) node, it will unload the level with all actors including those created by the plugin. How should we go about fixing this problem?

**Comment by KyleStorck** [comment]
Thanks for the bug report. Confirmed the behavior on my end. Our AudioPluginListener does need to be fixed to be able to handle level changes. We'll report back when we have released the fix to the marketplace.

In the meantime, I don't think there's a non-code workaround. Below is my cursory change that fixed the issue for me. If you wanted to recompile the plugin as a project plugin, you could apply these fixes yourself.

Add the following function to AcousticsAudioPluginListener.cpp
```
void FAcousticsAudioPluginListener::OnWorldChanged(FAudioDevice* AudioDevice, UWorld* ListenerWorld)
{
    m_IsInitialized = false;
    m_NumVirtualSpeakers = 0;
    m_VirtualSpeakers.Empty();
    m_VirtualSpeakerPositions.Empty();

    OnListenerInitialize(AudioDevice, ListenerWorld);
}
```

Add the following function declaration to AcousticsAudioPluginListener.h
`    virtual void OnWorldChanged(FAudioDevice* AudioDevice, UWorld* ListenerWorld) override;
`

![image](https://user-images.githubusercontent.com/1233941/212112039-5dd12c5e-5cdc-4d00-886c-a09764857559.png)

**Comment by imgamesgustav** [comment]
Many thanks for the quick response, it seems to work perfectly :)

**Comment by KyleStorck** [comment]
A fix for the level change crash has been pushed to the marketplace. It can be found in version 4 (2022.1.410) of the Project Acoustics plugin.
