### ISSUE TITLE
Updated bake data lost if file is write protected

### ISSUE THREAD

**Issue by borogove** [microsoft/ProjectAcoustics#15]
Unreal 4.23, Perforce Helix

We are using Perforce for source control, which, unlike git, write-protects files locally until they're explicitly checked out for editing. 

I re-baked acoustics data for a level that already had an .ace file in source control, and it appears that the results of the bake were silently lost when it completed because it couldn't write the local file.

I checked the Azure storage account and couldn't find anything there. 

The desired behavior here would be to integrate with the source control system -- Unreal is already Perforce-aware and offers an option to check out or overwrite files locally when it tries to save an asset and finds it write-protected. 

It would also be okay to ask the user for overwrite permission, or ask the user to save to another filename, or go into a retry/fail loop.

**Comment by MikeChemi** [comment]
Yikes! Sorry to hear you lost your acoustics data. Perforce integration is not something we had considered with this release. Are you able to modify the plugin code to check out the file on your behalf?

**Comment by borogove** [comment]
> Are you able to modify the plugin code to check out the file on your behalf?

I don't have enough room in my schedule to. I might be able to do a dumb "increment a number in a filename if the first write fails" hack.

**Comment by kegodin** [comment]
Thanks for filing this bug. It's tracked internally as VSO # 24777005. It's resolved as fixed and expected to go out with the next public release.

**Comment by MikeChemi** [comment]
Fix is included in version 2.0 #55
