### ISSUE TITLE
UE5.1 Error when sending bake to Azure

### ISSUE THREAD

**Issue by FireCode117** [microsoft/ProjectAcoustics#154]
Hello. In the process of putting Acoustics into Lyra and after setting up everything with Azure the “Submit Azure Bake” button becomes clickable and when I hit I get this error:

LogPython: Error: Value cannot be null.
Parameter name: Need a valid VOX file
LogPython: Error: Triton.BakeService

**Comment by NoelCross** [comment]
@FireCode117 Please check that you have generated a VOX file by using the Probes tab to calculate the probe locations and voxelize the scene.  This Probe calculation step needs to complete successfully before submitting to Azure for a bake operation.

**Comment by FireCode117** [comment]
> @FireCode117 Please check that you have generated a VOX file by using the Probes tab to calculate the probe locations and voxelize the scene. This Probe calculation step needs to complete successfully before submitting to Azure for a bake operation.

Thank you this helped, however after submitting the bake I get an error on the azure portal saying that the job failed due to a quota limit with the pools and that I should request a qutoa increase. I have no idea on how to successfully go about the request process and none of the videos on project acoustics goes into much detail about it

**Comment by NoelCross** [comment]
@FireCode117 Please consult the documentation on the Project Acoustics doc site: [upgrading-your-quota](https://learn.microsoft.com/en-us/gaming/acoustics/create-azure-account#upgrading-your-quota)

This documentation link redirects you to the Azure site for managing your quota.
