### ISSUE TITLE
Unreal 5.1 Crashes between level loads

### ISSUE THREAD

**Issue by JoshCaudill** [microsoft/ProjectAcoustics#161]
Hello!

I'm currently working on a project using Project Acoustics in Unreal 5.1.1, and whenever anybody on the team tries to transitions between our levels during runtime, the engine crashes with the following log:

> LoginId:978cf0c1427cf75c9fbde1b791d8ef90
> EpicAccountId:ad2958ef8ceb4dc3a17c6a5a05ce3243
> 
> Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000247842
> 
> UnrealEditor_Engine
> UnrealEditor_ProjectAcousticsNative!FAcousticsAudioPluginListener::OnListenerUpdated() [E:\Repos\ThesisProject\TPP\Plugins\ProjectAcousticsNative\ProjectAcousticsNative\Source\ProjectAcousticsNative\Private\AcousticsAudioPluginListener.cpp:119]
> UnrealEditor_Engine
> UnrealEditor_Engine
> UnrealEditor_Engine
> UnrealEditor_Engine
> UnrealEditor_Engine
> UnrealEditor_Engine
> UnrealEditor_UnrealEd
> UnrealEditor_UnrealEd
> UnrealEditor
> UnrealEditor
> UnrealEditor
> UnrealEditor
> UnrealEditor
> UnrealEditor
> kernel32
> ntdll

Some of our machines mention the "SetActorLocation" function on crashes, while others do not, but the log always mentions Project Acoustics, and it always lists the \AcousticsAudioPluginListener.cpp:119.

Any help would be fantastic, and I'm more than willing to give any more information that would help.

**Comment by KyleStorck** [comment]
This is the same issue as this one https://github.com/microsoft/ProjectAcoustics/issues/147. I provided a code fix. No ETA on when we'll update the marketplace plugin with the fix. Also see this issue for how to apply the code fix https://github.com/microsoft/ProjectAcoustics/issues/152.

**Comment by haisting** [comment]
Hey Kyle, did the fix and it stopped the crashing but now we're having issues with doing bakes. When I'm on the Probes tab to prep the bake, once I hit calculate we get his crash. I removed project acoustics from the Plugins\Marketplace folder and rebuilt our project in visual studio. Any advice?



**Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff

Triton_Preprocessor
vcomp140
vcomp140
vcomp140
vcomp140
kernel32
ntdll**





Additionally, I see there is a "Package" button in the plugins now when looking at Project Acoustics for Unreal Audio. Does this need to point to the AcousticData folder where the Triton processor is or the ProjectAcousticsNative folder?
![image](https://user-images.githubusercontent.com/75640805/219546421-d3c9f848-e0e1-4d9a-9664-8e85f07992b6.png)

**Comment by KyleStorck** [comment]
Not sure about the packaging, but that does remind me. You should double check your Acoustics Data Folder points to the right spot. When you migrated your plugin, you might be using the old Acoustics Data Folder path which points to a directory that no longer exists. 
![image](https://user-images.githubusercontent.com/1233941/219686393-7591e5a1-4cda-42da-9d21-9fd1417457dd.png)

**Comment by haisting** [comment]
Hey Kyle! 

It looks like it's pointing in the right location. It's looking for the Triton.LocalProcessor.exe right?

In my project's directory, I have it: [project]/Plugins/ProjectAcoustics/AcousticData

**Comment by haisting** [comment]
Also, when rebuilding should I be doing a full rebuild of Engine + Project in visual studio or just the project?

**Comment by KyleStorck** [comment]
Do you see your prebake files there (<prefix>_config.xml and <prefix>.VOX) in that folder? You may need to redo your prebake (Probes calculation) after you migrated your plugin.

**Comment by haisting** [comment]
I see them! They are mainly test levels and we were about to start to bake all our levels, so I could delete these as they aren't as important (if needed). 

That's also where I'm getting the crash. Whenever I go to the probe calculation tab and kick off a calculation I get the error above.

**Comment by haisting** [comment]
Additionally, I tried removing everything and installing the downloadable version of the plugin. I kept getting the python error saying it had python dependencies in the probes tab. I attempted the fixes in CMD and ensured that I had all the correct packages from VS Installer and couldn't get that to work either. I'm a bit stump currently.

**Comment by haisting** [comment]
Just as a recap, I was having crashes with level loading so I referenced #147 and #152 to fix that issue and it did fix the crashing.

Now, I'm having issues trying to generate new bakes.

I go here:
![image](https://user-images.githubusercontent.com/75640805/219813108-8577526a-2c05-4758-8dbf-962490c992ec.png)

and then when I hit calculate this is what I get:
![image](https://user-images.githubusercontent.com/75640805/219813165-070396de-2a9a-43a2-a969-4978175fd689.png)


I tried the method of moving everything over to plugins/ProjectAcousticsNative in my project directory, then uninstalling the version in the Plugins/Marketplace/ProjectAcousticsNative in the Engine directory and rebuilding and that still produced the crash. 

I reverted back, and then tried compiling and modifying the plugin from the engine directory and that gave the same results.

Whenever I have the Marketplace plugin installed directly with no modifications, it works fine but my level loading breaks. When I add the code to the .cpp and .h files, that fixes the level loading crashes but now gives me this error, not allowing me to prep acoustics.

**Comment by KyleStorck** [comment]
Are you able to debug the project through Visual Studio? That would give us more information about the error.

Otherwise, we don't have an official fix out for the level change bug. The code I shared is an unofficial workaround and that makes it harder to debug.

**Comment by haisting** [comment]
I'm not sure, I don't spend a tremendous amount of time working in visual studio. I'd love to connect with you and show you what is going on. Project Acoustics is currently a primary factor in my thesis and would love to find a fix for this asap. If there is going to be a released patch, is there a general frame of time for that? I have to have my entire game finished by the end of April.

**Comment by KyleStorck** [comment]
No ETA on when the fix will be released. We'll get back to you if there's an update.

I think something went wrong when you were converting the plugin from a marketplace engine plugin to a project plugin. That's a messy process and a few different things could have gone wrong. My recommendation is to start completely fresh. 

- Uninstall Project Acoustics from Epic launcher. Make sure the plugin is removed from the engine marketplace directory. 
- Remove the Project Acoustics project plugin you created before
- Download our plugin source code from here https://www.microsoft.com/en-us/download/confirmation.aspx?id=104791, and install it as a project plugin. Don't apply the fix yet. Make sure the original plugin bakes for you.
  - If you download the plugin this way, the plugin binaries may get a "Mark of the Web" that you will have to remove. See this for how to remove MOTW https://learn.microsoft.com/en-us/gaming/acoustics/known-issues#in-unreal-engine-the-bake-tab-does-not-display-properly-or-module-load-errors-appear-in-the-output-log
- Then try to apply the fixes once the original plugin is working.

**Comment by haisting** [comment]
Thank you for being so helpful Kyle. I'm working through it right now. I did get this issue with python on the manual install.
![image](https://user-images.githubusercontent.com/75640805/219818466-6276cbfb-c491-4601-b12a-dff68132d812.png)

When installing the plugin this way, what is the proper way to do it? Do I open the project's .sln and rebuild (or build?) the project? Or do I build both the project and the engine?

**Comment by KyleStorck** [comment]
What are the messages in the Output Log?

**Comment by haisting** [comment]
![image](https://user-images.githubusercontent.com/75640805/219820628-debb43cf-5717-41da-bfab-5d99c22e04d1.png)

**Comment by haisting** [comment]
Ohhh this was the bug you were talking about, going through that solution now.

**Comment by KyleStorck** [comment]
Yes, remove Mark of the Web from all the files in Plugins\ProjectAcousticsNative\Source\ThirdParty\Win64\Release

**Comment by haisting** [comment]
I got them all unblock and restarted the engine and the tab loaded! But when I tried to calculate it gave me the same error. (To confirm I haven't done the other fix for levels yet, only manual install and unblocking .dll files)

![image](https://user-images.githubusercontent.com/75640805/219821338-5951e094-e4c9-4843-b8fd-a0df195849aa.png)

**Comment by KyleStorck** [comment]
Well, we know it's not the fix nor is it not the plugin conversion process. But now I'm stumped. I'll think more on it next week.

**Comment by haisting** [comment]
Hey Kyle! I just wanted to touch base and see if there are any updates on this issue.

**Comment by KyleStorck** [comment]
No, still not sure what could be wrong with your setup. Weird that it works fine when you use the Marketplace plugin. Some thoughts

- If you were able to debug through Visual Studio that would give us more information
- Double check you have the requirements installed: https://learn.microsoft.com/en-us/gaming/acoustics/unreal-audio-integration 
- Check that your path is not too long. Put your project close to the root ("c:\projects"). 
- Could you post some pics of what your project and plugin directory look like. Like the ones I posted below
- You could try copy-pasting the Project Acoustics ThirdParty directory from the marketplace plugin into your project plugin. Not sure why those binaries work and the other ones don't
- Have you tried different scenes?

![image](https://user-images.githubusercontent.com/1233941/221216381-7f363c3a-ec9a-4071-8b4c-6ad2ba79f206.png)
![image](https://user-images.githubusercontent.com/1233941/221216436-33ecc318-f089-44f7-9489-c812baeca7cf.png)

**Comment by KyleStorck** [comment]
A fix for the level change crash has been pushed to the marketplace. It can be found in version 4 (2022.1.410) of the Project Acoustics plugin.
