### ISSUE TITLE
Interpolation resolvers - QuerySuccess

### ISSUE THREAD

**Issue by HDalsfelt** [microsoft/ProjectAcoustics#162]
Hi,

I'm testing different resolvers for solving situations where the query fails, and it works fine in most cases. But sometimes the audio isn't audible at all and if I look at the results from the UpdateObjectParameters the data is gibberish. But the function seems to always return that the query succeeds when I'm using interpolation resolvers, making it hard to catch these special cases. Is there any other way to check if the query failed?
For some important sounds, I would like to be able to "just play without acoustics" as a fallback if the query fails, better than silence.

**Comment by KyleStorck** [comment]
Can you post some pictures/logs of the failures and gibberish you're seeing

**Comment by HDalsfelt** [comment]
Sure! Here are two logs; one working and one failure, a "pixel" difference in position. 
![Acoustics_values_incorrect_more](https://user-images.githubusercontent.com/107394500/219065677-85b73013-c7ba-4fd0-90cd-54420efcf177.jpg)
![Acoustics_values_correct_more](https://user-images.githubusercontent.com/107394500/219065730-b74a3d69-eefc-400c-9238-9975752cfe0c.jpg)

**Comment by KyleStorck** [comment]
Are you using the Unreal native SDO plugin or the UE/Wwise plugin?

Which resolver are you using when you see the gibberish queries? Does the audio sound fine in that spot with other resolvers?

**Comment by HDalsfelt** [comment]
I'm using the UE/Wwise plugin.
This example was with Blend resolver, but I've noticed same behavior with Loudest. The problem might occur with any resolver. It is bad positions, in corners with grenades so you can squeeze them into... not optimal positions. That it always shows that query succeed when using resolvers, is that by design?

**Comment by KyleStorck** [comment]
Can you turn on the per-source debug parameters and send a pic of what they look like in the gibberish case. On your AcousticsAudioComponent, enable "Show Acoustic Parameters"

**Comment by KyleStorck** [comment]
And also a pic or explanation of what the audio source and listener (camera) are doing in that case

**Comment by HDalsfelt** [comment]
Here are two pictures working/not working. The not working one just shows the red square, and the one working shows info and receiver samples(?) (not sure what all the debug stuff actually means :)). 

The audio component spawns when the grenade explodes, and are removed when done playing, I did suspect that it was some timing issue (create component/tick). But the problem only occurs at places that are a bit difficult to solve for PA (and it is not easy to reproduce even then). The listener stands still. 
![no_effect_not_working](https://user-images.githubusercontent.com/107394500/219376581-a8e669b0-945a-40c8-abfd-ad2504fa250b.jpg)
![no_effect_ok](https://user-images.githubusercontent.com/107394500/219376591-2759c158-396f-4465-b145-f759e42a2b08.jpg)

**Comment by KyleStorck** [comment]
Thanks for the bug report. A query returning success with bad parameters is bad. Filed a bug and we'll look at it. 

>  I would like to be able to "just play without acoustics" as a fallback if the query fails,

This should be the behavior, but I'm guessing that because the query returns success with bad parameters, the bad parameters are making the audio inaudible.

**Comment by HDalsfelt** [comment]
Thanks. Yes, it sounds like what's happening. Would be nice if the resolver solution differs too much from the source it should fail (or at least there's an option for that behavior).

**Comment by NoelCross** [comment]
@HDalsfelt just getting back to this one after a few months.  We haven't seen this behavior internally after extensive testing on our team and with our experience working with several studios.  If you have a minimum repo that you could share with us to investigate, that would be ideal.  Otherwise, our only other hypothesis is some sort of memory corruption in the configuration, and we haven't been able to pinpoint any root cause.
