### ISSUE TITLE
Resuming Local Baking when interrupted ?

### ISSUE THREAD

**Issue by laurelhach** [microsoft/ProjectAcoustics#163]
Hi,

Was wondering if this is possible to resume a local bake when the bake process has been stopped?
Let say I reached 650 / 800 tasks and I'd like to be able to continue the task without restarting from the beginning (is it even possible)

Thanks!

**Comment by MikeChemi** [comment]
Try adding "--resume true" to the end of the command line for local processor.exe and run again.

Sent from Surface Duo
________________________________
From: laurelhach ***@***.***>
Sent: Monday, March 6, 2023 12:41:16 PM
To: microsoft/ProjectAcoustics ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/ProjectAcoustics] Resuming Local Baking when interrupted ? (Issue #163)


Hi,

Was wondering if this is possible to resume a local bake when the bake process has been stopped?
Let say I reached 650 / 800 tasks and I'd like to be able to continue the task without restarting from the beginning (is it even possible)

Thanks!

**Comment by haisting** [comment]
Hey Mike,

What file specifically are you referring to? The RunLocalBake.bat ?

**Comment by laurelhach** [comment]
yes runlocalbake.bat, it's working wonderfully :)

**Comment by haisting** [comment]
Hey Laurel!

Do you mind sharing a screenshot so I can confirm I'm doing this correctly?

**Comment by laurelhach** [comment]
Basically you need to edit the *.bat file.
Here is the line in my *.bat file:

docker run --rm -w /acoustics/ -v "%CD%":/acoustics/working/ mcr.microsoft.com/acoustics/baketools:2022.1.Linux ./tools/Triton.LocalProcessor --configfile Acoustics_PrisonUnderground_config.xml --workingdir working **--resume true**
del *.enc

**Comment by haisting** [comment]
I'm so sorry for being a bot, just to confirm, I would put this on the line before: del "%YYYY%MM%%DD%-%HH%%MN%\*.enc
Right?

So it would look like this?

![image](https://user-images.githubusercontent.com/75640805/223303471-89afa00c-cd01-4aa9-81b0-13e97794fbfe.png)

**Comment by nikunjragh** [comment]
At the end of line 8 so it looks like, `... --WorkingDir %YYYY%MM%%DD%-%HH%%MN% --resume true`

**Comment by haisting** [comment]
Thanks!! I got it working :)
