### ISSUE TITLE
Errors packaging Unreal Engine project with Project Acoustics

### ISSUE THREAD

**Issue by aidannewsome** [microsoft/ProjectAcoustics#165]
Hello,

I'm getting this new error when packaging my project with Project Acoustics. Do you have any idea why? I wasn't getting it before with 5.1.1. and I'm using the code fix from #147. I can't narrow down what change may have caused it. It begins with:

> Parsing headers for CH_VR_Experience_UE5
>   Running Internal UnrealHeaderTool "C:\Perforce\Circadian House VR Experience UE5\CH_VR_Experience_UE5.1\CH_VR_Experience_UE5.uproject" "C:\Perforce\Circadian House VR Experience UE5\CH_VR_Experience_UE5.1\Intermediate\Build\Win64\CH_VR_Experience_UE5\Development\CH_VR_Experience_UE5.uhtmanifest" -WarningsAsErrors -installed
> C:\Perforce\Circadian House VR Experience UE5\CH_VR_Experience_UE5.1\Plugins\ProjectAcousticsNative\Intermediate\Build\Win64\UnrealGame\Inc\ProjectAcousticsNative\UHT

Thank you,

Aidan

[New_Project_Acoustics_Packaging_Problem.log](https://github.com/microsoft/ProjectAcoustics/files/10935467/New_Project_Acoustics_Packaging_Problem.log)

**Comment by KyleStorck** [comment]
First thought is check your path length. Move your project closer to the root directory.

**Comment by NoelCross** [comment]
Also, you might want to try deleting your Intermediate folder.  If you renamed your project in the past, there might be lingering files in that folder from the previously named project.

You also might want to inspect the UBT log mentioned in the file you shared for more clues:
C:\Users\Aidan Newsome\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.1\UBT-CH_VR_Experience_UE5-Win64-Development.txt

**Comment by aidannewsome** [comment]
Thanks, Kyle, I've done this, and I realize now that my project and folder names are pretty verbose (I'm a non-programmer, and I'm learning, so apologies). I also ensured support for "Long Path Names" was enabled in my Registry, which it was. I'm still getting the error.

I will try Noel's suggestion now.

Noel, is the "Intermediate" folder you're speaking of the one inside the "ProjectAcousticsNative" folder or the layer beneath my project folder?

**Comment by NoelCross** [comment]
Probably best to delete at least the Intermediate folders in the main project directory and the one in the PA plugin directory as well.  UE will rebuild those directories on your behalf.  I'm not sure if this will help, but it shouldn't hurt since these folders are generated and should be generated again after being deleted.

**Comment by aidannewsome** [comment]
No luck, unfortunately. I did notice that the path in this file is incorrect. Could that be why? Any idea how to properly fix that file path to be the correct one?

![Acoustics_Path_Incorrect](https://user-images.githubusercontent.com/32934243/224756613-d55dbc91-b707-4432-a672-aa1bf6e370bb.png)

**Comment by aidannewsome** [comment]
Hi Noel! You can mark this as closed if you'd like. For anyone experiencing this error in the future, it's likely because you're using "Project Launcher" to package your game and don't have the "Project" dropdown pointing to the correct project path. For me, this was because I was packaging from another workstation.

**Comment by NoelCross** [comment]
Good news that you figured this out.  I'm glad since I was running out of ideas on what to do next.
