### ISSUE TITLE
Acoustics Tab not showing up in Window menu

### ISSUE THREAD

**Issue by srya2544** [microsoft/ProjectAcoustics#17]
Hello,

I've been following the steps in https://docs.microsoft.com/en-us/azure/cognitive-services/acoustics/unity-quickstart but the acoustics tab just won't show up in the Windows Tab. 
Not sure where else to find and open the floating acoustics window.

I'm using Unity 2018.2.21f1 

Any help is hugely appreciated,

Cheers,

Shane

**Comment by MikeChemi** [comment]
Hi there @srya2544 , Do you have any warnings/errors showing up in Unity's console window?

**Comment by NoelCross** [comment]
@srya2544, please do share any information displayed on the console window with us so we can understand why the Acoustics window isn't showing up for you.  Thanks!

**Comment by ashtat** [comment]
@srya2544 If you're seeing assembly reference issues with "ProtectedData" namespace, one quick thing you can try is to rename csc.rsp to mcs.rsp and then restart the editor. Let us know if that helps!

**Comment by kegodin** [comment]
Hi @srya2544 , thanks for trying out Project Acoustics. We'd love to help if you're still having trouble opening the Acoustics window, but we'd need more info. @ashtat has a suggestion above to try, and sometimes after first installing the Project Acoustics plugin it helps to close and reopen the Unity project.

Closing this issue for now, but please re-open this issue if there's anything more we can do. Thanks!
