### ISSUE TITLE
Roadmap, Unreal 5.2 Support

### ISSUE THREAD

**Issue by timoxley** [microsoft/ProjectAcoustics#170]
I'm on a team currently building out an audio-centric game on UE5.1 using ProjectAcoustics & Wwise. So far I love the results, but I do worry about long-term support and/or being stuck on an old version of unreal for an extended period of time while waiting for an update on ProjectAcoustics end.

Is there a roadmap or release schedule for ProjectAcoustics? I notice it hasn't seen any (public) updates in a while. Is the project still under active development? 

The Unreal Engine 5.2 release is imminent, will there be a new ProjectAcoustics Release for 5.2?

**Comment by NoelCross** [comment]
@timoxley Thank you for your interest in Project Acoustics.  The last major release for Project Acoustics was in November 2022 and a minor bug fix update was provided on the Unreal Marketplace last week.

As for a roadmap, we don't have anything shared for our future plans.  I am happy to say that the project is still under active development, and we do plan on continuing support for our public releases for the foreseeable future.

We haven't started testing against Unreal Engine 5.2.  Regardless, I wouldn't expect that our plugin would be impacted too much by the update, if at all.  We'll need to discuss internally what our plans and timing are for updating the marketplace plugin to support Unreal Engine 5.2.  We don't have a target date at this time.

**Comment by NoelCross** [comment]
@timoxley The UE5.2 plugin is now available on the marketplace.  Let us know if you run into any issues.
