### ISSUE TITLE
[Triton] InitLoadMultiple - ACE file at index 1 has incompatible metadata

### ISSUE THREAD

**Issue by afrostalin** [microsoft/ProjectAcoustics#172]
Hello there. We use project acoustic (plugin 2022.1.410 ) with UE 5.1.1. 
We try implement `InitLoadMultiple` function from triton with array of `FTritonUnrealIOHook` for loading more .ace files at once, but it's not work for us, we got error: 

`LogAcousticsRuntime: Error: [TritonRuntime::EncodedMapData::EncodedMapDataPrivate::Init, Ln474] ACE file at index 1 has incompatible metadata.`

Moreover, if there is only one file in the array, everything will work like a normal call `InitLoad()`

Could you explain how we can set up our .ace files so they can loaded by `InitLoadMultiple`?

**Comment by MikeChemi** [comment]
The incompatible metadata error occurs when the two .ace files have different global parameters. For example, if one .ace file was baked at the "coarse" setting and the other at the "fine" setting, you won't be able to load them both at once.

**Comment by afrostalin** [comment]
Thanks for you asnwer, we will check it & write result here

**Comment by afrostalin** [comment]
Thanks again for your reply, we re-baked the acoustic date with the same settings and everything worked as expected!
