### ISSUE TITLE
[UE5.2] Crash on shutdown

### ISSUE THREAD

**Issue by afrostalin** [microsoft/ProjectAcoustics#175]
Hello there. We have crash on `FAcousticsSpatializer::Shutdown()` when `HrtfEngineUninitialize` called & also in `FAcousticsSpatialReverb::ProcessAllSources` when `HrtfEngineProcess` called. All this happens in the editor, when you exit the game mode. It is also often repeated when trying to launch the client + server in the main window in the editor.
We understand that there is no set timeline for an official update right now, but we hope someone will point us in the right direction in resolving this issue on our own.

Best regards

**Comment by NoelCross** [comment]
@afrostalin Thank you for reporting this problem.  We have a plan to do a UE5.2 marketplace update of our plugins in the next 4-6 weeks so we'll add this to the list of issues to address for this update.

Does this happen consistently when exiting game mode with the Microsoft Spatializer plugin chosen for spatialization?  Or does it only happen some of the time in your testing?

**Comment by afrostalin** [comment]
This happens stably in the editor on the second launch of the game mode. I added some changes to the call order and it helped a bit and removed the direct dependency, but it still happens at random times

**Comment by NoelCross** [comment]
@afrostalin The UE5.2 update is now on the UE Marketplace with a fix to address this issue.  Thanks for your patience.
