### ISSUE TITLE
Installing plugin to an Unreal Engine 5.2 project. 

### ISSUE THREAD

**Issue by Noscka** [microsoft/ProjectAcoustics#178]
Hello,

So I am trying to install the plugin to an Unreal Engine 5.2 project, I've tried installing the Wwise version, that failed with an error:
```
<Project>\Plugins\ProjectAcousticsWwise\Intermediate\Build\Win64\x64\UnrealEditor\Development\ProjectAcousticsBakeUI\Module.ProjectAcousticsBakeUI.cpp : fatal error C1001: Internal compiler error
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 224)
```
So I gave up on that, I then tried to install the standalone, marketplace version. I installed it to Unreal Engine 5.2, tried to launch and got an error which said something along the lines "binaries missing or compiled for another version, recompile with IDE because it's an engine module". So I moved the plugin to my project instead and tried to compile it that way, from there I had some errors with FVector and Fvector3f but those were easy to fix. but now I am running into another issue. I have an error which says `'TObjectPtr<T> can only be used with types derived from UObject' note: see reference to class template instantiation 'TObjectPtr<FProjectAcousticsNativeModule>' being compiled` and underneath, get the same internal compiler error again:
```
<Project>\Plugins\ProjectAcousticsNative\Intermediate\Build\Win64\x64\UnrealEditor\Development\ProjectAcousticsBakeUI\Module.ProjectAcousticsBakeUI.cpp : fatal error C1001: Internal compiler error.
1>(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 224)
```

So is there anything I can do to fix this, or is there a 5.2 version going to be coming out soon?

**Comment by NoelCross** [comment]
@Noscka We are in the process of getting the UE5.2 plugin posted on the Unreal Marketplace.  We plan on submitting the update to Epic today and they will evaluate the update before allowing the plugin to go live.  The issues that you are reporting should be addressed with this update.  Thanks for your interest in the project!

**Comment by Noscka** [comment]
Oh great, thank you very much. Would you know what time about the update should be live?

**Comment by NoelCross** [comment]
@Noscka My best guess is 3-5 business days for the evaluation to happen.  Since this is a simple patch update and not a new product, it shouldn't take long, but the process is opaque to us, so this is just a best guess.

**Comment by Noscka** [comment]
ok, well thank you very much for your time.

**Comment by NoelCross** [comment]
@Noscka This UE5.2 plugin is now available on the Unreal Marketplace.  Please download and let us know if you run into any problems.  Thanks!
