### ISSUE TITLE
Apple silicon support?

### ISSUE THREAD

**Issue by antja0** [microsoft/ProjectAcoustics#183]

**Comment by NoelCross** [comment]
Hello @antja0, 

While it is technically possible to get PA running on Apple silicon, it is a direction that we have not pursued at this time with this project.  This support is not on our immediate roadmap.  We hope that you still find Project Acoustics useful for your needs.

Thanks,
Noel

**Comment by antja0** [comment]
ok

mention of it would be highly appreciated.

https://www.microsoft.com/en-us/download/details.aspx?id=57346

> Target platform support:
> Windows desktop (x86 and AMD64)
> Windows UWP (x86, AMD64, and ARM)
> Android (x86 and ARM64)
> MacOS

**Comment by NoelCross** [comment]
@antja0 Thanks for the feedback.  I've updated the text on the Download Center to clarify.

Target platform support:
Windows desktop (x86 and AMD64)
Windows UWP (x86, AMD64, and ARM)
Android (x86 and ARM64)
MacOS **(Intel silicon binaries only)**
