### ISSUE TITLE
Unreal 5.3 Support timeline

### ISSUE THREAD

**Issue by CaptainCheerios** [microsoft/ProjectAcoustics#185]
I was wondering when support for the next version of unreal is coming out?

**Comment by NoelCross** [comment]
@CaptainCheerios we are in the process of doing final validation and submission to Epic for evaluation.  I would expect the 5.3 version to be on the marketplace in about a week or so.

**Comment by KyleStorck** [comment]
5.3 version of the plugin was released last week.
