### ISSUE TITLE
Unity integration: FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by AndersMalmgren** [microsoft/ProjectAcoustics#2]
I get this when I try to calculate probes. Unity 2019.2.5.  OS (Windows 10) is set to Swedish culture

> FormatException: Input string was not in a correct format.
> System.Number.ParseDouble (System.String value, System.Globalization.NumberStyles options, System.Globalization.NumberFormatInfo numfmt) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
> System.Double.Parse (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
> System.Double.Parse (System.String s) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
> Microsoft.Cloud.Acoustics.ComputeCostPredictor.InitializeCostBasis (System.String costsheet, Microsoft.Cloud.Acoustics.SimulationConfiguration& costBasisConfiguration, System.Collections.Generic.List`1[Microsoft.Cloud.Acoustics.ComputeNodeCostInformation]& nodeCosts) (at <81f508e053f048a59a07e00307dfbdc1>:0)
> Microsoft.Cloud.Acoustics.ComputeCostPredictor.EstimateProcessingTime (System.String costsheet, Microsoft.Cloud.Acoustics.SimulationConfiguration target, Microsoft.Cloud.Acoustics.ComputePoolConfiguration pool) (at <81f508e053f048a59a07e00307dfbdc1>:0)
> Microsoft.Cloud.Acoustics.CloudProcessor.EstimateProcessingTime (System.String costsheet, Microsoft.Cloud.Acoustics.SimulationConfiguration targetConfiguration, Microsoft.Cloud.Acoustics.ComputePoolConfiguration targetPool) (at <81f508e053f048a59a07e00307dfbdc1>:0)
> Microsoft.Cloud.Acoustics.AcousticsEditor.UpdateComputeTimeEstimate () (at Assets/Acoustics/Editor/AcousticsEditor.cs:1696)
> Microsoft.Cloud.Acoustics.AcousticsEditor.DisplayPreviewResults () (at Assets/Acoustics/Editor/AcousticsEditor.cs:1638)
> Microsoft.Cloud.Acoustics.AcousticsEditor.Update () (at Assets/Acoustics/Editor/AcousticsEditor.cs:189)
> System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
> Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
> System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
> System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
> UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:359)
> UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:353)
> UnityEditor.HostView.SendUpdate () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:465)
> UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:303)

**Comment by AndersMalmgren** [comment]
Setting `CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;` does fix the problem, but its probably not a viable solution.

**Comment by ashtat** [comment]
Thanks for reporting this Anders, we'll get this fixed asap!

**Comment by kegodin** [comment]
This is fixed in our internal develop branch and slated for inclusion with the next release

**Comment by bouiz** [comment]
Hello, 
I am having the same issue as Anders. Using Unity 2019.4. OS (Windows 10)
Where should I add the "CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;" line code ? 
(I only have a basic level in coding)

**Comment by ashtat** [comment]
@bouiz you can try adding that line to OnEnable function in AcousticsParameters.cs - 

```
        public void OnEnable()
        {
            System.Globalization.CultureInfo.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture;
            ListView?.Reload();
        }
```

**Comment by bouiz** [comment]
@ashtat it works !
Thanks a lot
