### ISSUE TITLE
Mesh components within an actor aren't voxelized.

### ISSUE THREAD

**Issue by borogove** [microsoft/ProjectAcoustics#20]
We've built a level out of modular "prefabs", actors which contain several static mesh components within them. 

- Bulk selection of static mesh in the Acoustics > Objects pane doesn't select them; it's only looking for static mesh actors. 
- Selecting the individual static mesh components and selecting tag doesn't change the object tag counts (fair enough, it's only counting actors).
- If the prefab actor is hand-selected and tagged as geometry, then calculating the voxelization and probes for the map doesn't appear to voxelize any of the geometry in the prefab. The log reports:

```LogAcoustics: Error: Unsupported Actor tagged for Acoustics: Trench_Prefab_2```

This sort of modular construction seems pretty valuable. If an actor is specifically tagged for acoustics, it seems like it should get scanned for mesh components.

**Comment by NoelCross** [comment]
Do you happen to know if Trench_Prefab_2 is a AGroupActor?  We currently only support AStaticMeshActor and ALandscapeProxy, but are open to supporting more Actors types if needed.

**Comment by borogove** [comment]
It's its own blueprint class with Actor as its parent class.

**Comment by borogove** [comment]
Do you plan to support geometry brushes? I don't think we're planning to rely on them for production, but we have used some in quick-and-dirty test levels.

**Comment by MikeChemi** [comment]
Static mesh components are supported in the 3.0 release, available now! #94
