### ISSUE TITLE
Bug: Silent UAcousticsAudioComponent ignores ShowAcousticParameters true->false transition

### ISSUE THREAD

**Issue by borogove** [microsoft/ProjectAcoustics#21]
Toggling ShowAcousticParameters to true causes debug information to be shown, as expected. Toggling it back to false causes an early exit from TickComponent if there's no sound playing on the component, so UpdateSourceDebugInfo isn't called, and the acoustics system isn't told to turn off debug info for that object. 

EDIT: There's something more going on here that I don't fully understand -- in some cases turning ShowAcousticParameters false->true does display debug, in other cases it doesn't. I'll try and get more info on this tomorrow.

**Comment by kegodin** [comment]
Thanks for filing this bug. This is tracked internally as ADO bug # 25217155. Please share any additional repro info, if available. Thanks!
