### ISSUE TITLE
Do Unity plugin actually support multiple materials on same mesh renderer?

### ISSUE THREAD

**Issue by AndersMalmgren** [microsoft/ProjectAcoustics#22]
The plugin does not complain and the bake works. But it does not sound like there is any glass window    in my concrete wall (Transmission etc is like it would be all concrete). Does Unity plugin voxelization distinct two materials on the same mesh render?

**Comment by MikeChemi** [comment]
Hi Anders, Can you elaborate more on why the materials do not sound correct? Project Acoustics currently does not simulate transmission effects, so in that respect glass and concrete would behave the same (in that there would be no transmission). What other effects are you expecting to be able to hear, but aren't hearing?

**Comment by AndersMalmgren** [comment]
Ah I thought it did sorry. Then it's harder for me to know if it's sound correct. Multiple materials on same mesh will be more important when and if you support transmission.

**Comment by AndersMalmgren** [comment]
Though I do bake some smaller stuff into a larger mesh and then it would be awesome if it did take individual materials into account.

**Comment by kegodin** [comment]
Hi @AndersMalmgren , thanks for your question. As Mike mentioned, Project Acoustics doesn't simulate transmission effects. The included DSP does provide a transmission effect that is driven manually by the user. For simulating reverberation, Triton applies materials based on the visual rendering material used for each mesh. 

It looks like your question was answered so I'm closing this issue for now. Please reopen, or open another issue, to let us know if we can answer additional questions or if you have a specific feature request. Thanks!
