### ISSUE TITLE
Can I pause a self hosted batch somehow?

### ISSUE THREAD

**Issue by AndersMalmgren** [microsoft/ProjectAcoustics#23]
I'm running self hosted on a AMD 3950x. Can I pause the work somehow to use the computer for other stuff and than resume work later? Thanks.

**Comment by AndersMalmgren** [comment]
I will play around with docker pause / unpausae and see if it works.

**Comment by NoelCross** [comment]
We haven't tried to pause a docker container during a bake, but it seems logical that pausing the container would keep the work in a suspended state until it is resumed again.  Let us know how it works for you.  Thanks!

**Comment by AndersMalmgren** [comment]
WIll do thanks

**Comment by AndersMalmgren** [comment]
Seems to work, did a fine back on a small test scene, issued a pause command and then unpause. The check phase passed ok and the bake seems fine
