### ISSUE TITLE
Multiple scenes point to the same AcousticParameters

### ISSUE THREAD

**Issue by AndersMalmgren** [microsoft/ProjectAcoustics#26]
In unity create a scene. Config it and prebake it. It will create a AcousticParameters asset for the scene. Create a new scene with another name, config it and prebake it it will create  AcousticParameters asset. Move back to the first scene. It will now point to the new scene AcousticParameters and preview will preview voxels from newest scene, not the correct scene.

**Comment by AndersMalmgren** [comment]
Restarting Unity and both scenes pont to their respective parameter asset

**Comment by kegodin** [comment]
Thanks for filing this issue. It's tracked internally with ADO bug # 25172180.
