### ISSUE TITLE
Unity terrain is not voxelized 

### ISSUE THREAD

**Issue by AndersMalmgren** [microsoft/ProjectAcoustics#30]
I'm on Unity 2019.2.19, I have marked the terrain as geo but its not voxelized during prebake

![image](https://user-images.githubusercontent.com/817577/73973330-a38f1380-4922-11ea-8728-416c64906063.png)

**Comment by kegodin** [comment]
Thanks for reporting this bug. For our bookkeeping, I'll note that we're tracking this internally with ADO bug # 25298969.

**Comment by MikeChemi** [comment]
We're not planning on adding support for terrains any time soon. Let us know if this is a major blocker for you.
