### ISSUE TITLE
Unity editor crash when reaching navigation bounding box and voxels spread outside box

### ISSUE THREAD

**Issue by AndersMalmgren** [microsoft/ProjectAcoustics#31]
Here is our scene, navigation mesh highlighted. The subway tunnels north of navigation bounding box span outside of the bounding box. 

![image](https://user-images.githubusercontent.com/817577/74129801-c9494080-4be0-11ea-8cb0-ce6fe1f862b7.png)

When voxels are previewed and I go beyond the green line unity crashes. I do not know if this affect runtime yet. Here is stacktrace

> 0x00007FFAF8688B24 (Triton.Preprocessor) TritonPreprocessor_SimulationConfiguration_IsVoxelOccupied
> 0x0000026324E73731 (Mono JIT Code) (wrapper managed-to-native) Triton.SimulationConfigNativeMethods:TritonPreprocessor_SimulationConfiguration_IsVoxelOccupied (intptr,Triton.ATKVectorI,bool&)
> 0x0000026318F7456B (Mono JIT Code) Triton.SimulationConfig:GetVoxelOccupancy (int,int,int)
> 0x0000026318F742EB (Mono JIT Code) [E:\Unity Projects\vwf_2018\Assets\Acoustics\Editor\AcousticsVoxelsRenderer.cs:229] Microsoft.Cloud.Acoustics.AcousticsVoxelsRenderer:GetVoxelOccupancy (int,int,int) 
> 0x0000026318A4C803 (Mono JIT Code) [E:\Unity Projects\vwf_2018\Assets\Acoustics\Editor\AcousticsVoxelsRenderer.cs:163] Microsoft.Cloud.Acoustics.AcousticsVoxelsRenderer:Render () 
> 0x0000026318A48837 (Mono JIT Code) [E:\Unity Projects\vwf_2018\Assets\Acoustics\Scripts\AcousticsVoxels.cs:18] AcousticsVoxels:OnDrawGizmos () 
> 0x00000263775BA318 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
> 0x00007FFAB08ABFB0 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\mini\mini-runtime.c:2809] mono_jit_runtime_invoke 
> 0x00007FFAB0832142 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\object.c:2921] do_runtime_invoke 
> 0x00007FFAB083B13F (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\object.c:2968] mono_runtime_invoke 
> 0x00007FF61B501012 (Unity) scripting_method_invoke
> 0x00007FF61B4FACC1 (Unity) ScriptingInvocation::Invoke
> 0x00007FF61B4FAF3E (Unity) ScriptingInvocation::InvokeChecked
> 0x00007FF61B559EB2 (Unity) SerializableManagedRef::CallMethod
> 0x00007FF61999EE07 (Unity) DrawMonoGizmo
> 0x00007FF61999BD27 (Unity) GizmoManager::DrawActiveGizmos
> 0x00007FF61999DBC0 (Unity) GizmoManager::DrawGizmos
> 0x00007FF619BD5FA7 (Unity) Camera::FinishRenderingEditorCamera
> 0x00007FF61A497301 (Unity) Handles_CUSTOM_Internal_FinishDrawingCamera
> 0x000002638030D487 (Mono JIT Code) (wrapper managed-to-native) UnityEditor.Handles:Internal_FinishDrawingCamera (UnityEngine.Camera,bool)
> 0x00000263802D528B (Mono JIT Code) [C:\buildslave\unity\build\Editor\Mono\Handles.cs:1381] UnityEditor.Handles:DrawCameraStep2 (UnityEngine.Camera,UnityEditor.DrawCameraMode,bool) 
> 0x000002638028DA13 (Mono JIT Code) [C:\buildslave\unity\build\Editor\Mono\SceneView\SceneView.cs:2362] UnityEditor.SceneView:OnGUI () 
> 0x000002636E6A86C8 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
> 0x00007FFAB08ABFB0 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\mini\mini-runtime.c:2809] mono_jit_runtime_invoke 
> 0x00007FFAB0832142 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\object.c:2921] do_runtime_invoke 
> 0x00007FFAB083B312 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\object.c:3073] mono_runtime_invoke_checked 
> 0x00007FFAB083BAA9 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\object.c:5264] mono_runtime_try_invoke_array 
> 0x00007FFAB083B2A6 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\object.c:5142] mono_runtime_invoke_array_checked 
> 0x00007FFAB07E02D4 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\icall.c:3358] ves_icall_InternalInvoke 
> 0x00000263774388D6 (Mono JIT Code) (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
> 0x0000026377436E3B (Mono JIT Code) System.Reflection.MonoMethod:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
> 0x0000026377436AFF (Mono JIT Code) System.Reflection.MethodBase:Invoke (object,object[])
> 0x000002638001B323 (Mono JIT Code) [C:\buildslave\unity\build\Editor\Mono\HostView.cs:359] UnityEditor.HostView:Invoke (string,object) 
> 0x000002638001B173 (Mono JIT Code) [C:\buildslave\unity\build\Editor\Mono\HostView.cs:354] UnityEditor.HostView:Invoke (string) 
> 0x0000026380229F93 (Mono JIT Code) [C:\buildslave\unity\build\Editor\Mono\HostView.cs:323] UnityEditor.HostView:InvokeOnGUI (UnityEngine.Rect,UnityEngine.Rect) 
> 0x00000263802297CB (Mono JIT Code) [C:\buildslave\unity\build\Editor\Mono\GUI\DockArea.cs:375] UnityEditor.DockArea:DrawView (UnityEngine.Rect,UnityEngine.Rect,bool,bool) 
> 0x0000026380213BA3 (Mono JIT Code) [C:\buildslave\unity\build\Editor\Mono\GUI\DockArea.cs:347] UnityEditor.DockArea:OldOnGUI () 
> 0x0000026380146CF9 (Mono JIT Code) [C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:281] UnityEngine.UIElements.IMGUIContainer:DoOnGUI (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,bool,UnityEngine.Rect) 
> 0x0000026380144CBB (Mono JIT Code) [C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:485] UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect) 
> 0x0000026380142963 (Mono JIT Code) [C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:458] UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent () 
> 0x000002638013D242 (Mono JIT Code) [C:\buildslave\unity\build\Modules\UIElements\Renderer\UIRenderer\UIRenderers.cs:113] UnityEngine.UIElements.UIR.RenderChainCommand:ExecuteNonDrawMesh (UnityEngine.UIElements.UIR.DrawParams,bool,System.Exception&) 
> 0x0000026380137BA3 (Mono JIT Code) [C:\buildslave\unity\build\Modules\UIElements\Renderer\UIRenderer\UIRenderDevice.cs:887] UnityEngine.UIElements.UIR.UIRenderDevice:EvaluateChain (UnityEngine.UIElements.UIR.RenderChainCommand,UnityEngine.Rect,UnityEngine.Matrix4x4,UnityEngine.Texture,System.Exception&) 
> 0x0000026380131363 (Mono JIT Code) [C:\buildslave\unity\build\Modules\UIElements\Renderer\UIRenderer\UIRenderDevice.cs:988] UnityEngine.UIElements.UIR.UIRenderDevice:DrawChain (UnityEngine.UIElements.UIR.RenderChainCommand,UnityEngine.Rect,UnityEngine.Matrix4x4,UnityEngine.Texture,System.Exception&) 
> 0x000002638011615B (Mono JIT Code) [C:\buildslave\unity\build\Modules\UIElements\Renderer\UIRChainBuilder.cs:235] UnityEngine.UIElements.UIR.RenderChain:Render (UnityEngine.Rect,UnityEngine.Matrix4x4) 
> 0x00000263801143D3 (Mono JIT Code) [C:\buildslave\unity\build\Modules\UIElements\Renderer\UIRRepaintUpdater.cs:67] UnityEngine.UIElements.UIRRepaintUpdater:DrawChain (UnityEngine.Rect,UnityEngine.Matrix4x4) 
> 0x0000026380113CC0 (Mono JIT Code) [C:\buildslave\unity\build\Modules\UIElements\Renderer\UIRRepaintUpdater.cs:55] UnityEngine.UIElements.UIRRepaintUpdater:Update () 
> 0x00000263800F2201 (Mono JIT Code) [C:\buildslave\unity\build\Modules\UIElements\VisualTreeUpdater.cs:73] UnityEngine.UIElements.VisualTreeUpdater:UpdateVisualTree () 
> 0x00000263800F1953 (Mono JIT Code) [C:\buildslave\unity\build\Modules\UIElements\Panel.cs:638] UnityEngine.UIElements.Panel:Repaint (UnityEngine.Event) 
> 0x00000263800F0AD3 (Mono JIT Code) [C:\buildslave\unity\build\Modules\UIElements\UIElementsUtility.cs:246] UnityEngine.UIElements.UIElementsUtility:DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel) 
> 0x00000263800F061B (Mono JIT Code) [C:\buildslave\unity\build\Modules\UIElements\UIElementsUtility.cs:78] UnityEngine.UIElements.UIElementsUtility:ProcessEvent (int,intptr) 
> 0x00000263800EFE4E (Mono JIT Code) [C:\buildslave\unity\build\Modules\IMGUI\GUIUtility.cs:179] UnityEngine.GUIUtility:ProcessEvent (int,intptr) 
> 0x00000263800F0183 (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_bool_int_intptr (object,intptr,intptr,intptr)
> 0x00007FFAB08ABFB0 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\mini\mini-runtime.c:2809] mono_jit_runtime_invoke 
> 0x00007FFAB0832142 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\object.c:2921] do_runtime_invoke 
> 0x00007FFAB083B13F (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\object.c:2968] mono_runtime_invoke 
> 0x00007FF61B501012 (Unity) scripting_method_invoke
> 0x00007FF61B4FACC1 (Unity) ScriptingInvocation::Invoke
> 0x00007FF61B4F4F1A (Unity) ScriptingInvocation::Invoke<bool>
> 0x00007FF618A2DEC9 (Unity) Scripting::UnityEngine::GUIUtilityProxy::ProcessEvent
> 0x00007FF6194AA96C (Unity) GUIView::ProcessRetainedMode
> 0x00007FF619E2EB47 (Unity) GUIView::OnInputEvent
> 0x00007FF6194AA87C (Unity) GUIView::ProcessInputEvent
> 0x00007FF619E1ECE7 (Unity) GUIView::DoPaint
> 0x00007FF619E3152D (Unity) GUIView::RepaintAll
> 0x00007FF61957A1FC (Unity) Application::TickTimer
> 0x00007FF619E0F0A0 (Unity) MainMessageLoop
> 0x00007FF619E11ABF (Unity) WinMain
> 0x00007FF61CACC962 (Unity) __scrt_common_main_seh
> 0x00007FFB26CC7BD4 (KERNEL32) BaseThreadInitThunk
> 0x00007FFB2750CED1 (ntdll) RtlUserThreadStart

Just before crash I get this in log (you can ask @nikunjragh for full log)

> ---VOXELIZE NAVIGABLE AREA---
> 
> Mesh bbox: (-97.4111, -209.4, -16.8) - (24.1564, 195.881, 12.7442) meters
> Voxelization bbox: (-127.393, -255.46, -27.11) - (49.0667, 36.26, 36.13) meters
> Voxel map resolution: [ 346, 572, 124 ]. Total: 24541088
> Refinement factor: 1
> 
> Rescaling mesh for voxelization and clearing voxel map.
> Pruning triangles...
> Pruned triangles down frNumber of probe points: 383
> UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
> UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:Log(Object)
> Microsoft.Cloud.Acoustics.AcousticsEditor:DisplayPreviewResults() (at Assets\Acoustics\Editor\AcousticsEditor.cs:1640)
> Microsoft.Cloud.Acoustics.AcousticsEditor:Update() (at Assets\Acoustics\Editor\AcousticsEditor.cs:189)
> System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
> System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
> System.Reflection.MethodBase:Invoke(Object, Object[])
> UnityEditor.HostView:Invoke(String, Object) (at C:\buildslave\unity\build\Editor\Mono\HostView.cs:359)
> UnityEditor.HostView:Invoke(String) (at C:\buildslave\unity\build\Editor\Mono\HostView.cs:353)
> UnityEditor.HostView:SendUpdate() (at C:\buildslave\unity\build\Editor\Mono\HostView.cs:465)
> UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at C:\buildslave\unity\build\Editor\Mono\EditorApplication.cs:303)
>  
> (Filename: Assets/Acoustics/Editor/AcousticsEditor.cs Line: 1640)
> 
> 
> Hashing assets (1 files)... 0.000 seconds
>   file read: 0.000 seconds (0.003 MB)
>   wait for write: 0.000 seconds (I/O thread blocked by consumer, aka CPU bound)
>   wait for read: 0.000 seconds (CPUT thread waiting for I/O thread, aka disk bound)
>   hash: 0.000 seconds
> Updating Assets/ExternalResources/UrbanUnderground/Scenes/Editor/Subway_AcousticParameters.asset - GUID: a33049cf8734bbc4d9f8e25213ad003a...
>  done. [Time: 3.669000 ms] 
> Refreshing native plugins compatible for Editor in 2.41 ms, found 18 plugins.
> Preloading 2 native plugins for Editor in 0.10 ms.
> Crash!!!

**Comment by nikunjragh** [comment]
Full log: 
[Editor.log](https://github.com/microsoft/ProjectAcoustics/files/4179569/Editor.log)

**Comment by kegodin** [comment]
Thanks for filing this bug. For our own bookkeeping, I'll note that this is tracked internally with ADO bug # 25299035.

**Comment by MikeChemi** [comment]
There were significant updates in this code in our 2.0 release. Let us know if you're still hitting this crash with those tools. #55
