### ISSUE TITLE
Unable to bake / submit to Azure: "Too many probes!"

### ISSUE THREAD

**Issue by jaegrover** [microsoft/ProjectAcoustics#34]
Hi folks, hope everyone is doing well despite all the chaos in the world at the moment :) 

I'm currently working at integrating Project Acoustics with a VR FPS I'm working on. However, whenver attempting to Bake / submit the data to Azure, I receive the following error message: 

Error: Too Many Probes!
Ensure the scene has a navmesh and try reducing the number of Acoustic Geometry objects. 

Just to be safe, I tried this in a few different maps, including an extremely rudimentary test map that consisted of nothing more than 8 static meshes, each tagged with AcousticGeometry via the Acoustics window, all set to the same material, and a Unity Navmesh. I am using Unity 2019.3.0f6. I've tried a variety of different settings, including different Node Counts, Low Priority, and creating different Azure Storage/Batch accounts for different regions. What am I missing? 

The only other info I can think to mention is that, when first importing the Project Acoustics Unity file, I received a crash, then was able to open relaunch Unity. On doing so, I had 999+ Compiler errors that seemed to stem from having imported a duplicate file. Per recommendation from a coder on our team, deleting "System.Runtime.CompilerServices.Unsafe.dll" resolved these errors and I've been able to launch successfully since then. 

Thanks in advance for any advice you can offer. Best wishes,

-Jonathan

**Comment by jaegrover** [comment]
Edit: I also notice an editor error message in Unity after attempting a bake. I've created a pastebin with that info: 

https://pastebin.com/UEWQ9Kv2

**Comment by ashtat** [comment]
Hi Jonathan, I'm sorry you're running into these issues. Can you share how many probes are being generated for your scene? And have you marked your navmesh as Acoustics Navmesh? That will constrain the generated probes to the navmesh areas and reduce the number of probes for the simulation.

**Comment by jaegrover** [comment]
Hi Ashtat, thank you kindly for the fast reply!

I may have solved the issue - it turned out that the File Name of the Acoustics Files Prefix set in the Probes tab had some spaces in it, i.e. "Suburbia Day 1" - removing the whitespace (SuburbiaDay1) has let be successfully submit a bake, at least in my small test map. I'm trying out a larger map now. 

Just so I'm 100% sure I'm following the steps correctly, could you please point me to the instructions for marking the Navmesh? I'm able to generate one with the standard Unity workflow (/ see the ones the level designers have made for the larger levels), and can successfully Calculate probes from the Probes tab in the Acoustics window. The probes and voxels appear to display correctly in the editor preview window. 

Thank you once again :) I'll update as soon as I have results back from the larger map

**Comment by ashtat** [comment]
Awesome, I'm glad you got past the issue! Here's our documentation for acoustics baking in Unity. https://docs.microsoft.com/en-us/azure/cognitive-services/acoustics/unity-baking Typically you select the navmesh in the Unity hierarchy window and then mark it as acoustic mesh in the Objects tab of the Acoustics plugin.

**Comment by jaegrover** [comment]
Ah, thank you! I think some confusion on my behalf came from the phrasing of: "Navigation meshes that were created through the Unity workflow will be picked up by the Acoustics system" from that guide. Am I correct in assuming that meshes created in that way (i.e from the Bake button on the Navigation tab in Unity) will be detected automatically by Project Acoustics and do not need to be manually tagged?

**Comment by ashtat** [comment]
Yes, those will get detected automatically. The probe counts in your maps look reasonable. I'll file a bug on our end to address the spaces in the prefix issue, thanks for reporting it!

**Comment by jaegrover** [comment]
Thank you once again for the support :) 

I have been able to submit a bake of one of the larger maps to Azure. I'm just wondering, is it typical for it to take a long time for the bake to start? I began the bake around 3 hours ago, and I'm still seeing a "waiting for nodes to initialize" status. If you happen to see this and could let me know if that's typical, I'd be very appreciative. Once again, thanks for all of your support - trying my best to get this project up and running ASAP for the team, and it's a big help :)

**Comment by ashtat** [comment]
That's not typical, the bake should start fairly quickly. Could you share what Azure Batch compute configuration you're using (what VM size, number of nodes in the pool etc.)? Also, am I correct in assuming that your small test bake went through ok? It seems to me like your account quota may not have enough cores to process a large job. The total time for a bake depends on the number of compute nodes in the job's compute pool. Unfortunately, the default quota that comes with an Azure Batch account is not sufficient for realistic jobs. You typically need to request an increase in the quota for the account. Another thing to check, you can also visit portal.azure.com with your credentials and check if the job is getting the compute resources it needs.

**Comment by jaegrover** [comment]
Hi Ashtat, 

Just wanted to thank you again for your support. I think I'll create a separate thread for the other Azure issues to help keep things organized. I've been able to start a bake after increasing my quota, but am still getting unsatisfactory results. I'll reach out again tomorrow if I'm unable to resolve those issues. Thanks again for your assistance

**Comment by MikeChemi** [comment]
Closing this issue since it seems to have been resolved. Please open a new issue if you run into any more problems here.
