### ISSUE TITLE
Bake times extremely slow, even with 25 dedicated cores / paid Azure account

### ISSUE THREAD

**Issue by jaegrover** [microsoft/ProjectAcoustics#35]
Hi again, 

Thank you for the assistance thus far with getting Project Acoustics up and running. I wanted to check back in as I have submitted a build over 24 hours ago, for a level featuring ~3,000 probes. I upgraded my account to a paid account, and see that there are 25 dedicated nodes currently active and running. I have requested a further increase to my cores, but the request has been denied. For the first hour or so of the build, progress was very quick, completing ~2,000/6000 tasks within an hour or two. Then it suddenly slowed to a crawl and has been limping along every since. 

I'm just wondering if this is typical behavior. If not, would this be the correct forum to request assistance in resolving this issue? The project I'm working on features over 10 maps, several of which will likely have more probes than this (i.e. they are significantly larger/have more complex geometry) - I cannot imagine the team being satisfied with bake times of multiple days per level. Any assistance / advice would be highly appreciated. 

Thank you!

**Comment by nikunjragh** [comment]
The quick-slow behavior is as expected - Each simulation runs in two phases the first of which is quick. 

A couple recommendations:
- Use low-priority nodes as that will save you a lot of money (an integer factor). Our experience has been that there is not much difference in compute time although of course with low-pri you can get evicted. But good place to start for your first evaluations, as it is cost effective.
- The wall clock time will go down linearly with number of nodes, dollar cost remains same. (The nodes are just baking volumetric probes separately, its embarrassingly parallel). So max out your node allocation - up to number of probes. With your current allocation this will take about 60 hours, with 100 nodes that comes down to 15 hrs, and so on.

**Comment by nikunjragh** [comment]
Also - as a quick note, the bake cost is insensitive to geometric complexity/triangle counts. It scales (mostly) linearly with number of probes.

**Comment by AndersMalmgren** [comment]
@nikunjragh  I think the local bake is a bit more logical here, baking .dat and .enc in pairs.  Also it would eliminate questions like these :D

**Comment by kegodin** [comment]
Hi @jaegrover, we're happy to try to help, unfortunately the behavior you've seen is expected and the only solution is to get an increase in your Batch core quota. The default allocation is 25 cores which gets you only 1 16-core or 2 8-core nodes.

You mentioned that your quota increase request was denied. Unfortunately all I can suggest is to re-open the request and work with Batch support to address their reasons for denial. We have seen that requests for large quota increases (such as to thousands of cores) can require demonstrating the financial resources to cover large charges should the cores be occupied for a significant portion of a given billing period. The typical Project Acoustics use case only occupies the cores for a small period of time (one or a few hours) so such large charges are unlikely to result from using Project Acoustics. 

@ashtat @NoelCross Can you share some info on the process to get a quota increase, or a suggested quota increase request size that we have seen succeed in the past?

**Comment by jaegrover** [comment]
Hi folks, 

Thanks very much for your replies and support thus far. I have just noticed that the price for this initial bake is ~$500.00, which is admittedly higher than I had initially expected. Given the previous comments about cost scaling proportionally with the number of dedicated cores available, it now makes sense why my request for additional cores was denied. 

It looks like I did not have the "use low priority nodes" option checked when initially submitting the bake - it also seems that my Azure account does not currently list any low-priority nodes associated with my account. I will reach out to Batch support again today to attempt to remedy that issue, and will try a smaller bake using the low-priority option if possible. 

I guess I still feel like I'm missing something, and I apologize if I am asking anyone to repeat themselves. From the language in the PA instructional PDF, it seemed initially that one should expect a bake to take a few minutes - @kegodin, it also sounds like you're implying that PA bakes typically don't consume much cost / resources. Yet this bake, with what seems to me to be a relatively low dedicated node allocation and using one of our game's average-sized and less complex maps as a test case, is consuming several days, and several hundred dollars' worth of resources. I'm confused as to how this would be viable for smaller / indie developers - unless I've misinterpreted something, and this is a tool primarily aimed at projects with larger-scale / AAA production budgets, or I've simply missed something in my setup process. 

Thanks again for taking the time to walk me through this - I hope we can figure something out!

**Comment by kegodin** [comment]
Hi @jaegrover , thanks for sticking with us so far.

With a core quota increase your observed bake time (wall clock time) should decrease significantly. The workloads are parallelized by probe. With a core quota in the range of 2k cores, I'd expect you could complete a 3k probe bake in single-digit hours, much closer to the claims you see in our documentation.

As far as cost, as @nikunjragh mentioned above, cost scales linearly with probe count. We have generally seen that Azure Batch costs for low priority nodes are a fraction of regular prices; for example (https://azure.microsoft.com/en-us/pricing/details/batch/) in West US region the recommended F8 nodes have a low priority cost at 20% the cost of regular priority. Hypothetically, reducing the probe count to 1.5k and switching to low priority nodes would bring the cost to the $50 range.

To give you a sense of how we've calibrated the language in our documentation, 3k+ cores is among the largest maps we have heard of being baked with Project Acoustics, being larger than map sizes used in the AAA games that have shipped Project Acoustics so far. This map size is absolutely considered within the sizes we support. I am only stating this in the hope that it explains where our assumptions are coming from and the discrepancy between our documentation and your observations. Again, your use case is certainly supported by the tools.

Also, I'm not sure if I missed it or if you didn't mention - but if you're doing a 'fine' bake, one way to reduce cost and time significantly is to switch to a 'coarse' bake.

**Comment by nikunjragh** [comment]
Also, let me clear our some potential confusions here @jaegrover 

To summarize @kegodin's main point: With 3000 low-priority 8-core VMs (e.g., Standard_F8s_v2), *both* your USD cost and wall-clock bake time will reduce significantly. 

- Cost scaling
> Given the previous comments about cost scaling proportionally with the number of dedicated cores available, it now makes sense why my request for additional cores was denied.
Cost of baking a given map does _not_ scale with number of VMs allocated. It will cost much the same but will just go faster if you have more VMs. @kegodin was explaining why Batch requires paperwork to increase the quota.

- Cores vs "nodes"
In analogy to how a PC is 1 machine with many cores, in Azure, a VM (Virtual Machine) or "node" is like a machine, and each VM has some number of cores. Our baking time scales down with VMs. 

- Probe counts
3000 probes is on the higher side for a single bake, as Keith noted - AAA games manage by typically splitting the map by splitting nav mesh, doing multiple bakes. But for this map at least, you could try the simpler set of increasing the max probe sample spacing from the default 3.5m to 4 meters and see how that affects your probe count. If you're interested, we can point you towards how to adjust this. Also, for iterating, using coarse bakes as @kegodin recommended is a good step.

Let me note overall that our wish is one day users don't have to worry about such details, but this is how far we've gotten till now.

**Comment by jaegrover** [comment]
Thank you kindly :) Especially having worked with the traditional volumes/rooms and portals setup on a previous FPS project, which was functional but very cumbersome, I very much appreciate the work you've done to streamline the whole process. I also appreciate your patience helping out a user who is both a n00b to PA and to Azure. 

I will write back to Azure customer support about increasing my allocation of low priority nodes, as it seems I currently have no low priority nodes available on my Azure account. 

I will also be sure to speak with members of the dev team regarding options for splitting up the maps and scaling geometry to reduce probe count for each individual bake. 

Thanks again for all of your support thus far, and have a great day :)

**Comment by jaegrover** [comment]
In the meantime, @nikunjragh , if you could indeed point me to where to adjust the probe distancing / placement count, that would be awesome, at least to have it available for future experimentation. Thanks again!

**Comment by nikunjragh** [comment]
Sure, its discussed in Issue #25, quoted below:
> You can't place individual probes, but you can change the density. If you find the _AcousticsParamters asset in your hierarchy, you can change the density. For example, in the demo scene it is at Assets/AcousticsDemo/Editor/ProjectAcousticsDemo_AcousticsParameters. Viewing this asset's inspector window shows a bunch of different parameters. If you change the Probe Horizontal Spacing min/max values then redo the probe calculation, you should see the resulting probe density change (before you do another bake).

Tagging @MikeChemi who can comment if there were some other details to changing spacing in Unity. I'm suggesting changing the max spacing parameter, increase it from 3.5m.

**Comment by MikeChemi** [comment]
Nope, that's the useful one. Just want to stress that you should verify the correct spacing in-editor before baking again. I've personally adjusted the wrong parameter many times before and got stuck wondering why spacing didn't do the right thing.

**Comment by nikunjragh** [comment]
Also, we're continually optimizing our bake tools internally, @KyleStorck can tell you how to switch to new build for our bake tools that is about 1.4x faster. Fresh off the presses though, but its been working well in our tests.

**Comment by KyleStorck** [comment]
Hi @jaegrover. You can try out the faster bake tools by changing the "Toolset Version" to "mcr.microsoft.com/acoustics/baketools:1.2_Optimized"

![image](https://user-images.githubusercontent.com/1233941/77206749-f37e0000-6ab4-11ea-8b5e-5562b6789429.png)

**Comment by MikeChemi** [comment]
Latest bake tools include some optimizations, and the removal of the confusing "quick-slow" behavior. Closing this one out. #55
