### ISSUE TITLE
Error when building with UE4.24 and Wwise 2019.1/2

### ISSUE THREAD

**Issue by budgidiere** [microsoft/ProjectAcoustics#37]
I am using Wwise and Project acoustics as an engine plugin. When ever I build the engine I get these errors:
`0>e:\cgw2\Engine\Plugins\ProjectAcoustics\Source\ProjectAcousticsBakeUI\ProjectAcousticsBakeUI.Build.cs(88,9): Warning CS0618: 'UnrealBuildTool.ModuleRules.PublicLibraryPaths' is obsolete: 'For external libraries use the full path in PublicAdditionalLibraries, if its a system library then use PublicSystemLibraries/PublicSystemLibraryPaths'
0>e:\cgw2\Engine\Plugins\Wwise\Source\AkAudio\AkAudio.Build.cs(291,9): Error CS0103: The name 'AddWwiseLib' does not exist in the current context
0>e:\cgw2\Engine\Plugins\Wwise\Source\AkAudio\AkAudio.Build.cs(291,21): Error CS0120: An object reference is required for the non-static field, method, or property 'UnrealBuildTool.ModuleRules.Target'`

Does anyone know what I am doing wrong?

**Comment by NoelCross** [comment]
budgidiere, the latest public release was synchronized with UE4.22 and Wwise 2018.  There's a few changes necessary to support UE4.24 and Wwise 2019 which we are working on right now.  Hopefully we'll have some instructions on how to update the plugin source in the next day or two.

**Comment by MikeChemi** [comment]
I believe all of the changes required for this to work are in issue #28 . Give it a go and let us know if that works for you.

**Comment by budgidiere** [comment]
@MikeChemi I did all the fixes in #28 and i still get these errors/warnings:
`UnrealBuildTool : warning : Library 'E:\cgw2\Engine\Plugins\Wwise\Source\AkAudio\../../ThirdParty\x64_vc140\Profile\lib\AcousticsWwiseFx.lib' was not resolvable to a file when used in Module 'AkAudio', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
1>UnrealBuildTool : warning : Library 'Triton.Preprocessor.lib' was not resolvable to a file when used in Module 'ProjectAcousticsBakeUI', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
`
`1>E:/cgw2/Engine/Plugins/ProjectAcoustics/Source/ProjectAcoustics/Private/AcousticsAudioComponent.cpp(25): error C2065: 'bUseSpatialAudio': undeclared identifier
1>E:\cgw2\Engine\Source\Runtime\Core\Public\Core.h(6): warning : Monolithic headers should not be used by this module. Please change it to explicitly include the headers it needs.`
`>E:/cgw2/Engine/Plugins/Wwise/Source/AkAudio/Private/AkAudioDevice.cpp(3017): error C2039: 'SetEmitterObstructionAndOcclusion': is not a member of 'AK::SpatialAudio'
1>  E:\cgw2\Engine\Plugins\Wwise\ThirdParty\include\AK/SpatialAudio/Common/AkSpatialAudio.h(467): note: see declaration of 'AK::SpatialAudio'
1>E:/cgw2/Engine/Plugins/Wwise/Source/AkAudio/Private/AkAudioDevice.cpp(3017): error C3861: 'SetEmitterObstructionAndOcclusion': identifier not found`
`E:/cgw2/Engine/Plugins/ProjectAcoustics/Source/ProjectAcousticsBakeUI/Private/AcousticsAzureCredentialsPanel.cpp(10): fatal error C1083: Cannot open include file: 'SScrollBox.h': No such file or directory`
Hope that Helps!

**Comment by NoelCross** [comment]
For problem #1, modify ProjectAcousticsBakeUI.Build.cs with the following adds/deletes:
        const string DllName = "Triton.Preprocessor.dll";
+        const string LibName = "Triton.Preprocessor.lib";

        var configuration = "Release";
        var arch = "Win64";
        var thirdPartyDir = Path.GetFullPath(Path.Combine(ModuleDirectory, "../../ThirdParty/"));
-        var thirdPartyLibPath = Path.Combine(Path.Combine(thirdPartyDir, arch), configuration);
-        var tritonPreprocessorDllPath = Path.Combine(thirdPartyLibPath, DllName);
+        var tritonPreprocessorLibPath = Path.Combine(thirdPartyLibPath, LibName);

+        PublicAdditionalLibraries.Add(tritonPreprocessorLibPath);

For problem #2, modify AcousticsAudioComponent.cpp with the following edits:
 
#if AK_WWISESDK_VERSION_MAJOR < 2019 || (AK_WWISESDK_VERSION_MAJOR < 2019 && AK_WWISESDK_VERSION_MINOR < 2)
    bUseSpatialAudio = false;
#else
    bUseSpatialAudio_DEPRECATED = false;
#endif

For problem #3, modify the already patched AkAudioDevice.cpp with the following edit:

- #if AK_WWISESDK_VERSION_MAJOR == 2017
+ #if AK_WWISESDK_VERSION_MAJOR == 2017 || AK_WWISESDK_VERSION_MAJOR == 2019
            eResult = AK::SoundEngine::SetObjectObstructionAndOcclusion(emitterId, listenerId, in_ObstructionValues[0], in_OcclusionValues[0]);
#else // If Wwise 2018
            eResult = AK::SpatialAudio::SetEmitterObstructionAndOcclusion(emitterId, in_ObstructionValues[0], in_OcclusionValues[0]);
#endif

For problem #4, we haven't seen the issue you are seeing with AcousticsAzureCredentialsPanel.cpp.  Maybe regenerate the precompiled headers again and see if this is still a problem.  Otherwise, I don't know why SScrollBox.h is not getting included.

**Comment by budgidiere** [comment]
`1>------ Build started: Project: UE4, Configuration: Development_Editor x64 ------
1>Using 'git status' to determine working set for adaptive non-unity build (E:\cgw2).
1>Invalidating makefile for UE4Editor (ProjectAcousticsBakeUI.Build.cs modified)
1>UnrealBuildTool : warning : Library 'E:\cgw2\Engine\Plugins\Wwise\Source\AkAudio\../../ThirdParty\x64_vc140\Profile\lib\AcousticsWwiseFx.lib' was not resolvable to a file when used in Module 'AkAudio', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
1>Parsing headers for UE4Editor
1>  Running UnrealHeaderTool UE4Editor "E:\cgw2\Engine\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors
1>Reflection code generated for UE4Editor in 62.3597466 seconds
1>Building UE4Editor and ShaderCompileWorker...
1>Using Visual Studio 2019 14.25.28612 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610) and Windows 10.0.18362.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>[Adaptive unity build] Excluded from Engine unity file: PhysScene_Chaos.cpp
1>Building 12 actions with 12 processes...
1>  [1/12] Module.ProjectAcousticsBakeUI.cpp
1>E:/cgw2/Engine/Plugins/ProjectAcoustics/Source/ProjectAcousticsBakeUI/Private/AcousticsAzureCredentialsPanel.cpp(10): fatal error C1083: Cannot open include file: 'SScrollBox.h': No such file or directory
1>  [2/12] Module.ProjectAcoustics.cpp
1>E:\cgw2\Engine\Source\Runtime\Core\Public\Core.h(6): warning : Monolithic headers should not be used by this module. Please change it to explicitly include the headers it needs.
1>  [3/12] UE4Editor-ProjectAcoustics.lib
1>     Creating library E:\cgw2\Engine\Plugins\ProjectAcoustics\Intermediate\Build\Win64\UE4Editor\Development\ProjectAcoustics\UE4Editor-ProjectAcoustics.lib and object E:\cgw2\Engine\Plugins\ProjectAcoustics\Intermediate\Build\Win64\UE4Editor\Development\ProjectAcoustics\UE4Editor-ProjectAcoustics.exp
1>  [4/12] Module.AkAudio.cpp
1>  [5/12] UE4Editor-AkAudio.lib
1>     Creating library E:\cgw2\Engine\Plugins\Wwise\Intermediate\Build\Win64\UE4Editor\Development\AkAudio\UE4Editor-AkAudio.lib and object E:\cgw2\Engine\Plugins\Wwise\Intermediate\Build\Win64\UE4Editor\Development\AkAudio\UE4Editor-AkAudio.exp
1>  [6/12] UE4Editor-AkAudio.dll
1>LINK : fatal error LNK1181: cannot open input file 'E:\cgw2\Engine\Plugins\Wwise\Source\AkAudio\..\..\ThirdParty\x64_vc140\Profile\lib\AcousticsWwiseFx.lib'
1>  [7/12] UE4Editor-AudiokineticTools.dll
1>LINK : fatal error LNK1181: cannot open input file 'E:\cgw2\Engine\Plugins\Wwise\Source\AkAudio\..\..\ThirdParty\x64_vc140\Profile\lib\AcousticsWwiseFx.lib'
1>  [8/12] UE4Editor-ProjectAcoustics.dll
1>LINK : fatal error LNK1181: cannot open input file 'E:\cgw2\Engine\Plugins\Wwise\Source\AkAudio\..\..\ThirdParty\x64_vc140\Profile\lib\AcousticsWwiseFx.lib'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(44,5): error MSB3075: The command "..\..\Build\BatchFiles\Build.bat -Target="UE4Editor Win64 Development" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.
1>Done building project "UE4.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

I will try to see what is wrong with SScrollBox.h later but there are more errors. Hope this helps!

**Comment by MikeChemi** [comment]
Ah! You're linking against the vc140 tools, but we only populate the vc150 directory.

> 'E:\cgw2\Engine\Plugins\Wwise\Source\AkAudio\../../ThirdParty\x64_vc140\Profile\lib\AcousticsWwiseFx.lib'

If you need to link against vc140 for everything else, it is safe for you to manually copy the AcousticsWwiseFx.lib from the vc150 directories back to the vc140 ones.

**Comment by MikeChemi** [comment]
Getting close now! The Async error looks the same as #7

**Comment by budgidiere** [comment]
More errors:
```1>------ Build started: Project: UE4, Configuration: Development_Editor x64 ------
1>Using 'git status' to determine working set for adaptive non-unity build (E:\cgw2).
1>Waiting for 'git status' command to complete
1>Building UE4Editor and ShaderCompileWorker...
1>Using Visual Studio 2019 14.25.28612 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610) and Windows 10.0.18362.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>[Adaptive unity build] Excluded from Engine unity file: PhysScene_Chaos.cpp
1>Building 5 actions with 12 processes...
1>  [1/5] Module.ProjectAcousticsBakeUI.cpp
1>E:\cgw2\Engine\Source\Runtime\SlateCore\Public\SlateCore.h(10): warning : Monolithic headers should not be used by this module. Please change it to explicitly include the headers it needs.
1>  [2/5] UE4Editor-ProjectAcousticsBakeUI.lib
1>     Creating library E:\cgw2\Engine\Plugins\ProjectAcoustics\Intermediate\Build\Win64\UE4Editor\Development\ProjectAcousticsBakeUI\UE4Editor-ProjectAcousticsBakeUI.lib and object E:\cgw2\Engine\Plugins\ProjectAcoustics\Intermediate\Build\Win64\UE4Editor\Development\ProjectAcousticsBakeUI\UE4Editor-ProjectAcousticsBakeUI.exp
1>  [3/5] UE4Editor-ProjectAcousticsBakeUI.dll
1>     Creating library E:\cgw2\Engine\Plugins\ProjectAcoustics\Intermediate\Build\Win64\UE4Editor\Development\ProjectAcousticsBakeUI\UE4Editor-ProjectAcousticsBakeUI.suppressed.lib and object E:\cgw2\Engine\Plugins\ProjectAcoustics\Intermediate\Build\Win64\UE4Editor\Development\ProjectAcousticsBakeUI\UE4Editor-ProjectAcousticsBakeUI.suppressed.exp
1>Module.ProjectAcousticsBakeUI.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl FStaticMeshAttributes::FStaticMeshAttributes(struct FMeshDescription &)" (__imp_??0FStaticMeshAttributes@@QEAA@AEAUFMeshDescription@@@Z) referenced in function "private: void __cdecl SAcousticsProbesTab::AddVolumeToAcousticMesh(class AcousticMesh *,class AAcousticsVolume *,class TArray<unsigned int,class TSizedDefaultAllocator<32> > &)" (?AddVolumeToAcousticMesh@SAcousticsProbesTab@@AEAAXPEAVAcousticMesh@@PEAVAAcousticsVolume@@AEAV?$TArray@IV?$TSizedDefaultAllocator@$0CA@@@@@@Z)
1>Module.ProjectAcousticsBakeUI.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual void __cdecl FStaticMeshAttributes::Register(void)" (__imp_?Register@FStaticMeshAttributes@@UEAAXXZ) referenced in function "private: void __cdecl SAcousticsProbesTab::AddVolumeToAcousticMesh(class AcousticMesh *,class AAcousticsVolume *,class TArray<unsigned int,class TSizedDefaultAllocator<32> > &)" (?AddVolumeToAcousticMesh@SAcousticsProbesTab@@AEAAXPEAVAcousticMesh@@PEAVAAcousticsVolume@@AEAV?$TArray@IV?$TSizedDefaultAllocator@$0CA@@@@@@Z)
1>Module.ProjectAcousticsBakeUI.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl FStaticMeshAttributes::~FStaticMeshAttributes(void)" (__imp_??1FStaticMeshAttributes@@UEAA@XZ) referenced in function "private: void __cdecl SAcousticsProbesTab::AddVolumeToAcousticMesh(class AcousticMesh *,class AAcousticsVolume *,class TArray<unsigned int,class TSizedDefaultAllocator<32> > &)" (?AddVolumeToAcousticMesh@SAcousticsProbesTab@@AEAAXPEAVAcousticMesh@@PEAVAAcousticsVolume@@AEAV?$TArray@IV?$TSizedDefaultAllocator@$0CA@@@@@@Z)
1>E:\cgw2\Engine\Plugins\ProjectAcoustics\Binaries\Win64\UE4Editor-ProjectAcousticsBakeUI.dll : fatal error LNK1120: 3 unresolved externals
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(44,5): error MSB3075: The command "..\..\Build\BatchFiles\Build.bat -Target="UE4Editor Win64 Development" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.
1>Done building project "UE4.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by budgidiere** [comment]
Side note: You guys are really helpfully and this is the best support I've gotten from any repo I've ever used :)!

**Comment by NoelCross** [comment]
In ProjectAcousticsBakeUI.Build.cs, add the highlighted line:

        PrivateDependencyModuleNames.AddRange(
            new string[]
            {
                "CoreUObject",
                "Engine",
                "RenderCore",
                "Slate",
                "SlateCore",
                "InputCore",
                "UnrealEd",
                "LevelEditor",
                "EditorStyle",
                "Projects",
#if UE_4_20_OR_LATER
                "NavigationSystem",
#else
                "NavMesh",
#endif
                "RawMesh",
                **"StaticMeshDescription",**
                "Landscape",
                "DesktopWidgets",
                "PropertyEditor"
                // ... add private dependencies that you statically link with here ...
            }

**Comment by budgidiere** [comment]
```---------------------------
Message
---------------------------
Plugin 'ProjectAcoustics' failed to load because module 'ProjectAcousticsBakeUI' could not be loaded.  There may be an operating system error or the module may not be properly set up.
---------------------------
OK   
---------------------------```

The engine builds now but once I enable the plugin I get this error when loading. Is there any way I can get you some logs?

**Comment by NoelCross** [comment]
First, let's make sure that you have the DLL in the proper folder:

```
<ProjectName>\AcousticsGame\Plugins\ProjectAcoustics\Binaries\Win64

04/01/2020  09:07 PM           592,896 UE4Editor-ProjectAcoustics.dll
04/01/2020  08:34 PM         2,608,640 UE4Editor-ProjectAcousticsBakeUI.dll

```

Next, you can pull up the latest log in the <ProjectName>\AcousticsGame\Saved\Logs.  You might see some indication in this log about the load failure.

Otherwise, understanding the load failure would probably require loading UE in Visual Studio under the debugger and see if there are any error messages when attempting to load the DLL.

**Comment by budgidiere** [comment]
```Warning: ModuleManager: Unable to load module '[REDACTED]/Plugins/ProjectAcoustics/Binaries/Win64/UE4Editor-ProjectAcousticsBakeUI.dll' because the file couldn't be loaded by the OS.```

This is in the log file. The DLL files are in the correct directory.

Sorry for the very late reply. I had other things come up.

**Comment by NoelCross** [comment]
It is possible that one of the DLLs provided by Microsoft was blocked from loading on your PC. To fix this, inspect all DLLs in File Explorer at <your_game>\Plugins\ProjectAcoustics\ThirdParty\Win64\Release. Right click on a DLL and choose Properties. At the bottom of the properties window should be a checkbox that says "unblock." Click the unblock checkbox, hit OK.  Repeat this process for all of the files in the directory to remove the block. After completed, restart Unreal and see if the problem persists.

**Comment by budgidiere** [comment]
None of the files we're blocked.

**Comment by budgidiere** [comment]
I just found this error in the log. 
```[2020.05.03-14.43.36:673][  0]LogWindows: Failed to load 'E:/cgw2/Engine/Plugins/ProjectAcoustics/Binaries/Win64/UE4Editor-ProjectAcousticsBakeUI.dll' (GetLastError=126)
[2020.05.03-14.43.36:673][  0]LogWindows:   Missing import: Triton.Preprocessor.dll```

**Comment by budgidiere** [comment]
It seems like it's not looking in the ThirdParty folder for the DLL.

**Comment by NoelCross** [comment]
It appears that UE will dump out the search path during a failure to load DLLs.  It would be good to share more of the log if you can.

		if(bIncludeSearchPaths)
		{
			for (const FString& SearchPath : SearchPaths)
			{
				UE_LOG(LogWindows, Log, TEXT("  Looked in: %s"), *SearchPath);
			}
		}

Second, let's make sure that your ProjectAcousticsBAkeUI.Build.cs has the following code:

        const string DllName = "Triton.Preprocessor.dll";
        const string LibName = "Triton.Preprocessor.lib";

        var configuration = "Release";
        var arch = "Win64";
        var thirdPartyDir = Path.GetFullPath(Path.Combine(ModuleDirectory, "../../ThirdParty/"));
        var thirdPartyLibPath = Path.Combine(Path.Combine(thirdPartyDir, arch), configuration);
        var tritonPreprocessorDllPath = Path.Combine(thirdPartyLibPath, DllName);
        var tritonPreprocessorLibPath = Path.Combine(thirdPartyLibPath, LibName);

        PublicAdditionalLibraries.Add(tritonPreprocessorLibPath);

        PublicDelayLoadDLLs.Add(DllName);
#if UE_4_20_OR_LATER
        RuntimeDependencies.Add(tritonPreprocessorDllPath);
#else
        RuntimeDependencies.Add(new RuntimeDependency(tritonPreprocessorDllPath));
#endif

Lastly, if you are willing to send a link to a min repo, we could debug this on our end by stepping through the code.

**Comment by NoelCross** [comment]
I meant minimum "repro" of the issue, not min "repo".  :)

**Comment by budgidiere** [comment]
The ProjectAcousticsBakeUI.Build.cs did not match the code you provided so I updated it and now I can get into the editor and the Module UI works. Thanks for you help!
