### ISSUE TITLE
Basic acoustic simulation problem

### ISSUE THREAD

**Issue by joachimcnrs** [microsoft/ProjectAcoustics#38]
Hi everyone, I am new to Unity and I'm desperately trying to bake a wood acoustic simulation test but I clearly need some help :

I've just created a new scene with a terrain and a basic "cube house" made with 4 walls, 1 floor and 1 roof. I've then bake a Navigation Mesh and put the DemoSource object from the AcousticDemo inside the "cube house" (with the audioclip Voice activated). 

I've assign some wood material on the different parts of the house, opened the Window Acoustic, selected the different parts of the house and enable them in "Acoustic Geometry". 

Then I went to Materials, selected a wood vanished acoustic and finally went to probe to calculate a coarse simulation resolution. 

Finally i clicked on play mode to see if there was any voxels appearing on my scene but nothing even when i am close to the walls of the house. Then i've tried to bake the simulation, entered my Azure account code but Azure Bake Status is saying "Not submitted".

Any advice will be very appreciated... Thanks in advance.
Best,

Joachim

**Comment by kegodin** [comment]
Hi @joachimcnrs, the acoustics voxel display is enabled/disabled using Unity's Gizmos menu. Can you verify that the AcousticsProbes and AcousticsVoxels gizmos are enabled? See the screenshot here: https://docs.microsoft.com/en-us/azure/cognitive-services/acoustics/unity-baking#review-voxel-and-probe-placement

This should enable display of voxels and probes in the Scene window when not in Play mode. Voxels and probes are only shown in Play mode in the Game window after a successful bake.

**Comment by NoelCross** [comment]
The first thing to check is to see that you have Gizmos for AcousticsVoxels.  If you don't have this Gizmo on, then you won't see the voxels from the Calculate process in the Probes tab.

https://docs.microsoft.com/en-us/azure/cognitive-services/acoustics/unity-baking#review-voxel-and-probe-placement

On the bake tab, was the Bake button enabled and did you click on it?  If the probe calculation process failed, you shouldn't be able to submit a bake to Azure.

Also, best to keep a look out in the Console window to see if there are any errors that are being displayed during each step of the process.  Sharing that log would be helpful to understand if any errors occurred.

**Comment by joachimcnrs** [comment]
Hi and thanks for your time and answers ! 

Concerning the Gizmos for the AcousticsVoxels : it was well activated (like the AcousticsManager & AcousticsProbes) I was also careful to activate the bake of the NavigationMeshSurface before making the probe calculation process.

After I did the probe calculation process here are the messages appearing in the console : 

_Attempt to load preview data failed, so ignoring. Input string was not in a correct format.
UnityEngine.Debug:Log(Object)
Microsoft.Cloud.Acoustics.AcousticsEditor:Initialize() (at Assets/Acoustics/Editor/AcousticsEditor.cs:505)
Microsoft.Cloud.Acoustics.AcousticsEditor:OnGUI() (at Assets/Acoustics/Editor/AcousticsEditor.cs:315)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)_

_Default materials loaded. Number of entries in material library: 47
UnityEngine.Debug:Log(Object)
Microsoft.Cloud.Acoustics.AcousticsEditor:Initialize() (at Assets/Acoustics/Editor/AcousticsEditor.cs:442)
Microsoft.Cloud.Acoustics.AcousticsEditor:OnGUI() (at Assets/Acoustics/Editor/AcousticsEditor.cs:315)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)_

_FormatException: Input string was not in a correct format.
System.Number.ParseDouble (System.String value, System.Globalization.NumberStyles options, System.Globalization.NumberFormatInfo numfmt) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Double.Parse (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Double.Parse (System.String s) (at <437ba245d8404784b9fbab9b439ac908>:0)
Microsoft.Cloud.Acoustics.ComputeCostPredictor.InitializeCostBasis (System.String costsheet, Microsoft.Cloud.Acoustics.SimulationConfiguration& costBasisConfiguration, System.Collections.Generic.List`1[Microsoft.Cloud.Acoustics.ComputeNodeCostInformation]& nodeCosts) (at <81f508e053f048a59a07e00307dfbdc1>:0)
Microsoft.Cloud.Acoustics.ComputeCostPredictor.EstimateProcessingTime (System.String costsheet, Microsoft.Cloud.Acoustics.SimulationConfiguration target, Microsoft.Cloud.Acoustics.ComputePoolConfiguration pool) (at <81f508e053f048a59a07e00307dfbdc1>:0)
Microsoft.Cloud.Acoustics.CloudProcessor.EstimateProcessingTime (System.String costsheet, Microsoft.Cloud.Acoustics.SimulationConfiguration targetConfiguration, Microsoft.Cloud.Acoustics.ComputePoolConfiguration targetPool) (at <81f508e053f048a59a07e00307dfbdc1>:0)
Microsoft.Cloud.Acoustics.AcousticsEditor.UpdateComputeTimeEstimate () (at Assets/Acoustics/Editor/AcousticsEditor.cs:1696)
Microsoft.Cloud.Acoustics.AcousticsEditor.DisplayPreviewResults () (at Assets/Acoustics/Editor/AcousticsEditor.cs:1638)
Microsoft.Cloud.Acoustics.AcousticsEditor.Update () (at Assets/Acoustics/Editor/AcousticsEditor.cs:189) 
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <437ba245d8404784b9fbab9b439ac908>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <437ba245d8404784b9fbab9b439ac908>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at <78f1ad0f25c84e3ca853e639f50d95f5>:0)
UnityEditor.HostView.Invoke (System.String methodName) (at <78f1ad0f25c84e3ca853e639f50d95f5>:0)
UnityEditor.HostView.SendUpdate () (at <78f1ad0f25c84e3ca853e639f50d95f5>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <437ba245d8404784b9fbab9b439ac908>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <437ba245d8404784b9fbab9b439ac908>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at <78f1ad0f25c84e3ca853e639f50d95f5>:0)
UnityEditor.HostView.Invoke (System.String methodName) (at <78f1ad0f25c84e3ca853e639f50d95f5>:0)
UnityEditor.HostView.SendUpdate () (at <78f1ad0f25c84e3ca853e639f50d95f5>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <437ba245d8404784b9fbab9b439ac908>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Delegate.DynamicInvokeImpl (System.Object[] args) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Delegate.DynamicInvoke (System.Object[] args) (at <437ba245d8404784b9fbab9b439ac908>:0)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <78f1ad0f25c84e3ca853e639f50d95f5>:0)_

Thanks again for your help.
Best,

Joachim

**Comment by AndersMalmgren** [comment]
I guess you have none US culture on your OS. I had same problem.

**Comment by joachimcnrs** [comment]
That was exactly my problem thanks a lot @AndersMalmgren ! 

However, I still have a problem concerning the final baking process because Azure Bake Status is now saying _Waiting for the nodes to initialize_ could it also be a problem with the region attached to my Batch account?

**Comment by AndersMalmgren** [comment]
you only have 20 vCPU default and no low prio ones. So if you have ticked low prio mode it will never start proccesing. And if you do not tick low prio nodes it will use maximum of 2 8 core nodes (16 vCPU) I have 256 low prio nodes

**Comment by joachimcnrs** [comment]
Alright thanks but then is it possible to buy some vCPU with the Free Trial Microsoft Azure Batch Account ?

**Comment by AndersMalmgren** [comment]
You will need a pay as you go account but the free amount will be transfered over, problem for me was that the trial period was over before azure granted me the CPUs

**Comment by AndersMalmgren** [comment]
I would recommend to play around in small scenes with local bake

**Comment by joachimcnrs** [comment]
Alright then thanks again for your help !

**Comment by kegodin** [comment]
Thanks @AndersMalmgren ! The 'culture' setting issue is covered by issue #2 . Closing this issue as a duplicate. @joachimcnrs , please don't hesitate to open additional issues or to reopen this issue if your problems haven't been resolved.
