### ISSUE TITLE
Crashes when importing into Unity-based project re: .JSON and Unsafe.dll files

### ISSUE THREAD

**Issue by jaegrover** [microsoft/ProjectAcoustics#40]
Hi again folks, hope everyone is doing well. 

I recently attempted to import Project Acoustics into a Unity-based project for a dev team I'm working with. During the initial import process, I experienced a hang at Importing (Iteration 2 - Acoustics\MicrosoftAcoustics.prefab). After closing out of Unity via the Task Manager and reloading the project file, I noticed some errors in the console, including the following: 

PrecompiledAssemblyException: Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included for the current platform. Only one assembly with the same name is allowed per platform. Assembly paths: Assets/Acoustics/Editor/Plugins/Windows/Newtonsoft.Json.dll, Assets/ThirdPartyTools/Photon/PhotonUnityNetworking/Code/Editor/Newtonsoft.Json.dll

Our code team informed me that our project already contains a version of Newtonsoft.Json.dll, that came with Photon Unity Networking. They recommended that I omit the .dll from the Project Acoustics import. 

I was then able to import PA without crashing; however, my editor log then displayed the following error message: 

Library\PackageCache\com.unity.collections@0.0.9-preview.12\Unity.Collections\UnsafeUtilityEx.cs(8,24): error CS0433: The type 'Unsafe' exists in both 'System.Runtime.CompilerServices.Unsafe, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Code staff once again suggested that I omit System.Runtime.CompilerServices.Unsafe from the PA import. 

However, I am now experiencing a crash if attempting to import Project Acoustics with those two files omitted - once again, during the stage where MicrosoftAcoustics.prefab is being imported. CPU usage jumps up to ~50%, and memory up to 97%, during this time. 

I will continue exploring solutions with the team, but in the meantime, would you folks be able to shed some light on what these files are used for? Would you recommend attempting to merge them with our local files? 

Thanks in advance for any insight you can offer, and have a great day :)

**Comment by jaegrover** [comment]
Clarification - if I just omit the .JSON file from the import, the import appears to go smoothly, i.e. no crash, though I do get the Console warning about CompilerServices.Unsafe. Previously, deleting that file from the Project Acoustics directory, post-import, and leaving the other CompilerServices.Unsafe as-is, allowed us to get PA up and running in-game, so perhaps I'm being overly cautious. However, I was experiencing a fairly high-repro issue where all audio was cutting out during loud combat scenes / during burst-fire of certain weapons - part of what I'm attempting to do at the moment is a clean install in a verified-stable branch to narrow down what may have been causing that drop-out issue.

**Comment by kegodin** [comment]
Hi @jaegrover , great to hear that you like how PA sounds :)

The required amount of RAM will depend on scene size. We haven't encountered many scenes that are pushing required RAM past 16GB but it's not out of the question.

I want to make sure I follow the thread of your experience here - are the issues resolved after increasing the RAM in your machine? Is there an audio dropout issue you're still investigating?

**Comment by jaegrover** [comment]
Hi there, 

I'm sorry for the somewhat sporadic nature of this post. 

Essentially, we were initially experiencing a crash on my machine when trying to load PA into our own project. My memory consumption shot up to 100%, causing a hang, and then a crash during import. By upgrading from 16GB to 32GB of RAM, I was able to avoid that issue. 

Next, we had some difficulties with the compiler, as Unity was upset that we were bringing in a .JSON file and the Unsafe.dll file from PA, when we already had assets in our project with identical names. Ultimately, we were able to find a workaround for that as well. 

If you think this issue will be helpful to others, please feel free to leave it here, otherwise I'd be happy to have it closed or to close it myself. 

Regarding the audio drop-out issue - I was previously experiencing an issue where playing several loud sounds in close succession and close proximity would result in a loud "Pop" (sounded like a zero crossing in a bad looping file), then all audio in the build would drop out. The mixer to which we had assigned the Project Acoustics effect in Unity reported no active signal input. However, my capture software (OBS) registered the audio channel as maxing out / clipping. My guess was that there was a feedback loop somewhere at it was triggering a limiter / failsafe and killing the default mixer, or something like that. 

Of note was that when Suiciding and respawning in an area in the same map, removed from the main playspace, SFX would return. However, upon returning to the main playspace, the POP would be heard again, and all audio would cut out once more. If exiting Unity while the audio was Cut Out, I'd hear a very brief sample of the expected audio (e.g. gunfire) playing, if the sounds were coming e.g. from a looping emitter in the main play space, then all audio would cease as the editor fully shut down. 

It occurred to me that our initial import of PA hadn't followed best practices. When we encountered the aforementioned crash, we quickly worked around it to be able to get some test cases of PA in our engine up as soon as possible. The recent import issues were experienced in a separate, "clean" branch, during an attempt at a "proper" PA import. 

At this point, I'm planning to proceed with testing in our new branch as the import has succeeded. I am happy to create a second bug for the popping issue if I run into that again, but I'm currently unable to repro it. 

It may be worth noting that people with projects already having .JSON or Unsafe.dll files in their build may experience conflicts when merging in PA. Our solution was ultimately to delete the .JSON files in our build (associated with Steam VR), then delete the Project Acoustics Unsafe.dll after the import, and use "ours" instead. 

I hope that helps :) Thanks again for your time

Thanks for your time and support.

**Comment by jaegrover** [comment]
Quick update - the audio cut out / popping issue is still happening in the "new" branch. Additional info: 
-Audio is heard correctly at runtime
-The player initially loads into a "ready tent" outside of the gamespace where navmesh and, consequently, acoustic probes, have not been built
-At this time, the main camera is a static camera that is relegated to this ready tent
-After choosing a loadout (the title is a VR FPS), the player is "teleported" to the main play area (it may be that we're just switching cameras rather than actually changing the transform of the player pawn)
-The player can move around the game map and hear ambient sounds
-The player can fire a few shots from a weapon and hear the individual sounds correctly
-When holding down the trigger to fire an automatic weapon, after ~10 rounds of fire, all audio will cut out of the build with the aforementioned "POP"
-This has also been observed occurring when e.g. turning on many Audio Source objects with loud looping assets playing concurrently
-This behavior is only observed when Project Acoustics is set as the Spatializer Plugin in Unity
-System Sample Rate is set to 0; Virtualize Effects is ON; NO Ambisonic Decoder plugin is active; DSP Buffer Size is set to Best Performance

I'll continue to investigate this morning

**Comment by jaegrover** [comment]
I'm going to close this issue down for the time being because I realize it's just become too verbose and confusing at this point - started off being a concern about duplicate file types and has now become a divergent issue about audio popping out. Feel free to leave this up for posterity if you think it would be helpful, or to delete it otherwise. I'll be looking out for a more solid repro as I continue testing this week and will open a more concise issue if I manage to track it down. Thanks again in the meantime :)

**Comment by kegodin** [comment]
Thanks @jaegrover, we'll be here on the forums so let us know if any issues come up and whether you have a consistent repro for the audio popping problem.
