### ISSUE TITLE
Fellow devs cant build branch after I have merged acoustics into it

### ISSUE THREAD

**Issue by AndersMalmgren** [microsoft/ProjectAcoustics#43]
Hi, this is a strange problem. I have pushed our project acoustics branch to our main dev branch. And my fellow devs cant build now. They get

![image](https://user-images.githubusercontent.com/817577/97103455-e6f60180-16ac-11eb-98ae-49ed450b1efe.png)

It works fine for me. We are all on Unity 2019.4.13 and same project settings (.NET 4.x etc)

**Comment by MikeChemi** [comment]
This sounds like either a missing csc.rsp file, or some other issue with it. The acoustics plugin ships with a csc.rsp file, with the following line:
-r:System.Security.dll

Can you confirm that made it into your main dev branch?

**Comment by AndersMalmgren** [comment]
Found it, its not checked in, only on my branch! Nice catch!
