### ISSUE TITLE
Where is the C API?

### ISSUE THREAD

**Issue by Leadwerks** [microsoft/ProjectAcoustics#44]
Where is the API for people who want to program with this directly?

**Comment by MikeChemi** [comment]
Hi @Leadwerks, we don't currently have a package for only the C API, however depending on which pieces you're interested in I may be able to get you started with something. Are you interested in the acoustics system, or the audio rendering system, or both?

**Comment by takapart** [comment]
> Hi @Leadwerks, we don't currently have a package for only the C API, however depending on which pieces you're interested in I may be able to get you started with something. Are you interested in the acoustics system, or the audio rendering system, or both?

I'm interested in both.

**Comment by NoelCross** [comment]
It would be great to have a deeper conversation about your needs and to explore the room for collaboration.  Would it be possible for you to send an email to noelc@microsoft.com so that we can schedule a meeting to talk more in depth?  Thanks!

**Comment by Leadwerks** [comment]
Email sent, thanks.
