### ISSUE TITLE
Fail to create new Material Library - Unity

### ISSUE THREAD

**Issue by LeGabee** [microsoft/ProjectAcoustics#45]
Hi!, I import the package into my unity project (I tested in Unity 2020.11.16f1 and 2019.4.14f1) no problem at all, but when I open the window of Acoustics, the console give me this error, over and over again.

`InvalidOperationException: Failed to create new Material Library 
Triton.MaterialLibrary.Create (System.String materialDataFileName)`

So the acoustics window, doesn't show anything and the error apper over and over again.
I'm using Windows 10. I don't know if more info it's need it.

I tried to create blank sessions or tested in others unity's version, but nothing works, I'll be glad if somebody could help me.

Thanks for reading.

**Comment by KyleStorck** [comment]
Hi @LeGabee . Can you first confirm if the file "DefaultMaterialProperties.json" is located in the "Assets\Acoustics\Editor" directory, alongside AcousticsEditor.cs?

**Comment by LeGabee** [comment]
Yes, both files are in the same directory.

**Comment by KyleStorck** [comment]
Are you seeing this error while viewing the Project Acoustics sample scene, or a scene of your own, or an empty scene?

**Comment by LeGabee** [comment]
I tried in multiples scenes, incluying the demo scene and an empty scene, but error appear as long i click the window acoustics, which is empty.

![imagen](https://user-images.githubusercontent.com/76458739/102924746-ec838400-4470-11eb-8c87-cece08a882b1.png)

And the same error appear over and over again

**Comment by KyleStorck** [comment]
I want to confirm the path being used one more time. Inside AcousticsEditor.cs, could you add the following debug line right before the call to Triton.MaterialLibrary.Create (on line 433). Can you reply back with the path that is returned in the console, and check if that is a valid path on your computer.

                    Debug.Log("Material path: " + materialsPropertiesFile);

![image](https://user-images.githubusercontent.com/1233941/102930447-483e1500-4451-11eb-8d70-1a2ceee622fb.png)
![image](https://user-images.githubusercontent.com/1233941/102930888-2d1fd500-4452-11eb-823e-1dc81873e482.png)

**Comment by LeGabee** [comment]
Ok, so I added the line, and I think the path it's ok, it's the directory where I saved the Unity Project.

![imagen](https://user-images.githubusercontent.com/76458739/102932966-13958200-4480-11eb-84aa-a633ee37e9df.png)

**Comment by KyleStorck** [comment]
Ok, I was able to reproduce your error. I believe the problem has to do with directories that contain a tilde in your project directory ("Año" and "Señales"). Looks like our plugin errors on those characters. To unblock you for now, please try again in a project directory that contains no tildes.

**Comment by LeGabee** [comment]
Ok soooo that was the error, I fell betray by the Ñ, hahaha.
The window of acoustics has no error now. Thank you very much for your help.

**Comment by KyleStorck** [comment]
Happy to help. Thanks for contacting us.

Tracked internally with ADO bug # 31151246
