### ISSUE TITLE
VM support for Dv3 Series

### ISSUE THREAD

**Issue by MicalKarl** [microsoft/ProjectAcoustics#48]
I am using an Azure Student account, and I found that only Dv3 Series VM can not be used. When I submit the bake job, azure indicates that "The specified account has reached core quota". Can this project support  Dv3 Series?

**Comment by MikeChemi** [comment]
Hi @MicalKarl 
This project can be used on the Dv3 series, but you'll need to modify the plugin code to schedule against Dv3 instead of the provided F/H options. For Fine-resolution bakes, you'll want to use at least the D4v3 SKU to ensure you have enough RAM for the compute.

**Comment by MicalKarl** [comment]
> Hi @MicalKarl
> This project can be used on the Dv3 series, but you'll need to modify the plugin code to schedule against Dv3 instead of the provided F/H options. For Fine-resolution bakes, you'll want to use at least the D4v3 SKU to ensure you have enough RAM for the compute.

Thanks for your answering, it did works.
