### ISSUE TITLE
Voxels only show the most outer one

### ISSUE THREAD

**Issue by MicalKarl** [microsoft/ProjectAcoustics#49]
I build my scene voxels follow the sample project intructions, but I can only see  the voxel in the most outside (the green line in the picture), and the house has no voxels displayed at all. How is that happened?
![image](https://user-images.githubusercontent.com/20335439/109450398-c2a89800-7a85-11eb-962d-cd9f6353af9c.png)
Here is the editor log.

```
LogAcoustics: Display: Starting geometry voxelization...
LogAcoustics: Display: Metadata for voxels read from disk is NOT consistent. Recomputing mesh voxelization.
LogAcoustics: Display: ---VOXELIZE SCENE---
LogAcoustics: Display: Voxelization bbox: (-196.26, -107.15, -17.51) - (100.05, 107.56, 39.1) meters
LogAcoustics: Display: Voxel map resolution: [ 581, 421, 111 ]. Total: 27150711
LogAcoustics: Display: Rescaling mesh for voxelization and clearing voxel map.
LogAcoustics: Display: Performing voxelization using 8 parallel tasks...
LogAcoustics: Display: Voxelizing mesh triangles: [51405/51405]: Done.
LogAcoustics: Display: Coarse level -- Wall voxels: 185030, Air voxels: 26965681
LogAcoustics: Display: Fine level wall voxels (approx.): 3827444. Write-cache avoided #overwrites = 52985947
LogAcoustics: Display: SUCCESS: Voxelization done in 0:01
LogAcoustics: Display: ---VOXELIZE NAVIGABLE AREA---
LogAcoustics: Display: Voxelization bbox: (-196.26, -107.15, -17.51) - (100.05, 107.56, 39.1) meters
LogAcoustics: Display: Voxel map resolution: [ 581, 421, 111 ]. Total: 27150711
LogAcoustics: Display: Rescaling mesh for voxelization and clearing voxel map.
LogAcoustics: Display: Performing voxelization using 8 parallel tasks...
LogAcoustics: Display: Voxelizing mesh triangles: [23613/23613]: Done.
LogAcoustics: Display: Coarse level -- Wall voxels: 94747, Air voxels: 27055964
LogAcoustics: Display: Fine level wall voxels (approx.): 104039. Write-cache avoided #overwrites = 792760
LogAcoustics: Display: SUCCESS: Voxelization done in 0:00
LogAcoustics: Display: Pass 4: Done. Filled 0 voxels.
LogAcoustics: Display: ---Optimizing voxel map.---
LogAcoustics: Display: SUCCESS: Optimization done. Safely cleared 57% of the voxel map
Job input voxel data to: AudioTest_AcousticsData.vox, cell size = 0.510000
LogAcoustics: Display: SUCCESS: Wrote Voxel metadata/data to: AudioTest_AcousticsData.vox
LogAcoustics: Display: SUCCESS: Success. Wrote config file: AudioTest_AcousticsData_config.xml and voxel file: AudioTest_AcousticsData.vox
```

**Comment by MikeChemi** [comment]
@MicalKarl the voxels are only displayed within a certain radius around the camera / viewport. Try moving around the scene and looking at the geometry closest to you. Do the voxels show up?

The drawable radius is a constant defined in AAcousticsDebugRenderer::RenderVoxels. You can try increasing this value, although it will decrease the editor's responsiveness the larger it gets.

**Comment by MicalKarl** [comment]
@MikeChemi I already done as you said, and I also enable draw Voxel in the acoustics space actor's setting. No matter how near I get close, the voxels do not show in the scene either in editor or running in game, I can see only the blue probes. But the head UI shows the outdoorness is decreasing when I getting close in a room (does it means that the voxels do exist?). Here is the pictures.
![image](https://user-images.githubusercontent.com/20335439/109904984-0d6e1e00-7cd9-11eb-9ede-222dfde48f5c.png)
![image](https://user-images.githubusercontent.com/20335439/109905224-6fc71e80-7cd9-11eb-98b8-61ee650d3167.png)
![image](https://user-images.githubusercontent.com/20335439/109905344-97b68200-7cd9-11eb-9b30-3dfc1f03b7be.png)

**Comment by MicalKarl** [comment]
@MikeChemi And I got error hint when I place an acoustics source in the scence, is anything wrong?
![image](https://user-images.githubusercontent.com/20335439/109922668-b1b38d00-7cf8-11eb-96f4-701f6651f80e.png)

**Comment by MikeChemi** [comment]
Looks like there's a couple issues here. Let's start with the voxels first.

There are two different display mechanisms for voxels and probes. After you calculate probes in the acoustics mode, you get an AcousticsDebugRenderer in the scene. This is the thing in your first screenshot, and the probes/voxels rendering there is only valid outside of play-in-editor mode. I think this is probably already set since you have probes showing up, but make sure the viewport has realtime mode enabled. If you're still not seeing voxels outside of play mode, try deleting the AcousticsDebugRenderer, closing the Acoustics mode tab, then reopening the acoustics mode tab and re-enabling Draw Voxels on the AcousticsDebugRenderer. Sometimes the state can get out of sync.

For Play-In-Editor voxels, you'll want to go to the AcousticsSpace object. Before entering play mode, go to the debug controls and enable Draw Voxels there.

**Comment by MikeChemi** [comment]
For the second issue, yes the red text indicates a problem. It looks like your sound source is inside a wall voxel. Try moving your sound source a little bit so that it's not inside of the scene's geometry.

**Comment by MicalKarl** [comment]
@MikeChemi For the firtst issue, I recaculate to voxels, then the problem is solved. For the second, it's really the soud source is inside the voxel.
