### ISSUE TITLE
Wave visualization in game

### ISSUE THREAD

**Issue by bouiz** [microsoft/ProjectAcoustics#50]
Hi everyone,

I was wondering if there would be a way to see the waves propagation in the built environment, or any kind of acoustics visual output (decaytime graphs, reverberance graphs, etc.) ?
Either as dynamic outputs like the .gif shown at the frontpage of Project acoustics, or static graphs of the acoustics informations ?

![wave-simulation](https://user-images.githubusercontent.com/48626073/109618407-cc8ad380-7b37-11eb-848b-5c59267d400f.gif)

I am using Project Acoustics on Unity, and am trying to implement it in my architecture design practice, to open up this powerful tool from game industry to architecture practice. As my graduation project at Architecture University of Paris-Malaquais (France).

**Comment by MikeChemi** [comment]
Hi @bouiz ! Thanks for using Project Acoustics. At this time, we do not have those visualizations available in any of our public offerings.

**Comment by bouiz** [comment]
Ok i see, Thanks !
