### ISSUE TITLE
The white line from audio to player does not draw

### ISSUE THREAD

**Issue by MicalKarl** [microsoft/ProjectAcoustics#52]
I integrate the plugin in a new project, but I found no white lines drawed from audio soucres to the player. Here is the correct sample. How to enable drawing the white lines, or something is wrong?
![image](https://user-images.githubusercontent.com/20335439/111281038-78273e00-8677-11eb-8c67-7add43be5946.png)

**Comment by MikeChemi** [comment]
Can you verify that:

- You have baked the space and can see the voxels/probes from the ACE displayed on the scene
- You have the "Show Acoustic Parameters" checkbox checked on the acoustics audio component

**Comment by MikeChemi** [comment]
Closing from lack of activity, please let us know if you're still having issues with the latest version
