### ISSUE TITLE
Camera.main is slow and shouldnt be used from a hot loop

### ISSUE THREAD

**Issue by AndersMalmgren** [microsoft/ProjectAcoustics#53]
Hi.
Camera.main calls unmanaged equivalent of FindByTag("MainCamera") internally which is very slow. Maybe a better is to cache camera and let user override this cached reference. 

edit: also calling GetComponent<AudioSource>() from AcousticsAdjust.Update can be a potential perfomance problem with many AcousticsAdjusts in the scene

**Comment by MikeChemi** [comment]
These are really good callouts, thanks Anders. We'll add these improvements to our backlog.

**Comment by MikeChemi** [comment]
Fixed in version 2.0 #55
