### ISSUE TITLE
Project Acoustics 2.0 now available!

### ISSUE THREAD

**Issue by MikeChemi** [microsoft/ProjectAcoustics#55]
We're happy to announce that a new version of Project Acoustics is available! It includes many bug fixes and new features. The documentation has been updated at http://aka.ms/acoustics with information about new features and beta features. Here's a few highlights:

- Faster bake times and support for larger map sizes
- Unreal Engine:
  - Increased control over probe layout with manual probe placement
  - More control over acoustics metadata with additional probe volumes
- Unity plus Wwise Integration Beta
- Various bug fixes and performance improvements

We'll be publishing a blog in the coming weeks with more information about all the new features. You can find version 2.0 from the links below. Thanks for using Project Acoustics!

Unity: https://www.microsoft.com/en-us/download/details.aspx?id=57346
Unreal with Wwise integration: https://www.microsoft.com/en-us/download/details.aspx?id=58090

**Comment by eefan000** [comment]
I tested the doorsgym level and found that there was no sound dynamic occlusion effect when the door moved

**Comment by KyleStorck** [comment]
Hi @eefan000. Try turning on "Apply Dynamic Openings" on the AcousticsAudio component within AudioHolder. That value is opt-in for new Dynamic Opening components and is false by default in the sample scene.
![image](https://user-images.githubusercontent.com/1233941/119504742-1d6a2c80-bd21-11eb-87f2-65b7e4c266c7.png)

**Comment by eefan000** [comment]
After testing the baking time, I feel that it is too slow. In our scene, there may be 3500 probes, and it takes 800 seconds for one probe to operate on an 8-core CPU.

Is there a plan to support GPU acceleration

**Comment by NoelCross** [comment]
@eefan000, while GPU acceleration would be great to have for the simulation task, we do not have GPU acceleration support at this time.  Each of the 3500 probes is a task that can be assigned to a different compute node to greatly reduce the overall time for a complete bake.  This is why the preferred baking mechanism is using Azure Batch to run many simulations in parallel.
