### ISSUE TITLE
Calculation issue

### ISSUE THREAD

**Issue by onaccident** [microsoft/ProjectAcoustics#6]
Hey Noel!

I ran into an issue with a bake that I'm really struggling to solve on my own. In order to try out the tool, I downloaded a VR capable project in unity, viking village. I got the integration together no prob, and even did a little bake. I found out though that I had only selected one "house" in the village so the probes weren't populating correctly. No big, just run a new bake, I thought. Selecting the entire project, however, is 1500 navigation and 1500 geometry. I didn't think this would be an issue, but when I do the pre bake it gets stuck at "calculating probe locations" or "generating scene diameter measures" below. I even left it overnight to calculate and no go, it's hard stuck. I don't know if I should be only selecting part of the scene, but if so, how do I have multiple acoustics bakes in one project?

Thanks for any help!
Megan

**Comment by ashtat** [comment]
Hi Megan, 

Thanks for trying out Project Acoustics and reporting the issue! It sounds like the scene is generating way too many probes. I'll give this scene a try on my end and see if I can reproduce the issue and suggest a solution. 

Stay tuned!
Ashu

**Comment by onaccident** [comment]
Definitely! Thanks for getting back to me so soon, look forward to hearing
from you.

If you need screen shots the demo I'm working on internally isn't
confidential, I should be able to work with ya.

**Comment by ashtat** [comment]
Hi Megan, I'm assuming you are using the Viking Village scene from the asset store? It's a pretty large scene but I was able to do the bake precalculation by -
1. Scoping the acoustic navigation to "terrain_near_01" mesh which is essentially the terrain under the village itself. 
2. Adding all meshes under "Buildings" and "Props" as acoustic mesh. 

It took about 8 minutes to compute 1330 probes on my machine. 

![image](https://user-images.githubusercontent.com/13240863/69456805-6c946300-0d20-11ea-8a0d-83304839d8c2.png)

![image](https://user-images.githubusercontent.com/13240863/69456828-803fc980-0d20-11ea-8fdb-2e2031f9dd51.png)

**Comment by onaccident** [comment]
Hiya Ashu!

Ok, scoping it out correctly is the ticket to getting the probes calculated
as you described.

I'm curious however how you are getting a bake done in ~8 minutes? I got a
reasonably powerful machine and we're probably looking at a couple hours,
maybe overnight? I'm currently trying to calculate 2125 probes (so more)
but no where near that fast. Ill I selected was Props and Buildings for
scoping, if that helps.

Thanks for your response!!!!
Megan

**Comment by ashtat** [comment]
Sorry about the confusion! The processing has two phases-- the first  phase computes acoustics probe placements for the scene, the second phase performs the actual bake which computes the full simulation for each probe. I meant the first phase of probe calculation took about 8 minutes. I did not do an actual bake which of course will take much longer. The bake tab provides an estimated duration for the bake.

**Comment by onaccident** [comment]
Haha, that makes so much more sense! Thanks! I'll reply in the git on
Monday with the solution if you haven't already, thanks again for your help.
