### ISSUE TITLE
Support for PlayStation 4/5?

### ISSUE THREAD

**Issue by jaegrover** [microsoft/ProjectAcoustics#63]
Hi folks, hope all is well!

Sorry if this has been mentioned elsewhere, but I noticed that the [Project Acoustics Overview](https://docs.microsoft.com/en-us/gaming/acoustics/what-is-acoustics) page doesn't currently list PS4/5 under Runtime Platforms. Just wondering if someone could please confirm that PA is not supported on PlayStation at this time - and, if so, are there plans to port it over sometime within e.g. the next year? 

Thanks in advance, and best wishes :)

**Comment by NoelCross** [comment]
Jonathan,

We don't ship binaries for PlayStation at this time.  Partners who have signed the GDK source license agreement [addendum](https://docs.microsoft.com/en-us/gaming/acoustics/what-is-acoustics#source-access) have obtained access to the source code and have made minimal modifications to the build scripts to build PA using the Sony SDK.  If you are working with a studio and they have a Microsoft Gaming representative, you can request the addendum to get access to the code and build for your platform of choice.

Thanks,
Noel Cross
Microsoft Corporation

**Comment by MikeChemi** [comment]
The GDK route is our only method for PS support at this time.
