### ISSUE TITLE
UE5/MetaSound

### ISSUE THREAD

**Issue by Stefank9** [microsoft/ProjectAcoustics#64]
Hi folks!
I'm looking into solutions for obstruction/occlusion/reverb for an upcoming project. Is there planned support for UE5?
Thanks!

**Comment by NoelCross** [comment]
Stefank,

We've had a few studios take a look at UE5 + PA and so far no issues have come up.  From what I'm aware of, the spatialization plugin API contract hasn't changed which means that PA should still continue to work when used with UE5.  If you run into any issues, please let us know.

Thanks,
Noel Cross
Microsoft Corp.
