### ISSUE TITLE
Unity + VS 2019 (Attach to Debugger) error with AcousticsEditor.cs

### ISSUE THREAD

**Issue by laurelhach** [microsoft/ProjectAcoustics#71]
Hi there,

I have an issue with the AcousticsEditor.cs script that throws error when I want to build the solution and attack VS 2019 to Unity 2020.3.16f1

I am not quite an expert so it might be a user issue :P but I can't find out what is the problem. I commented the section that was causing the issue, but in the end, I'd like to be able to keep the code untouched (it is probably used to talk to Azur)

Here is the issue:
Code issue : Starting Line 1276
WebException is causing the issue (sorry the description is in french)

![image](https://user-images.githubusercontent.com/6070076/132987691-3d90eb3a-216f-4a78-a04f-8279c320d585.png)

Thanks in Advance

**Comment by MikeChemi** [comment]
You're correct in your assessment that this code is used to get information back from Azure. In particular, it's reporting any errors that occurred with the bake submission process. The error indicates that there is a DLL mismatch -- the Project Acoustics code is looking for an older version of the System.Net implementation than exists in Unity 2020/VS 2019.

To clarify, this only happens right when you attach the debugger, correct? You don't actually get errors when submitting bakes? If so, to unblock yourself for now it's safe to remove all the webexception code and replace it with a generic error message. If you ever see the error pop up, we'll need more information to debug what went wrong, but if this is only hitting on debugger attach it's safe to just remove. In the meantime, we'll need to take a look at this on our side, but I don't have an estimate of when we'll have a solution for this problem.

**Comment by laurelhach** [comment]
Hi Mike,

Yes, this is only happening when I want to attach the debugger. I didn't submit yet to Azure, as I am not ready to send data, so I can't answer your question. My first try was to bake locally a level to see what the result would be :)

I actually did comment the section so I can attach and debug my project, and I will add a generic error msg as you suggest to make sure I don't forget about it.

That issue doesn't bother me that much, but I thought it would be worth mentioning it in case you didn't know about it.

Thanks again for your support!

**Comment by MikeChemi** [comment]
Closing this one out for now. We don't plan to make changes here any time soon.
