### ISSUE TITLE
Bake stuck on "Waiting for nodes to initialize"

### ISSUE THREAD

**Issue by Danreeves12** [microsoft/ProjectAcoustics#72]
Hello, 

After creating a project inside Unity, I sent the project to bake using Azura. The Azura Bake status is stuck on waiting for Nodes to initialize on the Acoustics window. 

After locating the job using the ID, I noticed that the project is active, but not progressed past 0.00% completion after 1 hour. 

Any advise?

**Comment by MikeChemi** [comment]
Sounds like there was a problem with initializing the nodes in the pool. Can you look at the pool on your Batch account and see what the node status is?

On the bake tab inside Unity, can you share the toolset version that you used?

**Comment by Danreeves12** [comment]
Hello,

After doing some research, I have concluded that I need to request a certain "quota" from Azure. According to the Project Acoustics help page - "By default, Azure Batch accounts are allocated a small number of cores, on a VM-size not supported by the Project Acoustics plugins. You will need to request a quota increase for at least one of the Fsv2- or H-series compute nodes"

I am pretty certain this is the issue.

Many thanks
________________________________

**Comment by MikeChemi** [comment]
I agree, insufficient quota can cause this. Let us know if you have any further issues.

**Comment by Danreeves12** [comment]
I appreciate the help.

How many should I request? I blindly requested 5.

Cheers
________________________________

**Comment by MikeChemi** [comment]
Depends on how big your scenes are and how fast you want the bakes back. I believe you request quota in terms of number of cores, so 5 wouldn't get you even a single F8 instance. If you wanted 5 nodes, you'd need to request 40 cores.

**Comment by Danreeves12** [comment]
Thank you again. I've sent in another request for 40.

Really appreciate your time. I'll message tomorrow with an update.

Cheers
________________________________
