### ISSUE TITLE
Project Acoustics Demo does not open in the latest version of Wwise and Unity

### ISSUE THREAD

**Issue by BenParisiFB** [microsoft/ProjectAcoustics#75]
Hello :)

I'm currently attempting to investigate Project Acoustics as a potential audio solution for our Unity game.
However, when I attempt to:

- Create a new Unity project (Version: 2020.3.7f1)
- Intergrate Wwise into that project (Version: 2021.1.3.7665)
- and Import MicrosoftAcoustics.Wwise.unitypackage

I get these compiler errors:
<img width="892" alt="CompilerErrors" src="https://user-images.githubusercontent.com/92057609/136274824-4ef3cbfd-55bb-4f6b-8566-1c3d9cd2f317.PNG">

I tried commenting out the offending lines. They are after all, calling functions that don't exist. But at runtime I get these errors:
<img width="932" alt="tritonRuntimeError" src="https://user-images.githubusercontent.com/92057609/136274852-dcff0fc3-93bd-4573-b5c2-138416750bd8.PNG">

What are the ideal versions of Wwise and Unity to use with Project Acoustics? And is it possible to update the example project to support the latest versions? 

Or am I just making a mistake in way I'm importing everything? The Quickstart guide does not mention that the Unity project already needs to be integrated into Wwise. But I tried importing the Project Acoustics package without integrating Wwise into my project, and it definitely seems to have dependencies there.

**Comment by BenParisiFB** [comment]
Hi MikeChemi Thanks for the reply :)

I see my first mistake was following this page: https://docs.microsoft.com/en-us/gaming/acoustics/unity-integration
and not this one: https://docs.microsoft.com/en-us/gaming/acoustics/unity-wwise-beta

These instructions make more sense. I followed them in that exact order. But I still have problems.
When I reach the step where I open AcousticsDemo/ProjectAcousticsDemo.unity and click play, I hear nothing.

Sorry in advance for these nitpicky questions but I want to make sure I get this perfect:
- The specific version of Wwise is 2021.1.0.7575.2069 That's the only 2021.1.0 version available for download. Is this version ok?
- (This seems super extra nitpicky, sorry) There is no package called `MicrosoftProjectAcoustics.Beta.Wwise.unitypackage`. There is a zip called `MicrosoftProjectAcoustics.Beta.Wwise.zip`. But the package in that zip is called `MicrosoftAcoustics.Wwise.unitypackage` is this ok? This is the one I'm supposed to use right?
- When integrating Wwise into the Unity project, should I select a Wwise project path? I assumed yes and chose the Wwise project in the zip next to the `MicrosoftAcoustics.Wwise.unitypackage`. But I tried tried not selecting a project and that didn't work either.
- Should I need to generate the sound banks before playing? When I generate the sound banks in Wwise I get a pile of errors about not having a license for ConvolutionReverb. But generating the sound banks is not mentioned in those top steps. It says I should be able to just play and hear something. I tried it both ways and didn't hear a sound in either case.

Thanks again so much for taking the time to help me with this. It looks like a super slick solution.

**Comment by BenParisiFB** [comment]
Yeah. It appears that I am unable to build the sound banks in this project at all without a license to that plugin. I think it might have given me a free trial, but my organization already has a license for convolution reverb for a different project. 
I'll sort this out and get back to you.

**Comment by BenParisiFB** [comment]
Thank you so much! It works perfectly. I deeply appreciate your patience and responsiveness to my questions.

Now that the root problem has been determined, I set up the project with the version of Wwise that I was intending on using (2021.1.3) and verified that it works in that version as well.

**Comment by BenParisiFB** [comment]
Hi Mike! 
I have a few more questions about Project Acoustics that I couldn't find answers for in the faq.

- Is there a possibility of supporting dynamic geometry in Unity in the future?

- Disk size is a concern for us. Is there a possibility of getting a bake somewhere between course and fine. Maybe there is a sweet spot we can hit with size and quality. 

- Alternately, I am completely unfamiliar with .bytes files. Is it possible that there are opportunities for compression here? Maybe we can decompress at runtime when we load our levels? (Sorry if this last question is silly. "Bytes" to me implies binary. So there's probably not a lot of room to crunch down further)

Thanks :)

**Comment by BenParisiFB** [comment]
Got it. thanks for those answers.

I have not baked a scene with one of our levels. I was basing my idea off of the project acoustics demo test scene, which has an ace file of ~ 100mb. Our levels are many many times this size. So I assumed the ace files would scale proportionally.

**Comment by nikunjragh** [comment]
> So I assumed the ace files would scale proportionally.

Depends. Probes are not laid out uniformly, but spread out coarsely in open areas and bunch together in narrower regions. Mike's suggestions above are with this in mind. Good thing is you can iterate by just pre-baking the scene with various max spacing values and look at probe counts. That is good enough to project numbers by comparing probe counts on sample scene.

**Comment by BenParisiFB** [comment]
Cool. This is helpful for us to consider. Thanks! :)

**Comment by MikeChemi** [comment]
Other things to consider too -- the sample scene has entirely too many probes for a scene of its size. For one, there are probes on all the ceilings, which is just silly :) (yes, our character actually can jump up there, but there's no reason for that) And that disk in the center definitely doesn't need as many as it does. This is a case where increasing the max spacing would drastically reduce the number of probes without hurting the end result.

**Comment by MikeChemi** [comment]
Thanks for working with us on the sample project setup issues. We've added the manual steps to our documentation page, so I'm closing this issue out. Please open a new issue for any other questions you have :)
