### ISSUE TITLE
Forever Compiling Unreal Engine (UE4)

### ISSUE THREAD

**Issue by RAI-Clara** [microsoft/ProjectAcoustics#77]
I've followed the installation instructions for setting up UE4 and Project Acoustics, but when I add the PA plugin to the plugins folder in my project, Visual Studios ends up compiling forever.  I've even left it to compile overnight, and it just won't budge after a certain point.
Specifically it stalls at UE4Editor-ProjectAcousticsBakeUI.dll's creating library UE4Editor-ProjectAcousticsBakeUI.suppressed.lib stage.

I'm pretty sure I followed all the instructions right, and wwise itself works with my UE projects.  It's only when I add the plugin do I have issues.

the wwise version I'm using is 2019.2.14, my unreal engine version is 4.26.1, and I'm currently using Visual Studio 2019.
Thank you.

**Comment by MikeChemi** [comment]
Hi @RAI-Clara, I think this is a problem with the PatchWwise.bat script. AudioKinetic updates their UE integration faster than we release updates to that script and they sometimes get out of sync.

I believe the problem is a missing '}' at the end of AkAudioDevice.cpp. Please have a check

**Comment by RAI-Clara** [comment]
thank you, that worked!
But now when the project starts and the python scripts run I get this error in the outputlog error:
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "ProjectATest/Plugins/ProjectAcoustics/Content/Python/init_unreal.py", line 3, in <module>
LogPython: Error:     import init_project_acoustics
LogPython: Error:   File "ProjectATest/Plugins/ProjectAcoustics/Content/Python\init_project_acoustics.py", line 45, in <module>
LogPython: Error:     from Microsoft.Azure.Batch import ContainerRegistry
LogPython: Error: ModuleNotFoundError: No module named 'Microsoft'

**Comment by MikeChemi** [comment]
This looks like the same issue as #10 . Follow the instructions there to check to see if the DLLs are blocked with "mark of the web"

**Comment by RAI-Clara** [comment]
yep, that worked too, thank you so much!!
I've been spending forever trying to get this to work.
