### ISSUE TITLE
Can I use a custom HRTF? UE4 

### ISSUE THREAD

**Issue by RAI-Clara** [microsoft/ProjectAcoustics#79]
Hello, I was wondering if you can create a custom HRTF with Project Acoustics Version 2 in UE4, or at least modify the HRTF a bit?
I need to be able to create/modify HRTF models in some way for the project I'm working on.

Thank you.

**Comment by MikeChemi** [comment]
We don't support customizing the HRTFs at this time.

**Comment by RAI-Clara** [comment]
Is there any work arounds for this?
Or can we at least adjust the distance between the ears?
Also, will there be support for this in the future maybe?

**Comment by MikeChemi** [comment]
If you can find a spatializer plugin for Wwise that does what you want (or develop your own), the [instructions here](https://docs.microsoft.com/en-us/gaming/acoustics/unreal-integration) will let you use that spatializer on the dry path in conjunction with the Project Acoustics reverberation.

For various reasons, we don't allow swapping out the spatializer in Unity, so that won't help you.

Nothing to share about future support for HRTF customization in Project Acoustics at this time. I can say it's not on our short-term roadmap.

**Comment by RAI-Clara** [comment]
Ok, I'll see if I can get the spatializer plugin to work then.

Would this work for the PA + Wwise version for Unity too?  Or all around Unity will not be able to do any spatialization adjustments even in wwise.

**Comment by MikeChemi** [comment]
You're correct - this will also work in Unity + Wwise. Only standalone Unity is not going to work.

**Comment by MikeChemi** [comment]
This will not work out of the box, although it should be possible to modify the UE plugin code to handle this. UAcousticsAudioComponent::TickComponent does one query/parameter set for the primary listener. You'll need to update this to handle all the listeners. Other than that, should be OK.

**Comment by RAI-Clara** [comment]
hmmm do you have any suggestions for a spatializer plug-in that would be free to use?
I tried implementing the recommended auro headphones plugin, but it's requiring me to get a license.

**Comment by MikeChemi** [comment]
Sorry, as a Microsoft employee I can't comment on licensing terms for non-Microsoft tech.

**Comment by RAI-Clara** [comment]
ohh ok sorry about that,

then is MS HRTF still supported for wwise?  I saw that it exists, but I can't seem to find any plug-in download and I don't see it as a pre included plugin-in for wwise either.

https://www.audiokinetic.com/library/2017.1.9_6501/?source=Help&id=ms_hrtf_plug_in

**Comment by MikeChemi** [comment]
No problem :)

The MS HRTF plugin has been replaced by the Wwise plugin included in Project Acoustics, or alternatively the MS Spatial Sink plugin (in Wwise versions <= 2019) or the native Wwise spatial audio pipeline (in Wwise 2021+)
