### ISSUE TITLE
ProjectAcoustics as Wave-based Multi-Channel RIR Simulator

### ISSUE THREAD

**Issue by schmiph2** [microsoft/ProjectAcoustics#81]
Hi everyone

Thanks for providing this fantastic audio engine! I am an audio researcher looking for an easy to use, fast, wave based room impulse simulator. Most simulators out there are either very slow or based on the image source method. In contrast, this engine seems like it would be perfect for me. 
I found out that Nikunj Raghuvanshi's work on the adaptive rectangular decomposition method probably led to this engine. Hence my question: Is this engine based on the ARD method and therefore purely wave based? Can I use it to simulate binaural multichannel RIRs with correct phase relationships (e.g. for beamformer applications)? 

Thank you for a short comment.

**Comment by MikeChemi** [comment]
> "I found out that Nikunj Raghuvanshi's work on the adaptive rectangular decomposition method probably led to this engine"

Even better, this engine *is* @nikunjragh 's ARD. We don't have any support for IR export at this time, only the perceptual acoustic parameter fields.

**Comment by schmiph2** [comment]
Oh wow, even better! Do you have any plans to support IR export at the moment?

**Comment by nikunjragh** [comment]
Hi @schmiph2 -- Not at the moment, no. But, potentially in the future depending on many internal factors that we cannot commit on currently. You're not alone in asking for this and these requests certainly factor into our roadmap. May I ask if you want to use this for purely academic purposes, or for potential commercial application?

**Comment by schmiph2** [comment]
@nikunjragh first of all, thank you for developing and publishing the ARD method. And thanks for your comment, I hope the IR export will be implemented soon. Currently our project is still purely academic research. But we have a commercial application for an industrial partner in mind.

**Comment by nikunjragh** [comment]
Thanks for your response @schmiph2, closing the issue for now -- we're always super happy to see interest in the tech. I've noted your response and we'll factor it in our future planning.
