### ISSUE TITLE
Project Acoustics UE5 troubles.

### ISSUE THREAD

**Issue by itmewuf** [microsoft/ProjectAcoustics#89]
I'm having a few issues with Project Acoustics for UE5

### 1. The plugin will say upon each and every load into the same project that "Project Acoustics is performing first run setup for the required python dependencies. This may take a minute."
I'm not sure if this intended behavior, but it doesn't seem like it considering it says "first run."

### 2. When in the Bake Acoustics mode and on the Probes tab, it says "Python is required for Project Acoustics baking. Please enable the Python plugin."
I can verify that the Python plugin was already enabled and functioning normally. This message appears in place of any content that would have been in the Probes tab.

The only errors in the Output Log were the ones shown below:

```
LogPluginManager: Mounting Engine plugin PythonFoundationPackages
LogPluginManager: Mounting Engine plugin PythonScriptPlugin
LogPluginManager: Mounting Engine plugin PythonAutomationTest
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/PythonFoundationPackages/Content/' mounted to '/PythonFoundationPackages/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/PythonScriptPlugin/Content/' mounted to '/PythonScriptPlugin/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Tests/PythonAutomationTest/Content/' mounted to '/PythonAutomationTest/'
LogPython: Using Python 3.9.7

LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "G:\UE_5.0/Engine/Plugins/Marketplace/ProjectAcousticsNative/Content/Python\init_project_acoustics.py", line 26, in <module>
LogPython: Error:     import clr
LogPython: Error: ModuleNotFoundError: No module named 'clr'
LogPython: Error: During handling of the above exception, another exception occurred:
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "G:/UE_5.0/Engine/Plugins/Marketplace/ProjectAcousticsNative/Content/Python/init_unreal.py", line 3, in <module>
LogPython: Error:     import init_project_acoustics
LogPython: Error:   File "G:\UE_5.0/Engine/Plugins/Marketplace/ProjectAcousticsNative/Content/Python\init_project_acoustics.py", line 43, in <module>
LogPython: Error:     import clr
LogPython: Error: ModuleNotFoundError: No module named 'clr'

LogPython: Display: Generating Python API stub file...
LogPython: Display:   ...generating Python API: glue code
LogPython: Display:   ...generating Python API: additional code
LogPython: Display:   ...generated: R:/Downloads/UnrealDemos/AcousticsGameUE5/Intermediate/PythonStub/unreal.py
```
### 3. Clicking on the Bake tab will crash the project immediately.

```
Assertion failed: IsValid() [File:D:\RocketSync\5.0.0-19505902+++UE5+Release-5.0\Working\Engine\Source\Runtime\Core\Public\Templates\SharedPointer.h] [Line: 1074]

UnrealEditor_ProjectAcousticsBakeUI!SAcousticsBakeTab::Refresh() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\ProjectAcoustics\Source\ProjectAcousticsBakeUI\Private\AcousticsBakeTab.cpp:217]
UnrealEditor_ProjectAcousticsBakeUI!FAcousticsEdMode::OnClickBakeTab() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\ProjectAcoustics\Source\ProjectAcousticsBakeUI\Public\AcousticsEdMode.h:110]
UnrealEditor_ProjectAcousticsBakeUI!SAcousticsEdit::OnActiveTabChanged() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\ProjectAcoustics\Source\ProjectAcousticsBakeUI\Public\SAcousticsEdit.h:90]
UnrealEditor_ProjectAcousticsBakeUI!TBaseSPMethodDelegateInstance<0,SAcousticsEdit,1,void __cdecl(enum AcousticsActiveTab),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\RocketSync\5.0.0-19505902+++UE5+Release-5.0\Working\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:309]
UnrealEditor_ProjectAcousticsBakeUI!SSegmentedControl<enum AcousticsActiveTab>::CommitValue() [D:\RocketSync\5.0.0-19505902+++UE5+Release-5.0\Working\Engine\Source\Runtime\Slate\Public\Widgets\Input\SSegmentedControl.h:540]
UnrealEditor_ProjectAcousticsBakeUI!UE::Core::Private::Tuple::TTupleBase<TIntegerSequence<unsigned int,0>,enum AcousticsActiveTab>::ApplyAfter<void (__cdecl SSegmentedControl<enum AcousticsActiveTab>::*const &)(enum ECheckBoxState,enum AcousticsActiveTab),SS() [D:\RocketSync\5.0.0-19505902+++UE5+Release-5.0\Working\Engine\Source\Runtime\Core\Public\Templates\Tuple.h:324]
UnrealEditor_ProjectAcousticsBakeUI!TBaseSPMethodDelegateInstance<0,SSegmentedControl<enum AcousticsActiveTab>,1,void __cdecl(enum ECheckBoxState),FDefaultDelegateUserPolicy,enum AcousticsActiveTab>::ExecuteIfSafe() [D:\RocketSync\5.0.0-19505902+++UE5+Release-5.0\Working\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:309]
```

These issues were replicated on an unmodified Project Acoustics "AcousticsGameUE5" sample project as well as the LyraStarterGame project.

Any help would be appreciated.

Thank you,

**Comment by KyleStorck** [comment]
Hi @itmewuf. Thanks for trying out Project Acoustics. I think I know what the problem is. One of the installations during that first run setup is failing. That is why you see the setup each time, and why the plugin is crashing.

One of the installations in that first run setup requires Visual Studio 2019 installed, along with .NET Framework Targeting pack v4.0 installed. And VS 2022 won't work. VS 2019 is required. This is an unfortunate requirement we're working to improve. 

So please try installing VS 2019, along with .NET framework 4 targeting pack, which you can find in VS Installer... Modify... Individual Components. 

![image](https://user-images.githubusercontent.com/1233941/169305718-17f342fe-a4b8-4257-ad96-3f1936923931.png)


If you don't want to or are unable to install VS2019, there is another workaround I could offer.

**Comment by itmewuf** [comment]
Thank you kindly for the reply.

Unfortunately, installing the .net framework 4 targeting pack within VS2019 (as well as restarting the machine for good measure) didn't resolve the issue. I'd be willing to try that other workaround then, I suppose.

**Comment by KyleStorck** [comment]
@itmewuf I'd like to understand your problem a bit better. Could you please go to the following location in a command prompt in your UE5 installation, and try to install this one Python package. I'd like to see the output from it. This would help us a lot.

```
cd c:\Program Files\Epic Games\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64
python.exe -m pip install --upgrade pythonnet
```

For instance mine looked like this: 
<img width="917" alt="image" src="https://user-images.githubusercontent.com/1233941/169415912-1cfc6285-b4aa-4441-8afc-02d1cdfcaa46.png">

**Comment by itmewuf** [comment]
Whoa, loads of errors, looks promising.

The log was too big to paste here, so here's an external link: [pastebin](https://pastebin.com/gg2vUGiN)

Does this mean there's possibly something wrong with my VS2019 install?

**Comment by KyleStorck** [comment]
Yup, great data! Haven't seen these errors before. Looking...

**Comment by KyleStorck** [comment]
Ya, I'm a little stumped on your errors. Could be a problem with your VS. The only solutions I've seen online for those errors are: install the Windows SDK in VS or reinstall VS2019. Up to you if you want to try those.

The workaround I proposed before is to download a pre-built package for PythonNet and install that directly in Python. The steps for that would be:

1. Download pythonnet‑2.5.2‑cp39‑cp39‑win_amd64.whl from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pythonnet 
2. Within `c:\Program Files\Epic Games\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64`, run: `python.exe -m pip install <downloaded whl>`
3. That should install PythonNet for your UE5, and the Project Acoustics plugin should be satisfied.

**Comment by KyleStorck** [comment]
Kinda good news though. I was able to reproduce your error on my own system. So I'm getting closer to finding the minimum set of requirements.

**Comment by KyleStorck** [comment]
Ok @itmewuf . I was able to get past your error by installing ".NET Desktop development" package in VS installer. If you haven't done the workaround yet, could you try installing ".NET Desktop development" and seeing if PythonNet will install for you. So the minimum set of packages I have installed that made it work for me are:

1. .NET Framework 4 targeting pack (Individual component)
2. .NET desktop environment (Big package in workloads)

**Comment by itmewuf** [comment]
I did the workaround and it worked perfectly -- thank you very much, Kyle!

I wish I could test the second solution to verify, but it sounds like it at least worked on your end when trying to fix the issue. I can at least say that I checked and I _did not_ have .NET Desktop development installed, so that was likely it!

Thank you again, I appreciate it greatly.

**Comment by Jimmanator** [comment]
Thank you both for working through this. I had the same exact errors. I had a go at the second solution (ie install NET Framework 4 targeting pack, and .NET desktop development) and can confirm that is worked for me

**Comment by hectorC** [comment]
> The workaround I proposed before is to download a pre-built package for PythonNet and install that directly in Python. The steps for that would be:
> 
> 1. Download pythonnet‑2.5.2‑cp39‑cp39‑win_amd64.whl from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pythonnet
> 2. Within `c:\Program Files\Epic Games\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64`, run: `python.exe -m pip install <downloaded whl>`
> 3. That should install PythonNet for your UE5, and the Project Acoustics plugin should be satisfied.

This one worked for me. I have VS2022 and didn't want to install 2019 so this worked fine to solve the issue.

**Comment by maxjaudio** [comment]
I am still running into this issue with VS2022 (.NET Framework 4 targeting pack and .NET desktop environment installed).

[Pastebin ](https://pastebin.com/5ifc9Ypu)

![image](https://github.com/microsoft/ProjectAcoustics/assets/31394147/251740e3-4c5c-421f-92ab-c79a3023d582)

I can't figure out why it doesn't recognize pycparser. I believe I've installed that. @KyleStorck any recommendations?

**Comment by KyleStorck** [comment]
PythonNet 2.5.2 is an old version. PythonNet 3 is out now and our latest plugin offering should set it up correctly for you. 

First, might be best to ensure you're starting fresh. Clean up your current UE python packages by doing the purge routine below, and then try starting a project with the latest version of our plugin from the marketplace.

python.exe -m pip uninstall pythonnet
python.exe -m pip cache purge
