### ISSUE TITLE
Seeing Voxels after a bake has been made

### ISSUE THREAD

**Issue by onaccident** [microsoft/ProjectAcoustics#9]
Hello!

Ok, so I've been working with Viking Village integrating project acoustics and doing a bake. I have the .ace file and have that tied to an acoustics manager gameobject with the ace file loaded. I'm playing a .wav file and positioning it with prebaked objects (the houses) in between it and the source, in order to test the occlusion. The Acoustics Adjust is tied to the audio source, enable acoustics is checked, occlusion is driven up to 2, transmission to 0, wetness to highest, but it does not occlude. 

Is there anyway to resee the voxels? I can see them when I go to bake, and previewing what I'm going to get. What I'm worried about is somehow post bake I've "desynced" the ace file and I need to reattach it, but I can't seem to find the setting to turn the voxels back on. Under gizmos, the voxels and probes are checked but I see nothing. 

Thanks!
Megan Frazier

**Comment by MikeChemi** [comment]
Hi Megan!

Acoustics voxels are only visible while in play mode. Drawing them causes frame rate to drop, so we only draw them within a few meters of the main camera by default. If you turn on gizmos, enter play mode, and look around the main camera, you should see voxels.

If you don't see voxels, double check that your Acoustics Manager's transform is set to identity.

**Comment by onaccident** [comment]
Could you send a screenshot of the acoustics manager transform being set to identity? Mine does not appear to have any setting like that. [Not seeing any voxels in my bake - your demo looks fine]

**Comment by MikeChemi** [comment]
Sure! It should look like this (with your ACE file listed instead):
![image](https://user-images.githubusercontent.com/1040735/70366685-ff1f2100-184d-11ea-8097-3548b8d1922e.png)

**Comment by onaccident** [comment]
Nice, I found them!

Separate question - the probes are too high and the voxels are not placed where I saw them to be when I baked them. When I baked them, they appeared to be player ear level and now they are probably a story (4 meters?) too high.  I played around with the probe location region, but it doesn't seem to lower them. How does one transform the ace file down?

**Comment by onaccident** [comment]
I actually just figured this out, sorry for the spam! 

The game object that is the acoustics manager is affected by unitys position. It needs to be perfectly aligned to wherever it was for the bake. I must have moved it.

**Comment by MikeChemi** [comment]
Great that you found them! Sorry to hear they don't line up properly. You are correct that Unity's position does affect things. If the Acoustics Manager is parented to another object, that parent object's transform will be applied. Similarly, if the actual scene has changes position after being baked the Acoustics Manager also needs to have its position changed by the same amount.
