### ISSUE TITLE
Azure Bake Button not working 

### ISSUE THREAD

**Issue by yash086** [microsoft/ProjectAcoustics#90]
I have downloaded the project acoustics plugin from the Epic marketplace and had followed all the steps mentioned in the Inside Unreal Stream and had to uninstall Visual Studio 2022 and reinstall 2019 for the plugin to work as intended.

After setting up everything by following the steps i.e Tagging the objects, Assigning properties to materials, prebaking or previewing the probes, and when coming to the last step of baking I have entered all the details of my Azure account leaving the " Custom Azure Container details" and when I click on " Submit Azure Bake ", the button does not do anything while the Status shows Ready for processing. I have even checked my Jobs section in the Azure portal and there is no new job created. 

Any help would be appreciated.

**Comment by KyleStorck** [comment]
Hi @yash086. Are there any error messages in the Output Log?

**Comment by yash086** [comment]
There were no errors, I restarted the editor and it was working fine. Can you please help with me the local baking?

I created a new folder for preparing local bake in directory: Content\_Game\ProjectAcoustics\AcousticsData
, copied the Bake Tools files to this directory and executed the "RunLocalBake.bat" file from file explorer.

The simulation took about three and half hours on my Ryzen 9 3900x and has generated a ace archive file in the time stamp folder i copied it and pasted it in directory: Content\Acoustics\. Placed the Acoustic space in the level and assigned the Ace file to the Acoustics Data. Now when I play in editor the error : Failed to load ACE file [Content/Acoustics/L_Expanse_AcousticsData.ace](x3)

I tried baking it again and found the same issue with the newly generated ACE file.

**Comment by KyleStorck** [comment]
Thanks for the pictures. They were very helpful. I think there were 2 problems with your process. First is the ACE file does NOT need to be extracted. Just leave it as is. And the second is how you moved the ACE file to your project. Sometimes when you drag-n-drop directly into the Content Browser, the actual ACE file does not get copied into your project's file hierarchy. It just creates a reference to the original file. 

This time try copying the ACE (no extraction needed) file directly to that folder in your project in File Explorer (LyraStarterGame/Project/Content/Acoustics) and then doing a file Import. 
![image](https://user-images.githubusercontent.com/1233941/169653738-d3f9c032-d608-461b-bf47-611210d96171.png)

The goal is to have the original ACE file physically located in the Content/Acoustics folder and successfully imported into Unreal. The good news is your ACE file looks good by the size (22MB).

**Comment by yash086** [comment]
Thank you so much kyle!. Yes, coping the file manually in the file explorer and then importing the same file again in Unreal seems to solve the issue 👍. But this is a little cumbersome and I would love to see this improved as most of the people would drag and drop their files in unreal and would face the same issue as me. Thanks once again :)

**Comment by KyleStorck** [comment]
Glad to hear that worked @yash086. Understood about the clunky workflow, we'll work on that.

Did you want to investigate your "Azure Bake Button not working" issue. That's a strange one I would need more info on. If so, could you provide a picture of your bake tab in the state where the button does not work (feel free to hide your creds) and also a pic of the Output Log. If not, then I will close this issue.

**Comment by yash086** [comment]
No, the bake button is working. I just need to restart the editor and thanks a lot for your support.
