### ISSUE TITLE
Local baking is not working for me

### ISSUE THREAD

**Issue by alex37009** [microsoft/ProjectAcoustics#91]
I have downloaded the sample project on microsoft website to try baking on my local pc.
like for download the sample project: [https://www.microsoft.com/en-us/download/details.aspx?id=104115]
I had to reinstall visual studio 2019 with 'development.net' enable to have the python plugin
working since it's not working with visual studio 2022.
Then i followed the live presentation on youtube:
--> Adding objects
 -->Setup materials
-->Calculate probes
-->Prepare bake (choose the file destination)
-->Download the local bake tool (extract the files from the downloaded file
to the same destination as in the 'Prepare bake'step.
-->Run the batch 'Run local bake' file that comes with the downloaded file in the previous step
A new screen appears quickly and an empty folder is created "5" in the destination folder.
A subfolder with the name of the hour i execute the batch file is created but is empty.
Can someone help me to understand what i missed.
Thanks

**Comment by KyleStorck** [comment]
Hi @alex37009. It appears something went wrong with your local bake and it exited out quickly. If you run that batch file from command prompt the output will get saved and we can see what happened. Could you please run that batch file from the command prompt and reply back with what the output was?

**Comment by alex37009** [comment]
C:\>J:\ProjectAcousticsTest\Plugins\ProjectAcoustics\AcousticsData\RunLocalBake.bat

C:\>REM Execute acoustics bake locally

C:\>set MM=5/

C:\>set DD=02

C:\>set YYYY=

C:\>set HH= 8

C:\>if " " == " " (set HH=08 )

C:\>set MN=43

C:\>md "5/02-0843"

C:\>copy "*_config.xml" 5/02-0843
La syntaxe de la commande n’est pas correcte.

C:\>copy "*.vox" 5/02-0843
La syntaxe de la commande n’est pas correcte.

C:\>for %i in (*_config.xml) do Triton.LocalProcessor.exe --configfile %i --WorkingDir 5/02-0843

C:\>REM Clean up

C:\>del "5/02-0843\*.enc"
Impossible de trouver C:\5\02-0843\*.enc

C:\>REM .ACE file is produced upon successful bake. Manually import this into your project content.

C:\>J:\ProjectAcousticsTest\Plugins\ProjectAcoustics\AcousticsData\RunLocalBake.bat

C:\>REM Execute acoustics bake locally

C:\>set MM=5/

C:\>set DD=02

C:\>set YYYY=

C:\>set HH= 8

C:\>if " " == " " (set HH=08 )

C:\>set MN=43

C:\>md "5/02-0843"
Un sous-répertoire ou un fichier 5/02-0843 existe déjà.

C:\>copy "*_config.xml" 5/02-0843
La syntaxe de la commande n’est pas correcte.

C:\>copy "*.vox" 5/02-0843
La syntaxe de la commande n’est pas correcte.

C:\>for %i in (*_config.xml) do Triton.LocalProcessor.exe --configfile %i --WorkingDir 5/02-0843

C:\>REM Clean up

C:\>del "5/02-0843\*.enc"
Impossible de trouver C:\5\02-0843\*.enc

C:\>REM .ACE file is produced upon successful bake. Manually import this into your project content.

**Comment by alex37009** [comment]
C:\>J:\ProjectAcousticsTest\Plugins\ProjectAcoustics\AcousticsData\CommandLineLocalBakeTools\RunLocalBake.bat

C:\>REM Execute acoustics bake locally

C:\>set MM=5/

C:\>set DD=02

C:\>set YYYY=

C:\>set HH= 8

C:\>if " " == " " (set HH=08 )

C:\>set MN=55

C:\>md "5/02-0855"

C:\>copy "*_config.xml" 5/02-0855
La syntaxe de la commande n’est pas correcte.

C:\>copy "*.vox" 5/02-0855
La syntaxe de la commande n’est pas correcte.

C:\>for %i in (*_config.xml) do Triton.LocalProcessor.exe --configfile %i --WorkingDir 5/02-0855

C:\>REM Clean up

C:\>del "5/02-0855\*.enc"
Impossible de trouver C:\5\02-0855\*.enc

C:\>REM .ACE file is produced upon successful bake. Manually import this into your project content.

**Comment by KyleStorck** [comment]
This looks like a localization failure on our part. The script is supposed to create a new directory based on the locale's time/date, and whichever locale you are in, produced an unexpected date format that isn't a valid directory name.

Until we get a fix out, you can just create your own directory and modify the script to point to that. The goal of the script is to copy the config and vox file to that directory, and then run Triton.LocalProcessor.exe on those files. Modifying the RunLocalBake script to something like this should work for you
 
```
REM set MM=%date:~4,2%
REM set DD=%date:~7,2%
REM set YYYY=%date:~10,4%
REM set HH=%time:~0,2%
REM if "%HH:~0,1%"==" " (set HH=0%time:~1,1%)
REM set MN=%time:~3,2%
md myNewDirectory
copy "*_config.xml" myNewDirectory
copy "*.vox" myNewDirectory
for %%i in (*_config.xml) do Triton.LocalProcessor.exe --configfile %%i --WorkingDir myNewDirectory
REM Clean up
del "myNewDirectory\*.enc"
REM .ACE file is produced upon successful bake. Manually import this into your project content.
```

**Comment by alex37009** [comment]
Thanks i am able to bake now, but then when i assign the ace file to the accoustic space it's not working.

I have this message in the log.

LogAcousticsRuntime: Error: Failed to open ACE file for reading: [../../../../TomTutorial/ActionRoguelike/Content/Acoustics/TomTutorial.ace]

LogAcousticsRuntime: Error: Failed to load ACE file [Content/Acoustics/TomTutorial.ace

I have tried to bake again the map, the ace file is exactly the same but always have this log message.
-->I check debug controls (Acoustics Enabled ON, States ON Voxels ON). Nothing is showing.
-->I check in project Settings Spatialization Plugin, Reverb Plugin, Source Date Override Plugin.
-->I Make a new Attenuation with and assign a new created AcousticsSourcceDataOverrideSourceSettings
-->I use the new attenuation in  some cue files.

I have tried with two new project but it's never working, i have tried to add my baked .ace file in the sample
project to see but i have the same issue log file Error....
To test i have take the .ace from the sample project but no more succes

Did i miss something ?

**Comment by KyleStorck** [comment]
Can you check that the ACE file is physically located in the Content/Acoustics folder? Sometimes if you drag and drop the ACE file into UE, it doesn't physically copy the file, and it only creates a reference to the original file. Your Content/Acoustics folder should look something like this in File Explorer:
![image](https://user-images.githubusercontent.com/1233941/169905141-25dc4a55-d7fd-4f1a-a1b1-392e37e9bd86.png)

**Comment by NoelCross** [comment]
We've updated the bake tools to handle parsing dates correctly for non-US locales.  Download the updated local bake tools to get the fix.

**Comment by alex37009** [comment]
i think what causing the problem was that my folder with the ace file
was not directly under Content but in a subfolder.
I have moved all the Acoustics folder with ace file directly under the content
folder and then it's working.
Thanks
