### ISSUE TITLE
AcousticsSpace not loading my .ace files (local bake)

### ISSUE THREAD

**Issue by EXpMiNi** [microsoft/ProjectAcoustics#93]
Hey, so I've been trying a bit of everything to make it work, but I have no idea what I'm doing wrong in the process.

My first issue was like load of people was the python thing, I solved it by installing Visual Studio Community 2022 (I had only 2019 installed before).

The plugin is working so far, managed to grab the geo/nav to tag them. 
Compute the preview and see the probs and voxel grid. 
When I bake locally it's telling me to download some files and to put that in the same folder as where my bake files will be. 
Run the RunLocalBake.bat, wait a bit and have a **.ace**/**.vox**/**.xml** files. 
Import the the **.ace** file in unreal.
Load it into the the **AcousticsSpace**.
Check the debug boxes to see if it's working and find out it's not.

So all of that was on a new project, I tried to download the UE5 project you provide, I wasn't able to open it because **HoudiniEngine** was creating a conflict and prevent me to build the plugin on startup, so I removed it and it was going through.
The project is working fine, so I tried to import the **.ace** file from the project to my own project to see if it was working (it doesn't work).
I tried to import my **map** and **.ace** file into your project and it wasn't working either, but in this case loading your **.ace** file in my **map** was working.

So my guess is there are dependencies from your project I don't have on my own and the local baker isn't working, I'm clueless, any ideas?

Cheers.

**Comment by KyleStorck** [comment]
Hi @EXpMiNi. Can you post any error messages that show up in the Output Log when AcousticsSpace fails to load? 

First thing to check is if the ACE file is physically located within the "Content/Acoustics" folder. The ACE file needs to be in this exact folder. Sometimes if you drap and drop the ACE file into UE, it doesn't physically copy the file, it only references the original file. In File Explorer, "Content/Acoustics" should look something like this:
![image](https://user-images.githubusercontent.com/1233941/170089048-e7d670c6-7787-4bd4-b4cd-07433d7546a0.png)

**Comment by EXpMiNi** [comment]
Ah thank you a lot @KyleStorck !
It was indeed the .ace file physically missing in the folder, it's loading something and it's working now !

**Comment by KyleStorck** [comment]
Glad to hear! Let us know if you have any other trouble.
