### ISSUE TITLE
Project Acoustics 3.0 now available!

### ISSUE THREAD

**Issue by NoelCross** [microsoft/ProjectAcoustics#94]
We're happy to announce that a new version of Project Acoustics is available! It includes many bug fixes and new features. The documentation has been updated at http://aka.ms/acoustics with information about new features and beta features. Here's a few highlights:

- Deep integration with Unreal Engine 5
- Local bake support in Unreal Engine
- Wwise 2021 object pipeline support
- Faster bake times
- Support for larger map sizes
- Size and fidelity improvements for acoustic data file compression
- Performance improvements for acoustic data lookup at runtime
- Highly optimized spatializer and reverberator DSP
- Various bug fixes and performance improvements

Check out the [livestream with Epic Games](https://youtu.be/3uocCX0AMIg) discussing the latest release. You can find the version 3.0 downloads from the links below. Thanks for using Project Acoustics!

Unity: https://www.microsoft.com/en-us/download/details.aspx?id=57346
Unreal with Wwise integration: https://www.microsoft.com/en-us/download/details.aspx?id=58090

**Comment by Yoerik** [comment]
Hi @NoelCross !

It seems the Wwise plugin is not included in the download links.

**Comment by NoelCross** [comment]
@yoerik Whoops.  The Wwise plugin package was hidden so I've fixed that now.  Sorry for the inconvenience.

**Comment by Yoerik** [comment]
No worries :) All is looking good now, thanks!
