### ISSUE TITLE
Local Bake not working

### ISSUE THREAD

**Issue by agobbett** [microsoft/ProjectAcoustics#98]
Hi,

I am trying to do a local bake to give it a test run in UE5, following the process on the Project Acoustics website. I have got to the stage of importing the .ACE file into the project (in the content>Acoustics folder as directed) and loading it into the AcousticsSpace actor in the level. But from here I can't seem to get it to work. Using the debug on the actor it appears the file isn't getting loaded when playing the level. I've tried multiple times and on multiple projects. I even tried re-baking a small portion of the Acoustics sample project and get the same problem. I have attached the debug Draw Stats readout to show the file isn't getting loaded in as it should.

I'm wondering if I am doing something wrong in the baking process, or if there's a bug somewhere?

![Screenshot 2022-06-15 135348](https://user-images.githubusercontent.com/63791978/173831901-a8be78e6-66a7-4453-a3aa-951dac3297f8.png)
![Screenshot 2022-06-15 135420](https://user-images.githubusercontent.com/63791978/173831933-cb2f7071-1356-4017-8a61-e80cf37e1736.png)

Error in Output log:
LogAcousticsRuntime: Error: Failed to open ACE file for reading: [J:/.../Content/Acoustics/AcousticsGameUE5_AcousticsData.ace]
LogAcousticsRuntime: Error: Failed to load ACE file [Content/Acoustics/AcousticsGameUE5_AcousticsData.ace]

**Comment by KyleStorck** [comment]
Hi @agobbett. Can you check that your ACE file physically exists in the Content/Acoustics folder? If you drag-and-drop the ACE file, it doesn't physically get copied. It should look like this 
![image](https://user-images.githubusercontent.com/1233941/173848723-5666eee1-605e-4f8c-a232-92d1503c9d0b.png)

**Comment by agobbett** [comment]
Hi Kyle, I think that was the issue, I was dragging the ACE file straight into UE5 content browser. Just dragged it into the File Browser, opened the game and it works! Thanks

**Comment by dr0p1n** [comment]
may I add to this, as it did not work with the drag and drop in explorer on my end? restarting the engine did not work for me :( it is a local bake as well.
![image](https://user-images.githubusercontent.com/44287611/202570378-e2109588-979e-4c2d-8415-c7c128943e18.png)

**Comment by KyleStorck** [comment]
To be clear, did you drag and drop into Windows Explorer or the Content Browser in UE? Drag and dropping into the Content Drawer should work. If you drag and drop into Windows Explorer, you will have to manually import in UE.

**Comment by dr0p1n** [comment]
Ok that is weird! So agobbett stated that dragging into the file explorer worked and content browser didn't. For me it now worked dragging it into the content browser... thanks ^^
